### ISSUE TITLE
AI Notebooks

### ISSUE THREAD

**Issue by Michellehbn** [ovh/public-cloud-roadmap#100]
#### User story ####
As a customer, 
I want a better UI
so that I am able to start and manage my notebooks in AI Training with ease. 

**Acceptance criterias**
- specific category on the left control panel menu
- specific table to list my existing notebook
- ability to select JupyterLab or VSCode
- ability to add labels
- ability to authorize public access (unsecure access)
- quick link access to JupyterLab or VSCode

**Mockup**
<img width="1043" alt="notebooks" src="https://user-images.githubusercontent.com/16922182/116582049-3d225680-a915-11eb-89b6-bba1a5f88057.png">

**Comment by baaastijn** [comment]
Hello, The Beta is now live !
Available in your Public Cloud control panel

Commercial info FR : https://www.ovhcloud.com/fr/public-cloud/ai-notebook/
Commercial info EN : https://www.ovhcloud.com/en/public-cloud/ai-notebook/
70€ VOUCHER to test it 👍 

Official Documentation : https://docs.ovh.com/gb/en/publiccloud/ai/notebooks/

Discuss with us ! tech team : https://discord.gg/vXVurFfwe9
