### ISSUE TITLE
Object Storage - Cold Archive (new class of storage)

### ISSUE THREAD

**Issue by JacquesMrz** [ovh/public-cloud-roadmap#109]
As a user I want a storage class on which I'll be able to store Objects for archive purpose (minimum 1 year). This storage class will propose a high level of resilience as well as a very low price pr TB stored.

Lab page : https://labs.ovh.com/cold-archive
Beta test is open ! 

Operations:
Archive
List
Delete
Restore

Target API : S3

**Comment by Izaia64** [comment]
The Alpha test are opened ! You can suscribe by sending an email. All information are available in OVHcloud lab page : https://labs.ovh.com/cold-archive

**Comment by paschembri** [comment]
The documentation is not clear about the id required when defining aliases (https://docs.ovh.com/fr/storage/object-storage/s3/getting-started-with-cold-archive/).

- What is the purpose of defining `myid` ?
- Is it related to the id of the cloud project ?

**Comment by Izaia64** [comment]
The archive and restore time depends on the volume of data and the number of objects.
The restore time depends on the volume of data and the number of objects.
For a volume of a few TB, it can take a few minutes or a few hours
This is why the SLA is 48 hours although in reality the time can sometimes be much shorter.

**Comment by Izaia64** [comment]
Beta phase 2 is now live. You can consult the web page here: https://www.ovhcloud.com/fr/public-cloud/cold-archive/
The pricing page here: https://www.ovhcloud.com/fr/public-cloud/prices/ (1,3€/TB-month)
And discover the manager (service dashboard) to follow the bucket status and lifecycle
The beta is free, have fun testing the service. All your feedback are welcomed!

**Comment by paschembri** [comment]
Thank you for this excellent news. @Izaia64 do you know if content archived during the beta will be available when the production phase starts ?

Or do we have to plan to backup a second time only when production phase starts ?

**Comment by Izaia64** [comment]
We don't have any SLA during beta test. However we don't plan to delete the data from beta test to prod. We will inform the beta tester that starting the GA date the service will be charged.

**Comment by Izaia64** [comment]
For the launch of the Cold Archive beta, we designed and optimized an infrastructure dedicated to the use case of the archive based on 4 datacentres in France, optimized to seek low cost (€1.3/TB-m) and a very high level of resilience
An S3 endpoint: rbx-archive. We have not planned the opening of this infrastructure the others regions (North America or Pacific Asia) in a short term

**Comment by sepplK** [comment]
We are getting an Internal Server Error during the restore process. 
Where can we report the issues with the affected account and bucket ids ?

**Comment by agoude** [comment]
Cold Archive will be soon offered as an object storage tier (object-level granularity). This will allow direct compatibility with lifecycle management feature.
to track the update, follow this issue #947
