### ISSUE TITLE
MongoDB Advanced Roles

### ISSUE THREAD

**Issue by baaastijn** [ovh/public-cloud-roadmap#113]
## User Story ##

As a customer
I want to grant specific permission per database for my users
So that
I can control databases access and CRUD with more granularity

## Acceptance criterias ##

- Can be done via UI
- Can not be done via Mongo shell
- Can be done when creating users or when editing a user
- Ability to select : Admin, read+write on any database, read any database, specific privileges (xxxx@database1, ...)

## Vote and Feedback ##
Ask us anything here in the comments below, and  vote with emojis !
👍 to vote for this issue

## Discuss on Discord ## 
Feel free to discuss with us on https://discord.com/invite/PwPqWUpN8G

**Comment by thild42** [comment]
Just review the scope to focus on the UI as the feature is already available supported through the API and by the Terraform OVH Provider.

**Comment by thild42** [comment]
This feature was released earlier today (15/03/2023) on the OVHcloud Control Panel.
