### ISSUE TITLE
Managed PostgreSQL instances - BETA

### ISSUE THREAD

**Issue by baaastijn** [ovh/public-cloud-roadmap#120]
THIS ISSUE IS FOR THE BETA PHASE ONLY
For General Availability, please refer to : #124 

**User story**

As a customer,

I want to test and deploy managed PostgreSQL instances in OVH Public Cloud easily
So that I'm sure this service will fit my needs, I will gain time, and focus on my own job.

**Acceptance criterias :**

    I can launch new PostgreSQL instances via control panel / API
    Basic management via control panel / API (manage users, manage databases, manage ACL)
    Daily backups made by OVHcloud
    Pay as you go
    Private or Public network
    High-Availability

**BETA phase limitations**

    Free during the whole beta phase
    Not ready for production.
    No SLA will be provided
    No official support from OVHcloud. Best effort via Discord Channel : https://discord.com/invite/PwPqWUpN8G

**BETA vs GA features gap**

| Feature                                 | BETA                                        | GENERAL AVAILABILITY |
|-----------------------------------------|---------------------------------------------|----------------------|
| MySQL proposed versions                 | 8                              | TBD                  |
| Basic features (user mgmt, backup, ...) | X                                           |                      |
| Mono-AZ high-availability               | X                                           |                      |
| Service plan upgrade                    | X                                           |                      |
| PostgreSQL version upgrade              | X                                           |                      |
| Database instance Fork                  | X                                           |                      |
| Public Network                          | X                                           |                      |
| Private Network (vRack)                 | X but during the beta, not at the beginning |                      |
| Custom Connection limit                 | No, will be limited to 200                  | X                    |
| Read replicas                           |                                             | X                    |
| Multi-AZ deployments                    |                                             | X                    |
| Custom maintenance window               |                                             | X                    |
| Ability to force updates manually       |                                             | X                    |
| Advanced configuration parameters       |                                             | X                    |

**Comment by matmicro** [comment]
Do you have an ETA for vRack availablility for the BETA ?

Will GRA location be available for BETA ?

Can you provide more details about what multiAZ means ?
Does it means we can have replica in another region ?
Does it means we can have High Availability on 2 datacenters (like Live in GRA and standby in RBX) ?

**Comment by baaastijn** [comment]
> Do you have an ETA for vRack availablility for the BETA ?
> 
> Will GRA location be available for BETA ?
> 
> Can you provide more details about what multiAZ means ? Does it means we can have replica in another region ? Does it means we can have High Availability on 2 datacenters (like Live in GRA and standby in RBX) ?

ETA for vRAck : no ETA so far, but the beta should last 3 months. it will be during this lap of time.
GRA for BETA : yes, planned
Mono-AZ : all nodes are in the same physical availability zone
Multi-AZ : nodes are distributed at least in 2 availability zones. Yes in mean that you can have replicas in other regions. 

an AZ is something autonomous from a network, electric and technical stack perspective. 
Multi-AZ can be done when locations are closed enough to meet network requirement (low latency mainly).

In our case we target RBX/GRA but also FR/DE, FR/UK, DE/PL, etc. 
but so far it's now planned.

**Comment by matmicro** [comment]
For the BETA it is mentionned limitation to 200 connections. 
Is it 200 connecter per node ? Or for the whole cluster ?
What is the limitation for GA ?

On OVH website, it mentionned possibility to have up to 5000 connections with pooling.
Is that pooling included by default for all flavors ?
Is it for GA only or also testable from beta ?

**Comment by baaastijn** [comment]
Hello,
It's 200 connections for 4GB ram , for the whole cluster. Max 1000. Same
for GA.
https://docs.ovh.com/gb/en/publiccloud/databases/postgresql/capabilities/#maximum-simultaneous-connections

Connection pools will be included in the price and available very soon !

**Comment by matmicro** [comment]
Great, thanks for details about max number of connections.

Any news about vRack availability ? (it was mentionned to be available end of december)
Can you have more precise date when pooling available ?

Many thanks
