### ISSUE TITLE
Managed Redis instances - BETA

### ISSUE THREAD

**Issue by baaastijn** [ovh/public-cloud-roadmap#121]
THIS ISSUE IS FOR THE BETA PHASE ONLY
For General Availability, please refer to : (to be added)

**User story**

As a customer,

I want to test and deploy managed Redis instances (Community version) in OVH Public Cloud easily
So that I'm sure this service will fit my needs, I will gain time, and focus on my own job.

**Acceptance criterias :**

    I can launch new Redis instances via control panel / API
    Basic management via control panel / API (manage users, manage databases, manage ACL, logs, metrics, ...)
    Daily backups made by OVHcloud
    Pay as you go
    Private or Public network
    Fast performances

**BETA phase limitations**

    Free during the whole beta phase
    Not ready for production.
    No SLA will be provided
    No official support from OVHcloud. Best effort via Discord Channel : https://discord.com/invite/PwPqWUpN8G

**BETA vs GA features gap**

| Feature                                      | BETA                                        | GENERAL AVAILABILITY |
|----------------------------------------------|---------------------------------------------|----------------------|
| Redis proposed versions                      | 6.2                                         | TBD                  |
| Basic features (user mgmt, backup, ACL, ...) | X                                           |                      |
| Mono-AZ high-availability                    | X                                           |                      |
| Service plan upgrade                         | X                                           |                      |
| Redis version upgrade                        | X                                           |                      |
| Database instance Fork                       | X                                           |                      |
| Public Network                               | X                                           |                      |
| Private Network (vRack)                      | X but during the beta, not at the beginning |                      |
| Multi-AZ deployments                         |                                             | X                    |
| Custom maintenance window                    |                                             | X                    |
| Ability to force updates manually            |                                             | X                    |
| Custom Redis Data eviction policy            |                                             | X                    |
| Advanced configuration parameters            |                                             | X                    |

**Comment by baaastijn** [comment]
Hello, Public Beta is now live in Public Cloud control panel !

feel free to share your feedback here or on https://discord.com/invite/h5USbCaH66

**Comment by matmicro** [comment]
Hi, 
Do you have any ETA when private network (vRack) will be available in the BETA ?
Thanks
