### ISSUE TITLE
Managed PostgreSQL instances - General Availability

### ISSUE THREAD

**Issue by baaastijn** [ovh/public-cloud-roadmap#124]
THIS ISSUE IS FOR THE GENERAL AVAILABILITY PHASE ONLY
For Beta please refer to : #120 

## User story ##

As a customer,
I want to deploy managed PostgreSQL instances in OVH Public Cloud easily
So that I will gain time, and focus on my own job.

## Acceptance criterias :##

- I can launch new postgreSQL instances via control panel / API
- Full management via control panel / API (manage users, manage databases, manage ACL, ...)
- Daily backups made by OVHcloud
- Pay as you go per hour
- Private or Public network
- High-Availability  mono-AZ
- Official support and sustainable service (ready for production)

**Improvement compared to beta**

- More documentation/tutorials
- Ready for production.
- SLA will be provided
- Official support from OVHcloud.
- Ability to add read replicas
- Advanced parameters configuration
- Ability to modify the max connections

**GA phase limitations**

- Some existing OVHcloud datacenters may not be available.

## Vote and Feedback ##
Ask us anything here in the comments below, and  vote with emojis !
👍 to vote for this issue

## Discuss on Discord ## 
Feel free to discuss with us on https://discord.com/invite/PwPqWUpN8G

**Comment by matmicro** [comment]
Can we have an idea about prices ?

**Comment by ZuSe** [comment]
Is there any plan to allow to set PRIVILEGES such as CREATE DB for users?
We are required to have this as we create temporary dbs for unit and integration tests during deployment. 

As far as I remember other DBaaS offerings are capable of it.

**Comment by matmicro** [comment]
What is the ETA for GA ?

**Comment by baaastijn** [comment]
We target beginning of February.

**Comment by ZuSe** [comment]
Will it be possible to keep the beta instances or are they going to be erased?

**Comment by baaastijn** [comment]
You will be able to keep the instances

**Comment by ZuSe** [comment]
Will it be possible to upload backups taken by one instance to another?
Right now the auto-backups can only be recovered within the same data center.
I don't know if you take them with pg_dumpall in the background, but for large appliances it would be kinda required for migration.

**Comment by baaastijn** [comment]
Hello Patrick,
In thé Backups tab you Cmcan either:
1/ restore backup in place. So you overwrite current data
2 duplicate backup, creating a new service in aother location. You will
have 2 services up and ready

Tell me if something is missing !

**Comment by ZuSe** [comment]
Yes on fork the location selection is disabled. Only the current data center is preselected

**Comment by matmicro** [comment]
GA has been officially announced for Feb.
What about private network and Pgbouncer ? Is it included in the GA release announce for Feb ?

**Comment by baaastijn** [comment]
> GA has been officially announced for Feb. What about private network and Pgbouncer ? Is it included in the GA release announce for Feb ?

hello !
All new features will be included in current pricing, including private network and connections pools

About the schedule : connections pools, query statistics and live queries will be there for the GA, enf of january
Private netowrk : we are still in progress, it's planned for this quarter but i don't have an exact date.

Have a good day

**Comment by ZuSe** [comment]
@baaastijn  

One question, because we just run into it.
Will you support autoscaling of the volume? Compose is doing that and I really love it.
https://www.ibm.com/cloud/blog/announcements/ibm-cloud-databases-portfolio-introduces-autoscaling

Definitely lets me sleep better at night knowing that the DB scales with the utilization.
We just had the case that we got broadcasted on TV (without a warning) and many many users signed up, putting a lot of data into the system. You can guess the end of the story :P

**Comment by baaastijn** [comment]
Hello Patrick,

I will add it in the backlog but not planned even if I fully understand the
needs :)
Autoscaling means complain underlying storage and so far it's not so easy.

The first step will be to allow metrics and logs export in third party
tools (grafana, Datadog, new relic,..) then you can put alerts and scripts
API actions such as cluster upsize.

But thx for the feedback !

**Comment by baaastijn** [comment]
Hello, PostgreSQL offers are now in General Availability !
- Official support
- Contractual SLA
- Mature enough for production
- Billed (prices on ovhcloud.com / public cloud / prices)

Have a good day

**Comment by grebois** [comment]
@baaastijn is it already available in terraform? I cannot seam to find that in the documentation. Thanks!

**Comment by matmicro** [comment]
From OVH UI Metrics tab on Manage Database Postgres:

It would be great if we can have a graph with current opened sessions count.
Same graph with PGBouncer (pools) opened connection count.
