### ISSUE TITLE
Managed Redis instances - General Availability

### ISSUE THREAD

**Issue by baaastijn** [ovh/public-cloud-roadmap#125]
THIS ISSUE IS FOR THE GENERAL AVAILABILITY PHASE ONLY
For Beta please refer to : #121 

## User story ##

As a customer,
I want to deploy managed Redis instances in OVH Public Cloud easily
So that I will gain time, and focus on my own job.

## Acceptance criterias :##

- I can launch new Redis Community instances via control panel / API
- Full management via control panel / API (manage users, manage databases, manage ACL, ...)
- Daily backups made by OVHcloud
- Pay as you go per hour
- Private or Public network
- High-Availability  mono-AZ
- Official support and sustainable service (ready for production)

**Improvement compared to beta**

- More documentation/tutorials
- Ready for production.
- SLA will be provided
- Official support from OVHcloud.
- Ability to customize data eviction policy
- Advanced parameters configuration

**GA phase limitations**

- Some existing OVHcloud datacenters may not be available.

## Vote and Feedback ##
Ask us anything here in the comments below, and  vote with emojis !
👍 to vote for this issue

## Discuss on Discord ## 
Feel free to discuss with us on https://discord.com/invite/PwPqWUpN8G

**Comment by matmicro** [comment]
Hi,
Can we know what would be prices of all offers ?
Thanks

**Comment by matmicro** [comment]
What is the ETA for GA ?

**Comment by baaastijn** [comment]
We target beginning of February.

**Comment by ZuSe** [comment]
@baaastijn  Not sure where to post it, but it might be for your interested.
Our Redis-Instance went down over the weekend (26c8c90940f042e38c98b9350aa10468/storages/databases/2b46609e-1014-4559-b8cc-a38145c07b5f/)

After the restart it seems that the credentials got invalidated/changed:
`redis.exceptions.ResponseError: WRONGPASS invalid username-password pair or user is disabled.`

Maybe you want to take a look on that to prevent such behavior in the GA version.

**Comment by baaastijn** [comment]
> @baaastijn Not sure where to post it, but it might be for your interested. Our Redis-Instance went down over the weekend (26c8c90940f042e38c98b9350aa10468/storages/databases/2b46609e-1014-4559-b8cc-a38145c07b5f/)
> 
> After the restart it seems that the credentials got invalidated/changed: `redis.exceptions.ResponseError: WRONGPASS invalid username-password pair or user is disabled.`
> 
> Maybe you want to take a look on that to prevent such behavior in the GA version.

many thanks will are investigating
during the Beta, Discord Channel is the way : https://discord.com/invite/PwPqWUpN8G
After, it will be via support

**Comment by baaastijn** [comment]
Hello, Redis offers are now in General Availability !
- Official support
- Contractual SLA
- Mature enough for production
- Billed (prices on ovhcloud.com / public cloud / prices)

Have a good day

**Comment by baaastijn** [comment]
For information, some commands are forbidden (we will add it to official documentation) : 

```
bgrewriteaof
cluster
command
debug
failover
migrate
role
slaveof
script
eval
evalsha
acl
bgsave
config
replicaof
lastsave
save
shutdown
monitor
```

**Comment by PrinceNickBALLO** [comment]
Hello .

**Comment by thild42** [comment]
Hello @PrinceNickBALLO, it is indeed currently not possible.
We will make it quickly available through the advanced configuration.
Thank you for your feedback.
