### ISSUE TITLE
Crossplane provider

### ISSUE THREAD

**Issue by loeken** [ovh/public-cloud-roadmap#134]
As a DevOps managing our infrastructure I would like to see support for crossplane at ovh to allow my developers an easy way of managing their infrastructure

General info on crossplane&developers being in charge of their infrastructure https://youtu.be/gxx8EM08ihs

Most players in the cloud biz seem to support it https://github.com/crossplane-contrib

**Comment by sennerholm** [comment]
https://marketplace.upbound.io/providers/edixos/provider-ovh/v0.36.1 seems to exists now

**Comment by loeken** [comment]
thanks i guess my issue is solved then
