### ISSUE TITLE
Managed OpenSearch instances - BETA

### ISSUE THREAD

**Issue by baaastijn** [ovh/public-cloud-roadmap#135]
THIS ISSUE IS FOR THE BETA PHASE ONLY
For General Availability, please refer to : (to be added)

**User story**

As a customer,

I want to test and deploy managed OpenSearch instances (open-source fork of ElasticSearch) in OVH Public Cloud easily
So that I'm sure this service will fit my needs, I will gain time, and focus on my own job.

**Acceptance criterias :**

    I can launch new OpenSearch instances via control panel / API
    Basic management via control panel / API (manage users, manage ACL, logs, metrics, ...)
    Daily backups made by OVHcloud
    Pay as you go
    Private or Public network
    Fast performances

**BETA phase limitations**

    Free during the whole beta phase
    Not ready for production.
    No SLA will be provided
    No official support from OVHcloud. Best effort via Discord Channel : https://discord.com/invite/PwPqWUpN8G

**BETA vs GA features gap**

| Feature                                      | BETA                                        | GENERAL AVAILABILITY |
|----------------------------------------------|---------------------------------------------|----------------------|
| OpenSearch proposed versions                      | 1.1                                         | TBD                  |
| Basic features (user mgmt, backup, ACL, ...) | X                                           |                      |
| Mono-AZ high-availability                    | X                                           |                      |
| Service plan upgrade                         | X                                           |                      |
| OpenSearch version upgrade                        | X                                           |                      |
| Database instance Fork                       | X                                           |                      |
| Public Network                               | X                                           |                      |
| Private Network (vRack)                      | X but during the beta, not at the beginning |                      |
| Multi-AZ deployments                         |                                             | TBD                    |
| Custom maintenance window                    |                                             | TBD                    |
| Ability to force updates manually            |                                             | TBD                    |

**Comment by ZuSe** [comment]
Is there any ETA for it?

**Comment by baaastijn** [comment]
> Is there any ETA for it?

it's live since... TODAY 👍 !

Enjoy, it's free in our control panel

**Comment by ZuSe** [comment]
@baaastijn 

As the GA ticket is still missing. I would like to ask here if it would be possible to install additional plugins to the instance such as ingest-attachment for example or if it ships with the most common ones likes on AWS (https://docs.aws.amazon.com/opensearch-service/latest/developerguide/supported-plugins.html)
