### ISSUE TITLE
ISO 27001 compliance

### ISSUE THREAD

**Issue by mhurtrel** [ovh/public-cloud-roadmap#14]
As a OVHcloud public cloud user
I want all my services (MKS, MPR and all IaaS it orchestrates) to be ISO 27001 certified
so that I can communicate on this to my end users to confirm the high level of secrity of the cloud service I host my apps on.

Note :
We currently target a public-cloud-wide certification

**Comment by Grounz** [comment]
Hello,

What's the status of  ISO 27001 compliance for public cloud ?

**Comment by mhurtrel** [comment]
ISO 27001 / ISO 27701 / ISO 27017 / ISO 27018  are now reached for Public Cloud : Compute, Storage (Block, Object, Archive, Snapshot, Instance Backup) Kubernetes, Logs Data Platform, Cloud Databases, Data processing, ML Serving / AI Training. (both for current and future public cloud projects/deployments)

More details can be found here https://www.ovhcloud.com/fr/enterprise/certification-conformity/ and official corporate communication will be done late this month !

**Comment by baaastijn** [comment]
More information : 
**French** : https://www.ovh.com/fr/news/presse/cpl1780.securite-protection-donnees-ovhcloud-etend-certifications-iso-27001-iso-27701-lensemble-ses
**English** : https://www.ovh.com/world/news/press/cpl1778.security-and-data-protection-ovhcloud-expands-iso-27001-and-iso-27701-certifications-all-its-cloud
