### ISSUE TITLE
Get alerts when my cluster is reaching disk space limits

### ISSUE THREAD

**Issue by baaastijn** [ovh/public-cloud-roadmap#141]
## User Story ##
As a customer
I want to receive alerts when my cluster disk spzce is reaching its limits
So that
I can react accordingly

## Acceptance Criterias ##
- alert by email when reaching 80% disk space usage
- alert by email when reaching 85% disk space usage
- Cluster in Read-Only when reaching 95% disk space usage
- Ability for the customer to delete data
- End of read only when cluster <80% disk space usage

Not in the scope for this first iteration :

Ability for the customer to upsize to a higher range (with more storage)

## Vote and Feedback ##
Ask us anything here in the comments below, and  vote with emojis !
👍 to vote for this issue

## Discuss on Discord ## 
Feel free to discuss with us on https://discord.com/invite/PwPqWUpN8G

**Comment by thild42** [comment]
Closing this issue as it is released. Note that the ability for the customer to delete data is available through the API only. The support of this feature through the manager will arrive in a second time.
