### ISSUE TITLE
Flexible storage sizing for database

### ISSUE THREAD

**Issue by baaastijn** [ovh/public-cloud-roadmap#143]
## User Story ##
As a customer
I want to customize the size of the storage during my database instance creation
So that
I get products that fits my needs exactly

## Acceptance criterias ##
- Storage size could be selected during cluster creation.
- Storage size could be upgraded after cluster creation.
- Same storage space for all nodes.
- Minimum default storage for the cluster will depend of the node sizing, same values as of today.
- Maximum extra storage space equal to two time the base storage. For example Db1-4 have 80 Gb of base storage and will have 160 Gb of additional storage available for a possible total of 240 Gb. The hard limit is 4 Tb total storage.
- Available for the following engines: MongoDB, Apache Kafka, PostgreSQL, MySQL, OpenSearch, Apache Cassandra, M3DB.
- Accepted limitation: unable to decrease the amount of storage.
- Accepted limitation: performances may not be as good as local SSD storage IOPS-wise.
- Accepted limitation: unavailable on local SSD storage.

## Vote and Feedback ##
Ask us anything here in the comments below, and  vote with emojis !
👍 to vote for this issue

## Discuss on Discord ## 
Feel free to discuss with us on https://discord.com/invite/PwPqWUpN8G

**Comment by baaastijn** [comment]
hello, for info we prioritized this feature for the next release.

**Comment by thild42** [comment]
Good news! The feature is being developed.
I update the scope of the feature with new elements: storage upgrade after creation, available engines, storage capacity, etc.

**Comment by notz** [comment]
I hoped for smaller base sizes to have a much more flexible setup as other providers currently offer and alongside with that a much more competitive pricing.

**Comment by thild42** [comment]
@notz - the targetted limitation for the initial scope of the feature will be set to 3 times the base storage (see the above example). Future steps may be taken to further expand this limitation to 5 times the base storage.

Have you actual figure that you are willing to share regarding what you expect ?

**Comment by notz** [comment]
@thild42 smaller sizes :) Scaleway starts from 5 GB. For many of our databases 5-10GB would be enough (mostly admin tools - i.e.: translation tool, wiki, ...)

**Comment by thild42** [comment]
Thank you for your reply @notz.

The small databases offer you seek could be only be found in our [Cloud Database portfolio](https://www.ovh.com/fr/cloud-databases/) which is different than the [Managed Database portfolio](https://www.ovhcloud.com/en/public-cloud/databases/).

The smallest database flavour available in the Managed Database universe is the Db1-2 with 25 Gb storage that is only available for MongoDB. Extending the Db1-2 offer to other engines and/or proposing even smaller database offers is not yet planned, and won't likely be planned in the foreseeable future.

Hope that helps.

**Comment by notz** [comment]
@thild42 I know about the offer, but that is no option, because their is no private connection with vrack and currently no availability in the german data center. I'm fine with Db1-4 but we don't need the 80GB, which is waste of resources.

**Comment by thild42** [comment]
Release yesterday afternoon.

**Comment by baaastijn** [comment]
Hello ! good news, now you can add additional storage during databases instances creation !
You will have a sizer shown inside the control panel, with pricing estimation (per hour and per month)

Website will be updated soon

**Comment by guillaume1987** [comment]
nn
