### ISSUE TITLE
PostgreSQL connection pools

### ISSUE THREAD

**Issue by baaastijn** [ovh/public-cloud-roadmap#146]
## User Story ##
As a customer
I want Connection Pools feature for my PostgreSQL instances
so that
I will gain in performances with my use cases requiring a lot of simultaneous connections

## Acceptance Criterias ##
- based on PGBouncer
- Ability to manage connection pools via UI or API
- Ability to specify a pool name, a database, a user, a pooling method, and maximum allowed connections

## Vote and Feedback ##
Ask us anything here in the comments below, and  vote with emojis !
👍 to vote for this issue

## Discuss on Discord ## 
Feel free to discuss with us on https://discord.com/invite/PwPqWUpN8G

**Comment by baaastijn** [comment]
Hello, PostgreSQL connection pools are now available !
Have a good day

**Comment by matmicro** [comment]
Great news ! thx

The field "Size" on the UI, does it means the maximum allowed client connections ? (for that pool).
Or does it mean max DB connection ? 
Or does it means something else ?

We can create several pools, does it means each pool is a pgboucner ?

**Comment by baaastijn** [comment]
> Great news ! thx
> 
> The field "Size" on the UI, does it means the maximum allowed client connections ? (for that pool). Or does it mean max DB connection ? Or does it means something else ?
> 
> We can create several pools, does it means each pool is a pgboucner ?

hello,

Size = How many PostgreSQL server connections can this pool use at a time.
maximum size is 5000 db client connection per pool

As far as I know, each pool is a pgbouncer

**Comment by matmicro** [comment]
As a pgbouncer user i would like to be able to specify "*" (any) database connection on my pool.

So i need to connect to a pool (on port 20185) without specifying the database name.
this is something possible with pgbouncer with such syntax :
```; fallback connect string
* = host=postgresql-132456789.database.cloud.ovh.net port=20184
```

I would like to be able to do such configuration on my Managed Postgres Database from OVH UI Manager.

**Comment by thild42** [comment]
Hey @matmicro, just to let you know that I have brought to the attention of our partner both of your request.
The first one regarding the "*" database name fallback rule for connection pools.
The second one regarding the connection metric to be split by connection pools.
I'll let you know when I have an answer for each of these topics.
