### ISSUE TITLE
Private network (vRack) for all DBMS

### ISSUE THREAD

**Issue by baaastijn** [ovh/public-cloud-roadmap#147]
** this feature is already available for MongoDB**

## User Story ##
As a customer
I want to be able to select Public or Private network (vRack) during database instance creation
So that
I can connect to my instance with using the public network

## Acceptance criterias ##
- Ability to select public or private network during instance creation
- Ability to connect via private network (vRack) like any other OVhcloud compliant product
- (already the case) Works for MongoDB
- Works for Kafka, MySQL, OpenSearch, PostgreSQL, Redis

## Vote and Feedback ##
Ask us anything here in the comments below, and  vote with emojis !
👍 to vote for this issue

## Discuss on Discord ## 
Feel free to discuss with us on https://discord.com/invite/PwPqWUpN8G

**Comment by matmicro** [comment]
Is it possible to have news on this ?
Any precise ETA to provide ? (For Redis and postgresql)
Thanks

**Comment by baaastijn** [comment]
For information, Private networt technical implementations is successfully done for all DBMS except Kafka MirrorMaker 2.
We polish the end user guide, then we will unblock this feature for everyone.
It will be then possible to create new DB with public OR private network. You cannot activate vRack on existing clusters.

**Comment by baaastijn** [comment]
Hello, this feature is available for everyone and for all the DBMS ! 
Technical documentation is still on his way

have a good day
