### ISSUE TITLE
[FR] Windows Server 2022

### ISSUE THREAD

**Issue by ZuSe** [ovh/public-cloud-roadmap#164]
Windows Server 2022 has been release in August this year:

https://cloudblogs.microsoft.com/windowsserver/2021/09/01/windows-server-2022-now-generally-available-delivers-innovation-in-security-hybrid-and-containers/

It comes with a bunch of nice features to operate it as part of a cloud environment (even outside of Azure).
Right now the latest available version on OVH PC/OpenStack is Windows Server 2019.

I kindly ask to provide support for Version 2022.

**Comment by W3LLD0NE** [comment]
yes, would be really perfect.

**Comment by JacquesMrz** [comment]
Hi all,

The job is being done on our side. I'll let you know as soon as we have a clear ETA on that.

**Comment by ZuSe** [comment]
Hi @JacquesMrz  any update on it?

**Comment by zulander1** [comment]
@W3LLD0NE any update?

**Comment by zulander1** [comment]
@JacquesMrz Any updates?

Thanks

**Comment by bronxzv** [comment]
FYI as a client of OVH with 3 dedicated servers, I have asked their sales team 2 times for the an expected availability date for Windows Server 2022 template: zero feedback

After opening a ticket for technical assistance the answer was that they don't have a planned date since this require testing, this looks weird to me since we are now one year after preview and competitors such as Leaseweb have Windows Server 2022 available (using one at the moment)

**Comment by andrewkm** [comment]
Any update on this @JacquesMrz ?

**Comment by bronxzv** [comment]
https://www.ovhcloud.com/en/bare-metal/os/server-windows/

"All of our dedicated servers can be used with the **latest Windows operating system versions**. This delivers the reliability of a popular OS, as well as a panel of **ready-to-use operating systems** for your business."

I'll suggest to, at least, remove this misleading text from their website.

**Comment by JacquesMrz** [comment]
Hi all,

Sorry for the delay guys, we're on it.
The package is currently being validated.
Best case it's available by the end of the day.
Else, will be available next week.

**Comment by bronxzv** [comment]
Great news Jaques!

I was sure that some sarcasm will help speed things up. 

I have a gRPC based project to enter production soon, Windows Server 2022 is mandatory to have it on IIS along with legacy ASP.net code all on port 443.

**Comment by JacquesMrz** [comment]
To all,

Windows Server 2022 is available in all Public Cloud Regions except US ones (will be deployed soon there).

**Comment by bronxzv** [comment]
Thank you very much Jacques, I will have a try ASAP with our backup server.

**Comment by r-work** [comment]
Option to install Windows Server 2022 is not showing, we have bare metal server with Windows Server 2019.

**Comment by W3LLD0NE** [comment]
> Option to install Windows Server 2022 is not showing, we have bare metal server with Windows Server 2019.

same. @JacquesMrz

**Comment by andrewkm** [comment]
@JacquesMrz I too cannot see the template.

I am using your Game 2 dedicated servers and correctly have added a license for this version of windows.

**Comment by TB-G** [comment]
Same issue, only 2019

**Comment by bronxzv** [comment]
Guys this topic is closed and apparently Jacques missed the fact that some(most ?) people here were talking about dedicated servers (beyond the OP request). 

Anyway, I have asked again the technical team for an availability date and the answer is still the same: no ETA to be provided for a Windows Server 2022 template but you can install your own image **at your own risk** which I found very unprofessional for a major player like OVH.

**Comment by andrewkm** [comment]
Well that's ghetto, someone should make a new issue linking this one stating we want this for dedicated servers.

**Comment by bronxzv** [comment]
FWIW I have opened a topic here https://community.ovh.com/t/template-windows-server-2022/53482 (in French) since I have not seen a proper sub-forum on github/ovh (maybe I missed one though)

**Comment by bronxzv** [comment]
Thank you Jacques for the feedback,

I have added a comment here https://github.com/ovh/infrastructure-roadmap/issues/37  hoping to get, at last, some clear feedback about the ETA
