### ISSUE TITLE
kubernetes : nodepool : missing `nodepool` label on deleted node

### ISSUE THREAD

**Issue by briceruzand** [ovh/public-cloud-roadmap#165]
One of my node (that was just scaled up) cannot communicate with other node (error in pod no such service named ...), never-mind.

I decide to drain the node and then delete the node :

`kubect delete node mypool-node-xxxx`

A few seconds later the node came back as expected, and network is working, greats !!!
But the label of node pool `nodepool=mypool` was missing on the node.

I can patch it easily but it should be done automatically.

Thx

**Comment by mhurtrel** [comment]
Hi @briceruzand  I confirm this will be fixed with the following feature : https://github.com/ovh/public-cloud-roadmap/issues/87 to be prodded in a few weeks (you will be able to manipûlate nodepoolds labels and taints, that will be spread on all nodes of the pool)
