### ISSUE TITLE
Private Network (vRack) - Security group support

### ISSUE THREAD

**Issue by ncfrak** [ovh/public-cloud-roadmap#168]
Hello,

I read that the security group support for private network should be available late 2021.

Do you have a release date?

Indeed, as a public cloud user (using Terraform) I want to secure the traffic between my instances.

What alternatives are there available?

**Comment by JacquesMrz** [comment]
Hi @ncfrak ,

The support of Security Groups for private network is linked to the upgrade of our OpenStack Regions from Newton to Stein. This feature is available in all our public cloud regions running on Stein.
As of today, only GRA9 and SBG7 are running on Stein.
We currently work on the update of all our existing Public Cloud regions to Stein. Our target is to get the upgrade done everywhere by august 2022 (more precise planning to be communicated ASAP).

We recommend to not activate the Security Groups in your private network as soon as your Public Cloud resources are distributed on Public Cloud Regions running on Newton (behavior will not be homogeneous).

If your Public Cloud resources are strictly in regions running on Stein, you can activate Security Groups when creating the network using:
`openstack network create networkName --enable-port-security`

**Comment by ncfrak** [comment]
Hello @JacquesMrz 

Thanks for your answer. Great to see the progress.

Stein regions are still flagged "beta" here https://www.ovhcloud.com/fr/public-cloud/regions-availability/, but as I understand your message, we could use it right away?

My use case is to only use 1 region with Stein (GRA9 most probably), so there won't be issues with Security Groups on Newton vs Stein regions.

**Comment by JacquesMrz** [comment]
You are right, the following services are available in their BETA version in GRA9: 
- Baremetal aaS
- Floating IPs
- Virtual Router
- Public Cloud Load Balancer
- AI Notebooks

Nevertheless, all the other services available in GRA9 are available in their GA version (including Private Network).

**Comment by Yayg** [comment]
Hi,

Is there a release date announced for this feature? This would greatly help on security designs.

Thanks by advance.

**Comment by yomovh** [comment]
Hello @Yayg 

Security groups are available and supported but not integrated in our Control Plane : you have to use via Horizon (Openstack GUI Control Plane, Openstack CLI or terraform)

You can find more information on our documentation : 
 * [Access and security settings in Horizon](https://help.ovhcloud.com/csm/en-gb-public-cloud-compute-horizon-access-security?id=kb_article_view&sysparm_article=KB0050413)
 * [Managing firewall rules and port security on networks using OpenStack CLI](https://help.ovhcloud.com/csm/en-gb-public-cloud-compute-firewall-security?id=kb_article_view&sysparm_article=KB0051160)
 * [Creating and configuring a security group in Horizon](https://help.ovhcloud.com/csm/en-gb-public-cloud-compute-horizon-configure-security-group?id=kb_article_view&sysparm_article=KB0051197)

Hence I propose to close this issue and to open a new one for the security group integration into the OVHcloud Control Plane (also known as Manager)
