### ISSUE TITLE
Object Storage - Server-side Encryption

### ISSUE THREAD

**Issue by Izaia64** [ovh/public-cloud-roadmap#176]
As a customer I want OVHcloud to encrypt my object storage (server side) with my key before storing the datas on the drives

Feature : 

- Customer-Provided Encryption Keys
- API : https://docs.aws.amazon.com/fr_fr/AmazonS3/latest/userguide/ServerSideEncryptionCustomerKeys.html

**Comment by tanandy** [comment]
Is there any ETA on this topic ? thank you

**Comment by Izaia64** [comment]
hi, i don't have yet the ETA, it will be known soon and i will write the ETA here as soon as we get it (in Feb)

**Comment by Izaia64** [comment]
Available now ! On Object Storage High performance and next class of storage to be launched soon (Object Storage Standard Performance and Cold Archive)

**Comment by tanandy** [comment]
Huge news !! thank you . Any ETA for the Storage standard & Cold Archive ?

**Comment by Izaia64** [comment]
Standard object storage will be in beta test very soon, GA in June. Cold Archive is already testable (lab page for suscription) in alpha test, GA Septembre. Refer to to the 2 tickets for more update

**Comment by JacquesMrz** [comment]
For Cold Archive, Lab page is here : https://labs.ovh.com/cold-archive

**Comment by JacquesMrz** [comment]
Server Side Encryption will be available with all OVHcloud S3 storage class in all locations.
Issue closed.

**Comment by tanandy** [comment]
Shouldnt we wait SSE is GA everywhere ?

**Comment by ThachNgocTran** [comment]
SSE-C seems to be supported by OVH. But I wonder if they also support other encryption schemes:

+ SSE-S3: the cloud vendor manages the encryption key; at least data-at-rest is encrypted.
+ SSE-KMS: the cloud vendor manages the encryption key, but the master key is managed by the user.

Could anybody give some hints on this matter? Thanks.

**Comment by ThachNgocTran** [comment]
@Izaia64 Thanks for the quick response.

As of 04.10.2022, OVH Object Storage supports the following types:

![image](https://user-images.githubusercontent.com/9520123/193840013-06fdba3d-e5a9-4192-a46a-4829366dc0e8.png)

I tested the "**Standard Object Storage - S3 API**", following the [guide](https://docs.ovh.com/de/storage/s3/encrypt-your-objects-with-sse-c/). Good news: it works as expected. (https://github.com/ovh/public-cloud-roadmap/issues/176#issuecomment-1266977860)

However, if accidentally choosing "**Standard Object Storage - Swift API**", executing the command below returns NO ERROR, NO INDICATION of encryption being used in Server Side. This is contrary to [expected output](https://docs.aws.amazon.com/cli/latest/reference/s3api/put-object.html#output) in case of AWS S3.

```
aws s3api put-object \
  --body /etc/magic \
  --bucket <bucket_name> \
  --key encrypt_magic \
  --sse-customer-algorithm AES256 \
  --sse-customer-key $encKey \
  --sse-customer-key-md5 $md5Key
```

Worse, one can even _manually_ download the file (`encrypt_magic`) via [web interface](https://www.ovh.com/manager/#/public-cloud/?onboarding) > Storage > Object Storage. Meaning: the file is not encrypted at rest, despite seeing no errors/warnings.

Potential problem: Users may assume the file is securely stored in the Cloud, but in fact, it is **not**. This is _misleading_. Sensitive data may be accidentally leaked.

**Comment by biapar** [comment]
The problem is still open. I just tried and if I open the file from the panel, I see the content.

**Comment by guldil** [comment]
Is "SSE-C" working with AWS PHP S3Client ?

I always get error :

```
<Error><Code>BadRequest</Code><Message>X-Amz-Server-Side-Encryption-Customer-Key  (truncated...)
 BadRequest (client): X-Amz-Server-Side-Encryption-Customer-Key header must be a base64 encoding of exactly 32 raw bytes - <?xml version='1.0' encoding='UTF-8'?>
<Error><Code>BadRequest</Code><Message>X-Amz-Server-Side-Encryption-Customer-Key header must be a base64 encoding of exactly 32 raw bytes</Message><RequestId>txc8af08bea5354a428312b-0065a94cfd</RequestId></Error>Please fix error with file upload before continuing.
```

i followed doc from here : https://help.ovhcloud.com/csm/fr-public-cloud-storage-s3-encrypt-objects-sse-c?id=kb_article_view&sysparm_article=KB0047318
 i test with aws cli it's working : 
 
```
 root@xxxxxxxxxxxxx:~# aws s3api put-object \
>   --body /etc/magic \
>   --bucket xxxxxxxxxxxxxx  \
>   --key encrypt_magic \
>   --sse-customer-algorithm AES256 \
>   --sse-customer-key $encKey \
>   --sse-customer-key-md5 $md5Key
{
    "ETag": "\"272913026300e7ae9b5e2d51f138e674\"",
    "VersionId": "1705594315.542242"
}
```
i just copy / paste encKey  and md5Key in my code then : 

```
        $file_name = "local-file-" . uniqid();
        try {
            $s3Client->putObject([
                'Bucket' => $bucket_name,
                'Key' => $file_name,
                'SourceFile' => $local_file,
                'SSECustomerAlgorithm' => 'AES256',
                'SSECustomerKey' => 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
                'SSECustomerKeyMD5' => 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
            ]);
            echo "Uploaded $file_name to $bucket_name.\n";
        } catch (\Exception $exception) {
            echo "Failed to upload $file_name with error: " . $exception->getMessage();
            exit("Please fix error with file upload before continuing.");
        }
```

**Comment by biapar** [comment]
I’ve a similar problem with C# and S3 AWS SDK.
I’m able to encrypt, but I’ve error when I download it

Il giorno 18 gen 2024, alle ore 17:17, guldil ***@***.***> ha scritto:



Is "SSE-C" working with AWS PHP S3Client ?

I always get error :

<Error><Code>BadRequest</Code><Message>X-Amz-Server-Side-Encryption-Customer-Key  (truncated...)
 BadRequest (client): X-Amz-Server-Side-Encryption-Customer-Key header must be a base64 encoding of exactly 32 raw bytes - <?xml version='1.0' encoding='UTF-8'?>
<Error><Code>BadRequest</Code><Message>X-Amz-Server-Side-Encryption-Customer-Key header must be a base64 encoding of exactly 32 raw bytes</Message><RequestId>txc8af08bea5354a428312b-0065a94cfd</RequestId></Error>Please fix error with file upload before continuing.


i followed doc from here : https://help.ovhcloud.com/csm/fr-public-cloud-storage-s3-encrypt-objects-sse-c?id=kb_article_view&sysparm_article=KB0047318
i test with aws cli it's working :

 ***@***.***:~# aws s3api put-object \
>   --body /etc/magic \
>   --bucket xxxxxxxxxxxxxx  \
>   --key encrypt_magic \
>   --sse-customer-algorithm AES256 \
>   --sse-customer-key $encKey \
>   --sse-customer-key-md5 $md5Key
{
    "ETag": "\"272913026300e7ae9b5e2d51f138e674\"",
    "VersionId": "1705594315.542242"
}


i just copy / paste encKey and md5Key in my code then :

        $file_name = "local-file-" . uniqid();
        try {
            $s3Client->putObject([
                'Bucket' => $bucket_name,
                'Key' => $file_name,
                'SourceFile' => $local_file,
                'SSECustomerAlgorithm' => 'AES256',
                'SSECustomerKey' => 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
                'SSECustomerKeyMD5' => 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
            ]);
            echo "Uploaded $file_name to $bucket_name.\n";
        } catch (\Exception $exception) {
            echo "Failed to upload $file_name with error: " . $exception->getMessage();
            exit("Please fix error with file upload before continuing.");
        }
