### ISSUE TITLE
Ability to assign an IPFO to a MKS LoadBalancer

### ISSUE THREAD

**Issue by matmicro** [ovh/public-cloud-roadmap#178]
As a MKS user, i want to be able to assign my IPFO (IP Fail Over) to one of my MKS loadbalancer.
Thus i can migrate my services without downtime.

**Comment by antonin-a** [comment]
Hello @matmicro, may I ask from which service you plan to migrate? 
What you call "MKS LoadBalancer" are in fact OVH Public Cloud Loadbalancer based on Octavia. They are currently not supporting the usage of Addtional IP (Failover IP) but you can use Floating IP instead.

**Comment by antonin-a** [comment]
Ok clear, for this specific scenario I do confirm that it is not supported yet. We can suggest a new feature request on Loadbalancer side (@yomovh FYI). 

If your current IP is not hardcoded, another option is to move to Floating IP usage and proceed to a DNS switch.

**Comment by yomovh** [comment]
Thanks for your request. This is not something that we plan to do in the short term : Floating IPs are the way to go to have some flexibility for IP for Public Cloud.
