### ISSUE TITLE
[Public Cloud] Instances randomly freeze on boot when multiple instances are launched in the same time in a private network

### ISSUE THREAD

**Issue by deepbluemussel** [ovh/public-cloud-roadmap#183]
Hello,

Every time I want to launch several instances at the same time (let's say more than 2), some of them freeze during boot (often on/after "Mounted FUSE Control File System"). After 15 minutes the instance finally starts but I can't connect to it, moreover in the shell horizon console the name of the instance is the one of the image used (e.g. "Ubuntu 20.04") instead of the name given when the instance was created. Rebuild, Hard Reboot will do nothing.

After multiple tests, I noticed that this problem only happened when the instance was attached to a network other than the Ext-Net (the default one to access the Internet).
As soon as the instance is attached to another network, the problem occurs.

You can test this very easily, here is how I did it (on the GRA1 region):
1. Create a new network (on the ovh dahsboard or on the horizon, it doesn't matter)
2. Create 10 new machines at the same time (on ovh or horizon), attached to this network and with "Ubuntu 20.04" as image
3. Go and check the console for each of these machines, many of them will be stuck on the boot

It's a bug that is quite disabling in the usage of dynamic environments.

**Comment by adamo-ovh** [comment]
Hello,

Based on the information provided I would assume you do not have DHCP configured on your private network. This means the VM has no way to configure your network interface. Cloudinit will get stuck waiting for the interface to come up.

You need to enable DHCP on your subnet and then when your VM boots it will be able to configure its interface.

I tested this and it works fine.

Steps:
1. Get your private network ID: https://api.ovh.com/console/#/cloud/project/%7BserviceName%7D/network/private#GET
2. Get your subnets: https://api.ovh.com/console/#/cloud/project/%7BserviceName%7D/network/private#GET
3. Enable DHCP on your subnet: https://api.ovh.com/console/#/cloud/project/%7BserviceName%7D/network/private/%7BnetworkId%7D/subnet/%7BsubnetId%7D#PUT

Using DHCP and different subnets in regions is recommended for image to work out of the box.

**Comment by deepbluemussel** [comment]
Hi,

Thanks for your answer. These network do have DHCP enabled.
Actually I didn't have the issue for a few weeks now (nothing changed since).Let's hope that it's was a temporary issue so we can close this issue.

**Comment by adamo-ovh** [comment]
If it does happen, I would suggest to submit a ticket to support with all information like VM UUID, Network ID and we can dig more into it for you.
