### ISSUE TITLE
Terraform; build Vrack  with gateway IP

### ISSUE THREAD

**Issue by Grounz** [ovh/public-cloud-roadmap#185]
Hello,

For the moment it's no possible to set `gateway_ip` in terraform when we want build a private network with subnet.

Here, it"s this configuration that we want use: https://registry.terraform.io/providers/ovh/ovh/latest/docs/resources/cloud_project_network_private_subnet#gateway_ip
In OVH terraform this is only exported attributes and no argument 

In openstack documentation it's possible to set this option: https://registry.terraform.io/providers/ovh/ovh/latest/docs/resources/cloud_project_network_private_subnet#gateway_ip
gateway_io is an argument.

It's possible to do ?

**Comment by arcalys** [comment]
@Grounz 
In the meantime, it's possible through the OpenStack provider (using the gateway_ip parameter on openstack_networking_subnet_v2). We have private networks with the gateway_ip defined to a service IP shared between our output "gateways".
