### ISSUE TITLE
Smaller Worker Nodes (D2 instances)

### ISSUE THREAD

**Issue by mhurtrel** [ovh/public-cloud-roadmap#19]
As MKS user
I want to use smaller that current general purpose VMs
so that I can achieve better granulrity in cluster scaling, and have cheaper staging clusters.

Note :
Our test and market feedback show that the bin packing strategy of Kubernetes make it behave unstably with overcommited VMs.
We therefore initially made the service compatible only with guaranteed ressources flavor. We are working with our IaaS compute colleagues to work on a new generation of smaller/very affordable VMs to guarantee  a great stability/price ratio at a cheaper entry price.

**Comment by mhurtrel** [comment]
These new instances/worker nodes (codename D2) are planned to be released second part of March

**Comment by mhurtrel** [comment]
Since late this week, new "discovery" instances are available as standalone instances
They will progressively replace the "sandbox" ones. Though their ressources are not dedicated (contrary to all other families), you will see a strong performance improvement over sandbox ones .
The website will be update soon, and the instances will be progressively open in all regions.

We will enable D2-4 and D2-8 with kubernetes in the next 2 weeks
.![image](https://user-images.githubusercontent.com/24432524/111043692-22b71b00-8444-11eb-9805-4aceb531bae8.png)

**Comment by mhurtrel** [comment]
We have an additionnal delay on the feature, bringing d2 integration to June.
Sorry for the delay

**Comment by PhilippeVienne** [comment]
@mhurtrel will it also include D2-1 and D2-4, those are quite small nodes no?

**Comment by mhurtrel** [comment]
@PhilippeVienne  D2-4 yes will be included, but indeed, not D2-1.

**Comment by trashcluster** [comment]
13th June and still nothing. Can we expect the new instances before July ?

**Comment by trashcluster** [comment]
@mhurtrel We're soon closing on June and no news about the smaller nodes, have you given up on those ?

**Comment by mhurtrel** [comment]
@trashcluster  it now just a matter of days, all region should be activated next week. sorry for the delay.

**Comment by mhurtrel** [comment]
The D2-4 and D2-8 are now usable in Sydney, Singapore, east and west cost US datacenters, Strasbourg, Warsaw, Beauharnois and in some Gravelines zones . Remaining zones will be activated tommorow or later this week.

**Comment by mhurtrel** [comment]
The feature is now available from all datacenters !

**Comment by mhurtrel** [comment]
Hi @matmicro No, d2-2 compute power is too low to handle both the managed components workload and significant containerized workload.

**Comment by ZuSe** [comment]
Maybe you could introduce sth. like d2-16?
Especially for cloud build runners (e.g. GitLab) the extra RAM would be very beneficial.

**Comment by mhurtrel** [comment]
@ZuSe have you considered b2-15 ? With 15gb of ram, dedicated cpu cores and gbps connectivity, and not a lot more than 2 x d2-8 in terms of pricing

**Comment by ZuSe** [comment]
That's what we are using right now, but comparing it to other clouds it seems to be a kinda expensive kind of build-node.

**Comment by MJBGO** [comment]
Hi @mhurtrel ,

It seems it is no longer possible to add d2-4 and d2-8 flavors to k8s. Is it normal ?
I tried at GRA9 and SBG7.

![image](https://user-images.githubusercontent.com/8344487/160412058-566c9116-4029-471f-8d4f-e95741134842.png)

![image](https://user-images.githubusercontent.com/8344487/160412079-431698a1-6b07-407f-822a-a7f91994a71c.png)

Thanks

**Comment by mhurtrel** [comment]
Hello @MJBGO D2-4 anbd D2-8 are available in all regions, and I could not reprodiuce this behavior on my clusters in GRA9. Could you open a support ticket so that we investigate why it would not let you do it ?

**Comment by MJBGO** [comment]
Ok I opened a ticket, thanks :) (5266832)
