### ISSUE TITLE
AI Tools - Improve CLI installation

### ISSUE THREAD

**Issue by baaastijn** [ovh/public-cloud-roadmap#193]
## User Story ##
As a customer, 
I want a simple way to install the ovhai CLI in any platform (Windows, MacOs, Linux)
So that
I can save time to find the correct way to 

## Acceptance criterias ##
- the PATH is exported automatically (no need for an "export path..."
- No need to unzip the file
- can be installed with 1 line of curl like
```
curl https://cli.gra.training.ai.cloud.ovh.net/install.sh | sh
```
- You still can download the binary file if required
- The Public Documentation is up to date

## Vote and Feedback ##
Ask us anything here in the comments below, and  vote with emojis !
👍 to vote for this issue

## Discuss on Discord ## 
Feel free to discuss with us on https://discord.com/invite/PwPqWUpN8G

**Comment by baaastijn** [comment]
This issuie is resolved technically, we now need to update the documentation to close it

**Comment by mhrng** [comment]
Hi all!
The updated documentation is available here: https://docs.ovh.com/gb/en/publiccloud/ai/cli/install-client/ .
