### ISSUE TITLE
Managed Database scaling up/down

### ISSUE THREAD

**Issue by matmicro** [ovh/public-cloud-roadmap#195]
As a Managed Database user :

I would like to be able to scale down my cluster:
- move to below node flavor (like from DB1-120 to DB1-60)
- move to below offer (like from Enterprise to Business)
- remove extras nodes (if more than 2 or 3 nodes created)
   this require also to be able to ask for more extra nodes

**Comment by ZuSe** [comment]
We would be also interested in it.
And especially decoupling CPU/RAM and DISK SPACE would be really great.
According to our internal calculation the OVH offering is 50% more expensive than direct competitors, atm. 
Mostly because you pay for resources you don't need/utilize.

**Comment by baaastijn** [comment]
Hello, could you you share the hypothesis for benchmarking the competitors
? Usually we are less expensive when you count network traffic, backups
storage, IP, and perf (disk Iops)

**Comment by ZuSe** [comment]
Hi @baaastijn I am a little bit short on time.
But my guys told me that they compared it with Open Telekom Cloud and Ionos (not the US-providers), especially with focus on German data centers and ease of scale. 
Our setup is a 4 Core machine with 8GB memory and we do need at least 1+ TB space. 
Regarding the decoupling of space and node-size, we already talked, I think here OVH can't win the race atm.
So comparing both offers just with CPU and Memory (internal traffic is free on OTC):
OTC - 4 Cores, 16 GB RAM: 130.96 € / month (on longterm commitment) + RDS SSD Storage for 320GB: 32€ = 162€/month
OVH - 4 Cores, 15 GB RAM, ??, 320GB:  213,01 €/month

I didn't do a benchmark on how faster/slower the OTC storage is, yet, but I would say that's more your job than mine ;)

**Comment by thild42** [comment]
Node flavor downgrade is now possible through the API (see #387).
It will be supported through the control panel later this year.
As for the plan downgrade we also are working on it.
