### ISSUE TITLE
Self Managed Worker Nodes

### ISSUE THREAD

**Issue by mhurtrel** [ovh/public-cloud-roadmap#20]
As a Kubernetes service user
I want to orchestrate self-managed worker nodes
so that I can use any OVHcloud IaaS server (even GPU flavors, dedicated servers...) and configure the local system in specific ways.

**Comment by Parsonswy** [comment]
Hello @mhurtrel,
Are you able to provide any sort of timeline for this feature? I saw in #78, you mentioned your target was late 2021. Does this still seem achievable? Right now we are deploying our K8 services with OVH US if that changes anything.

We are very interested in this feature for constructing a hybrid cluster that utilizes OVH's competitive dedicated serer offerings for our base capacity that we expect to need 100% of the time, while still being able to scale quickly with cloud VMs should we need to. We're not necessary looking for fully automated autoscaling in a hybrid environment as that seems a bit more complex - just the ability to join our dedicated servers to a managed K8s cluster that also has cloud VM instances.

We're a young business and look forward to this as a way to keep our hosting costs lower and our infrastructure flexible for only a bit more administrative work by our DevOps/IT team.

Thanks!

**Comment by mhurtrel** [comment]
Hello @Parsonswy and thanks for your interest !
I can definitely confirm that we will offer the support for this use case, in countries where OVHcloud or its subsidaries offer Managed K8s, inclusing USA, but I can not yet give you a commited ETA. 

We are still investigating the possible ways to support it and I anticipate the feature to now land early 2022.

**Comment by MJBGO** [comment]
Hi @mhurtrel,

Any new ETA about that feature ? :)

Thanks !

**Comment by vixns** [comment]
It's been a year since someone ask, so, any ETA on this feature ?

**Comment by sp2ed2** [comment]
I'm disappointed with this!

It went from coming soon to coming maybe at the end of the year to coming whenever to... "no comment".

I'm not a massive customer, but five figures spend per year. I stayed with OVH Managed K8s while waiting for this feature, but it never came, evidently because OVH decided it was more profitable to continue to lock us into the more expensive public cloud nodes.

I would've been happy if it even restricted external worker nodes to being part of the vRack (meaning all external worker nodes still had to be OVH servers, and premium ones rather than SYS or Kimsufi)

I would have also been happy to pay 10Eur/month for each external worker node (up to a fixed 100 Euro/month for 10 or more) or something like that.

I'm going back to self managed K8s, and not necessarily with OVH!

**Comment by mhurtrel** [comment]
Hello @sp2ed2 an other users interested in this.
Sorry for the long silence. I confirm we are currently developping a solution that will support self managed nodes, both at OVHcloud and anywhere (needing internet connectivity). 

The details of the exact featureset and pricing cannot yet be shared, vut i can share with you that we sould be able to start registering for private beta late september and deliver access to first users in October.

**Comment by sp2ed2** [comment]
Thank you. I hope that the pricing can be based on self managed node quantity rather than a fixed fee.

**Comment by mhurtrel** [comment]
@sp2ed2 yes, it will be :)

**Comment by mhurtrel** [comment]
Hi everyone ! 

We decided to go for another solution to manage self-managed worker nodes.
I invite you to subscribe to this issue if you look to leverage self-manged infrastructure on Kubernetes at OVHcloud : 
https://github.com/ovh/public-cloud-roadmap/issues/467  . A private beta will be open in the next few months.

**Comment by mhurtrel** [comment]
Hi everyone !

We decided to go for another solution to manage self-managed worker nodes.
I invite you to subscribe to this issue if you look to leverage self-manged infrastructure on Kubernetes at OVHcloud :
https://github.com/ovh/public-cloud-roadmap/issues/467 . A private beta will be open in the next few months.

**Comment by mhurtrel** [comment]
Hi Everyone !

Note that we just released Managed Private Rancher in alpha (aka private beta). This product, amongst many other features, allow you to create and self-manage kubernetes clusters on virtual machines or baremetal nodes, be them at OVHcloud, on premises or in any other cloud, provider they have internet connectivity.
To be one of the first users of this managed service, please complete the short form available here : https://labs.ovhcloud.com/en/managed-rancher-service/
