### ISSUE TITLE
Allow to use object storage bucket as backend for OVH managed LB

### ISSUE THREAD

**Issue by tanandy** [ovh/public-cloud-roadmap#200]
As a user I want to be able to setup bucket as backend in OVH managed LB
I want to be able to plug or not OVH CDN in front of my object storage bucket
I want to be able to consume these features through standard APIs / OVHcloud Customer panel
Then i will be able to host static website on object storage behind OVH LB with a cert (classic pattern)

**Comment by ducnm0711** [comment]
bumping issue, we need this feature

**Comment by lason-ovh** [comment]
Hi @tanandy, do these features https://github.com/ovh/public-cloud-roadmap/issues/351 & https://github.com/ovh/public-cloud-roadmap/issues/316 and answer your needs?

**Comment by rym-dd** [comment]
Hi @lason-ovh 

It doesn't fix the issue.
To reproduce, you have to:
* got to https://www.ovh.com/manager/#/dedicated/configuration/cdn
* select a CDN
* select a domain
* `Statistics` > `Network` > `Server` > `Change backend`
* In `New backend` add an fqdn > Save
* The new backend is not saved

**Comment by rym-dd** [comment]
Hi @lason-ovh @agoude 

The issue is closed but the problem is persistent.
Do you have news about this?

Regards.

**Comment by lason-ovh** [comment]
> Hi @lason-ovh @agoude
> 
> The issue is closed but the problem is persistent. Do you have news about this?
> 
> Regards.

Hi, we may have to check if it is a bug or not. We'll let you know asap

**Comment by daulet2030** [comment]
is this issue fixed? or just closed?
