### ISSUE TITLE
Audit logs for OVH account

### ISSUE THREAD

**Issue by tanandy** [ovh/public-cloud-roadmap#202]
As a user I want to be able to audit my OVH account (Login, Creation / Update / Delete and more generally usage)
I want to be able to consume these features through standard APIs / OVHcloud Customer panel
I want to be able to export audit logs
Then i will be able to follow activities and increase security & auditability

**Comment by LisaPerrier** [comment]
Hi @tanandy 
FYI, an issue has been created and will be kept up to date :D 
https://github.com/ovh/public-cloud-roadmap/issues/403
