### ISSUE TITLE
Serverless / Container-as-a-Service

### ISSUE THREAD

**Issue by tanandy** [ovh/public-cloud-roadmap#204]
As a user I want to be able to use serverless containers for the public cloud
I want to be able to consume these features through standard APIs / OVHcloud Customer panel
Then i will be able to deploy highly scalable containerized applications on a fully managed serverless platform.

history: https://github.com/ovh/public-cloud-roadmap/issues/90

**Comment by tanandy** [comment]
Basic requirements: 

- Scale to zero

**Comment by mhurtrel** [comment]
Merged with #90

**Comment by mhurtrel** [comment]
@tanandy I integrated #90 to our "container and orchestration" backlog, and we have interesting first user feedbacks on CaaS on that one from another user. Do not hesitate to add your there. Let us keep you other issues around FaaS and Serverless DBaaS too (not yet in our roadmap but open to discussion)
