### ISSUE TITLE
Flat k8s networking

### ISSUE THREAD

**Issue by pierreis** [ovh/public-cloud-roadmap#208]
As a user, I want to be able to create multiple clusters in multiple regions, share a VPC, and be able to have pods on different clusters communicate directly with each other. This would also allow services on the same VPC to address pods directly by their IP.

This would make it possible, for example, to create Istio multicluster deployments without the need for private-private load balancers.

**Comment by mhurtrel** [comment]
Hi @pierreis Actually if you use Private networks in public cloud with the same VLAN but make sure to use subnets with non-overlapping IPs for each cluster, this is doable today. (the capacity to specify a subnet at cluster creation was added recently, enable that usecase).
