### ISSUE TITLE
AI Notebooks - Choice in Python and ML frameworks versions

### ISSUE THREAD

**Issue by mhrng** [ovh/public-cloud-roadmap#216]
## User story
As a customer,
when I launch a notebook, I would like to be able to select from multiple versions of frameworks such as PyTorch, Tensorflow, fastai, MXNet... with diverse versions of Python (3.7, 3.8, 3.9...)
in order to
avoid any compatibility issues that may arise on my work (if I need to stick to a particular version of a framework or of Python, for easier use and flow...).

As a Cloud Provider,
I want to build and provide all framework environments over the same base image
so that
I improve maintainability over time and consistency for my customers.

## Acceptance criterias
- Ability to select different versions of ML frameworks such as MXNet, Pytorch, Tensorflow, FastAI, Huggingface
- Ability to select different versions of Python for each framework
- Ability to deploy through CLI, UI, API
- Compliant with CPU/GPU
- Built from a similar base image (Python + Conda)

## Follow, vote and give your feedback
You can follow this task with the notification on the right tab.
Ask us anything here in the comments below, and vote with emojis for most requested items !
👍 to vote for this issue

## Discuss on Discord
Feel free to discuss with us on https://discord.com/invite/PwPqWUpN8G

**Comment by baaastijn** [comment]
Hello, already done for Tensorflow environment and Conda environment
Other in progress, have a good day !
