### ISSUE TITLE
AI Notebooks - More flexibility on package management (Conda)

### ISSUE THREAD

**Issue by mhrng** [ovh/public-cloud-roadmap#217]
## User story
As a customer,
I would like to have flexibility in my Notebooks environment and install anything from Conda no matter which framework I use,
so that
I am not stucked in my explorations. I can freely install packages, libraries and so on from the web and experiment my code with almost no limitations.

## Acceptance criterias
- Ability to imitate the ROOT user through Conda open source software (https://docs.conda.io/en/latest/)
- everything that can be installed through Conda should be available
- available in all ML frameworks offered by OVHcloud

## Follow, vote and give your feedback
You can follow this task with the notification on the right tab.
Ask us anything here in the comments below, and vote with emojis for most requested items !
👍 to vote for this issue

## Discuss on Discord
Feel free to discuss with us on https://discord.com/invite/PwPqWUpN8G

**Comment by baaastijn** [comment]
Hello, already the case for Tensorflow environment and new Conda one, have a good day !

**Comment by mhrng** [comment]
Already available with Miniconda + through PyTorch and TensorFlow frameworks
