### ISSUE TITLE
AI Notebook - scikit-learn framework

### ISSUE THREAD

**Issue by mhrng** [ovh/public-cloud-roadmap#218]
## User story
As a customer,
I would like to start new AI Notebooks with a pre-installed scikit-learn framework.
so that
I can easily use scikit-learn with CPU and GPU in production, in few seconds.

 
## Acceptance criterias
- Preinstalled scikit-learn framework in the notebook
- Choice is scikit-learn version
- Full compatibility with diverse Python versions
- Ability to deploy via UI, CLI or API
- Ability to deploy with CPU or GPU resources

## Follow, vote and give your feedback
You can follow this task with the notification on the right tab.
Ask us anything here in the comments below, and vote with emojis for most requested items !
👍 to vote for this issue

## Discuss on Discord
Feel free to discuss with us on https://discord.com/invite/PwPqWUpN8G

**Comment by baaastijn** [comment]
Hello, we just added scikit learn as a specific AI Framework. Enjoy !
