### ISSUE TITLE
Terrafom to update name of cluster

### ISSUE THREAD

**Issue by Grounz** [ovh/public-cloud-roadmap#222]
Hi,

We use Terraform for create kubernetes cluster with `ovh_cloud_project_kube` module.

When we want update cluster name, the module force replacement of cluster.

It's possible to rename a cluster in the OVH Manager, so there must be correspanding api call.

Would be possible to update cluster name without recreating cluster via `ovh_cloud_project_kube` ?

**Comment by mhurtrel** [comment]
Hi @Grounz This is a good point !
I consider this as a bug of the provider more than a feature, and we have a new version of the terraform provider in the pipe (to handle new properties on nodepools and cluster). I will ask the team to make sure we manage this need at the same time.

**Comment by mhurtrel** [comment]
This has been fixed in the meaintime
