### ISSUE TITLE
BHS workflow: Automatic instance backup not running since Apr 12

### ISSUE THREAD

**Issue by karljohns0n** [ovh/public-cloud-roadmap#225]
Hello,

Automatic instance backup workflow aren't running anymore since Apr 12 ( 10 days ago) on BHS5 region, in multiple projects, see below;

<img width="200" alt="status" src="https://user-images.githubusercontent.com/13647791/164715813-669723da-dfce-4406-97ef-619af8871f94.png">

Therefore all instance backups are getting really old;

<img width="200" alt="status" src="https://user-images.githubusercontent.com/13647791/164715919-fcf823fe-63f0-4eba-ac90-2e882fd2a8db.png">

This is a critical issue as backups are so important.

At the same time, BHS region is missing in OVH status page workflow section;

<img width="200" alt="status" src="https://user-images.githubusercontent.com/13647791/164716141-95be280d-2f4d-47c1-ba60-701c02171d9c.png">

Thanks,

**Comment by JacquesMrz** [comment]
Hi all,
We identified an issue on Mistral component in BHS5 region. The issue has been fixed.
We will soon improve the monitoring of Mistral so this kind of long lasting issue will not happen again.
Indeed, backups are critical, we are very sorry.
