### ISSUE TITLE
Managed Private Registry IP restrictions

### ISSUE THREAD

**Issue by mhurtrel** [ovh/public-cloud-roadmap#23]
As a MPR administrator
I want to restrict Harbor and Docker Registry APIs to a selection of IPs
So that I have a extra level of security (additional to Harbor RBAC)

**Comment by matmicro** [comment]
Hi @mhurtrel , 

can you provide an ETA for this ?

As a user of MPR i want :
- to restrict access by IP address (external public IP)
- allow access for any internal instances of my projects
   - through vRack ?
   - allow a specific Public Cloud project ? (if i don"t know in advance my nodes IP address).

**Comment by mhurtrel** [comment]
@matmicro 
- access by IP address (external public IP) : this is this ticket. I don't have a precise eta yet, but roughly next automn ou winter
- restriction to a given vrack : this is not planned yet but will be, hoppefully in 2022
- to the instances of a given public cloud project : this is not planned but will be doable through the vrack restriction

**Comment by clement-igonet** [comment]
Is there any way to isolated an OVH managed "private" docker registry, with IP restriction, or with a vRack/vLan solution ???
Indeed, vRack advertises a solution to connected together OVH services in a kind of "bastion".
So what about the managed harbor docker registry ?

**Comment by antonin-a** [comment]
Hello @clement-igonet , thank you for raising this concern. I do confirm that the goal of this roadmap item is to provide IP restriction (whitelisting) on the OVHcloud Managed Private Registry. 
For the vRack solution it is also plan and we can track it here: https://github.com/ovh/public-cloud-roadmap/issues/541

**Comment by clement-igonet** [comment]
Roadmap for an issue going back 3 years ago...
What's the priority, please ?

**Comment by antonin-a** [comment]
Hello @clement-igonet @matmicro , IP restriction is almost done. We haven't made any announcements yet as we are finalizing the documentation and terraform resources but APIs are already exposed:
- IP restriction for Management components (UI and API): 
https://api.ovh.com/console/#/cloud/project/{serviceName}/containerRegistry/{registryID}/ipRestrictions/management~PUT
- IP restriction for artifact manager component (Docker, Helm, etc...)
https://api.ovh.com/console/#/cloud/project/{serviceName}/containerRegistry/{registryID}/ipRestrictions/registry~PUT

For vRack it will take a bit longer as we need a new network feature called 'vRack Endpoint' (I've created a dedicated issue for this one)

**Comment by antonin-a** [comment]
IP restriction is now available for Managed Private Registry.
Guide is available here : [Adding IP restrictions on an OVHcloud Managed Private Registry](https://help.ovhcloud.com/csm/en-public-cloud-private-registry-add-ip-restrictions?id=kb_article_view&sysparm_article=KB0061370).

**Comment by antonin-a** [comment]
Terraform ressource devellopement is in progress, should be finished by next week.

**Comment by nicolaslacroux** [comment]
We’re excited to announce that the IP restrictions feature for Managed Private Registry is now available in the OVH Console. This feature allows you to restrict access to your Managed Private Registry  from specific CIDR addresses, enhancing the security of your container images.

To enable this feature, go to the Managed Private Registry section in your OVH Console and configure the allowed IP addresses in "Manage authorized CIDR blocks"

Best regards,
