### ISSUE TITLE
AI Tools - "Read Write Delete" granularity on access rights for my data

### ISSUE THREAD

**Issue by mhrng** [ovh/public-cloud-roadmap#230]
## User Story
As a customer,
I would like to have three levels of granularity for access rights on my data:
- Read Only
- Read Write
- Read Write Delete

so that
I can choose whether I can just read them, or write and modify them, or even delete my data in this object container, especially when I work on code, if I want to save a model or connection weights after my training.

## Acceptance criteria
- Ability to select 3 levels of permission for each attached object storage container
- When the delete permission is granted, OVHcloud deletes data on object storage
- Ability to deploy via UI, CLI or API (CLI and API only for the RWD right)
- Up to date documentation on OVHcloud website
	

## Follow, vote and give your feedback
You can follow this task with the notification on the right tab.
Ask us anything here in the comments below, and vote with emojis for most requested items !
👍 to vote for this issue

## Discuss on Discord
Feel free to discuss with us on https://discord.com/invite/PwPqWUpN8G

**Comment by mhrng** [comment]
OVHcloud documentation is being updated

**Comment by baaastijn** [comment]
Hello, granual rights are already available in CLI and API, todo in the web UI

**Comment by mhrng** [comment]
Hello,
OVHcloud documentation is updated and all access rights are now available from the OVHcloud Control Panel.
