### ISSUE TITLE
Expose managed databases logs to OVHcloud Opensearch

### ISSUE THREAD

**Issue by baaastijn** [ovh/public-cloud-roadmap#232]
## User story ##
As a customer,
I want to expose my managed databases logs to internal OVHcloud offer OpenSearch easily
So that 
I able to get efficient and advanced logs dashboard instead of just "live logs"

## Acceptance criterias ##
- available for MySQL, PostgreSQL, Redis, Kafka, M3, Cassandra
- I can ask for logs integration from public cloud databases to Ovhcloud OpenSearch in few clicks or API
- retention is not limited (except about remaining disk space)
- My OpenSearch instance can accept multiple data source (for example 5 databases, 3 VMs, ...)

Requirement : customer will have to buy a managed OpenSearch before being able to push logs in it.

## Follow, Vote and give your Feedback ##
You can follow this task with the notification on the right tab.
Ask us anything here in the comments below, and vote with emojis for most requested items !
👍 to vote for this issue

## Discuss on Discord ## 
Feel free to discuss with us on https://discord.com/invite/PwPqWUpN8G

**Comment by thild42** [comment]
See our [Cross Service Integration guide](https://docs.ovh.com/gb/en/publiccloud/databases/cross-service-integration/) to know more about the feature and how to use it.
