### ISSUE TITLE
Expose managed databases metrics to OVHcloud Grafana/PostgreSQL/M3

### ISSUE THREAD

**Issue by baaastijn** [ovh/public-cloud-roadmap#233]
## User story ##
As a customer,
I want to expose my managed databases metrics to internal OVHcloud offer Grafana or PostgreSQL or M3db  easily
So that 
I able to get efficient and advanced logs dashboard instead of just "live logs"

## Acceptance criterias ##
- available for MySQL, PostgreSQL, Redis, Kafka, Cassandra, OpenSearch
- I can ask for logs integration from public cloud databases to Ovhcloud OpenSearch in few clicks or API
- retention is not limited (except about remaining disk space)
- My OpenSearch instance can accept multiple data source (for example 5 databases, 3 VMs, ...)

Requirement : customer will have to buy a managed Grafana, PostgreSQL or M3 cluster before being able to push metrics in it.

## Follow, Vote and give your Feedback ##
You can follow this task with the notification on the right tab.
Ask us anything here in the comments below, and vote with emojis for most requested items !
👍 to vote for this issue

## Discuss on Discord ## 
Feel free to discuss with us on https://discord.com/invite/PwPqWUpN8G

**Comment by tanandy** [comment]
Hi, we expect to be able to consume also metrics on external Grafana too.

**Comment by matmicro** [comment]
As Managed Database (Postgresql) user i would be also interested in having :
- PGBouncer (pools) stats :
   - inbound connections (from client to pool)
   - outbound connections (from pool to database)

**Comment by baaastijn** [comment]
Hello, 

We are moving forward on this ! We just released API to do it

**Please note that our goal is to provide an easier ergonomy. This guide is to try integration before it** 

# Integration concept
We now authorize cross database services integrations for Logs and Metrics.
For example, 
- send Redis or MySQL metrics or  Cassandra metrics in M3db or PostgreSQL
- send PostgreSQL or MySQL metrics to OpenSearch
- show metrics in Grafana

For that you need : 
- a source service
- a destination service

Out of scope : 
- expose metrics and logs outside OVH public cloud
- MongoDB

# API routes

routes are in OVHcloud API in 
/cloud/project/{serviceName}/database/[YOUR_DBMS]/{clusterId}/integration/*


# Example : PostgreSQL metrics shown in Grafana

## Step 1 :  connect to OVHcloud API
go in https://api.ovh.com/console/ (or Canadian version if required)
log in the top right corner.

## Step 2 : get integration capabilities

run the following call with your service ID (in our example, PostgreSQL service ID is 118541e7-0737-4cf9-b748-24d81812c9c9
https://api.ovh.com/console/#/cloud/project/{serviceName}/database/postgresql/{clusterId}/capabilities/integration~GET

It will give you ALL the possible integration for your specific services.

![step2 capa](https://user-images.githubusercontent.com/16922182/167869974-77af1f3f-a271-457b-a4ed-19fe4efc307b.png)

We will use two integration here for information : 
`{

    type: "postgresqlMetrics"
    sourceEngine: "postgresql"
    destinationEngine: "postgresql"

}`

and later
`{

    type: "grafanaDashboard"
    sourceEngine: "grafana"
    destinationEngine: "postgresql"

}`


### Step 3 : store PostgreSQL metrics somewhere

As a first step, you need to push your PostgreSQL somewhere, in order to store them an retrieve them with grafana

Again, grafana is only a data visualization tool, without storage space.

In this example, **we will store the metrics in the same PostgreSQL cluster**. it's for a test, usually you take another cluster (M3 or PostgreSQL).

Use the call https://api.ovh.com/console/#/cloud/project/{serviceName}/database/postgresql/{clusterId}/integration~POST
With parameters = NULL and type = postgresqlMetrics
Source and destination are the same (PostgreSQL service ID)

![step2](https://user-images.githubusercontent.com/16922182/167870183-bc9c4e94-a869-4cc6-8d82-e62dd33b2c4c.png)

## Step 4 : Allow metrics visualization into Grafana

Now that metrics are stored somewhere, we need to connect this PostgreSQL cluster to a Grafana service

For that, first create a Public cloud Database for Grafana via our control panel or API
Once done, create a second integration : 

API call : https://api.ovh.com/console/#/cloud/project/{serviceName}/database/postgresql/{clusterId}/integration~POST

![step3](https://user-images.githubusercontent.com/16922182/167872377-b6ed48bf-aab5-4f01-8399-b4b4b6ea9e4d.png)

## Step 5 : connect to Grafana and see your metrics

Once ok,
Go back to OVH control panel, configure grafana : admin user and IP whitelisted.

Connect to Grafana and browse the dashboard. One is already there as shown below

list of exposed metrics : https://developer.aiven.io/docs/products/postgresql/reference/pg-metrics.html

![Screenshot 2022-05-11 at 15 39 32](https://user-images.githubusercontent.com/16922182/167873117-63d06645-889e-4616-898a-f689814ab2ef.png)

![Screenshot 2022-05-11 at 15 39 44](https://user-images.githubusercontent.com/16922182/167873124-5edadf1b-25bb-49b2-adf5-0268562f344e.png)

![Screenshot 2022-05-11 at 15 39 54](https://user-images.githubusercontent.com/16922182/167873127-17c56de5-d9a4-4523-a02e-eca7d371dad3.png)

![Screenshot 2022-05-11 at 15 40 04](https://user-images.githubusercontent.com/16922182/167873130-b5481677-9381-4025-9e69-295194d2e1a0.png)

**Comment by thild42** [comment]
See our [Cross Service Integration guide](https://docs.ovh.com/gb/en/publiccloud/databases/cross-service-integration/) to know more about the feature and how to use it.
