### ISSUE TITLE
Improving connection time for Object Storage

### ISSUE THREAD

**Issue by midnight-wonderer** [ovh/public-cloud-roadmap#235]
The browser connection to
https://\<bucket>.s3.\<region>.cloud.ovh.net
is painfully slow.

I already submitted the ticket; I discovered this channel shortly after; I supposed here is the more appropriate place for suggestions.

This is about the existing Swift object storage with S3-compatible endpoints, not the [upcoming product](/ovh/public-cloud-roadmap/issues/44).
From my browser, it took around 1.5-2.0 seconds to fetch 60 KiB images. Making the website painfully slow overall.

While I won't judge what's underneath, there is a couple of simple things OVH can do to improve the connection speed.

- First, the TLS is misconfigured. OVH servers send the anchor (root certificate) along with the certificate chain.
![SSL Test](https://i.imgur.com/LQACJ1p.png)
By configuring the certificate chain properly, the connection time can be improved a bit.
- Second, since one of the common use cases for the s3 bucket is to store user-uploaded images, it'd be great if OVH could enable HTTP/2 on https://\<bucket>.s3.\<region>.cloud.ovh.net so the perceived load time can be improved.
- Third, The DNS resolution time is awful; it took around 600 ms from here with a reputable recursive resolver just to resolve the hostname. Can OVH do something about it? How about geo-distributed DNS solutions?

**Comment by midnight-wonderer** [comment]
Unfortunately, as I am located in Southeast Asia; does the new offer in the SGP region is in your (company) priority too?

**Comment by lason-ovh** [comment]
> Unfortunately, as I am located in Southeast Asia; does the new offer in the SGP region is in your (company) priority too?

Hi, all regions are our priority, however the roll out of features is being done sequentially region by region
