### ISSUE TITLE
Expose managed databases logs/metrics to external services

### ISSUE THREAD

**Issue by tanandy** [ovh/public-cloud-roadmap#238]
As a customer,
I want to expose my managed databases logs/metrics  to external services like existing external grafana
Then I will be able to follow managed databases inside my own customer observability system (centralization)

**Comment by ChrisEU** [comment]
I agree. It would be very useful if the database exposes a /metrics endpoint that can be scraped by Prometheus running within a k8s cluster. 
(exposing that endpoint could be a paid add-on, say a few euros per month)

**Comment by thild42** [comment]
Duplicate  #153
