### ISSUE TITLE
Node Pools Autoscaling

### ISSUE THREAD

**Issue by mhurtrel** [ovh/public-cloud-roadmap#24]
As a MKS user
I want to define a minimum and maximum of nodes for a nodepool to auto-scale based on CPU and RAM requests
So that my cluster auto-scales depending on my business needs.

Notes : 
Developing you own auto-scaling based on custom rules is already achievable though the manipulation of the Node Pools CRD

**Comment by mhurtrel** [comment]
We will release the feature in private beta in a couple of weeks.

**Comment by mhurtrel** [comment]
After evaluating options and a few inetrnal tests, we decided to go directly for a public beta, which we had planned to open next week. As you may know we had an incident in one our our datacenters earlier this week, and our roadmap is slightly impacted as we prioritize helping the impacted customers. I will update the information here as soon as possible.

**Comment by mhurtrel** [comment]
Th feature will be published in public beta (with documentation, usable only though API and Kubernetes API/CRD at first) early next week.

**Comment by cambierr** [comment]
Is it supposed to work already if I do update the NodePool crd sped ? I see that `autoscale: false` field

**Comment by mhurtrel** [comment]
Hi @cambierr not yet, but will be next week.

**Comment by mhurtrel** [comment]
The feature is now available for all existing and new clusters !

We will consider the feature in public beta until early summer for the following reasons : 
- We want to have the feature used in more diverse use cases that we were able to test it internally.
- We want to have your feedback about default values and/or need to allow configuration of some of the advanced parameters ( see https://docs.ovh.com/gb/en/kubernetes/configuring-cluster-autoscaler/ for details . our initial plan is to keep the feature as simple as possible to ensure better supportability)
- We will offer the feature in the web control panel (aka OVHcloud Manager), while it is for the moment usable ontly through OVHcloud APIv6 and Kubernetes CRD.

Here is the full documentation :  
https://docs.ovh.com/gb/en/kubernetes/using-cluster-autoscaler/
https://docs.ovh.com/gb/en/kubernetes/cluster-autoscaler-example/
https://docs.ovh.com/gb/en/kubernetes/configuring-cluster-autoscaler/

**Comment by tgruenert** [comment]
As a MKS user i want use the node autoscaler function for my workload. What kind of node i need depends on my workload (general, cpu , iops ...). A nodepool for every used nodetype is already created. 

A workload should deployed on a node from a defined nodepool. So i need a solution to express a node affinity for my workload. 

As example the deployment looks like this:
```
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: workload-type
            operator: In
            values:
            - iops
```

If I deploy a workload with this setting, a new node from matching nodepool should deployed (if needed).

So imho the scaler has to become a label function. These labels indicated which nodepool to use. And the scaler has to set these label to new launched nodes.

But maybe there is also an other solution that i not realized yet?

**Comment by mhurtrel** [comment]
@tgruenert You may be interested in that issue and its most recent comment comment : https://github.com/ovh/public-cloud-roadmap/issues/87 .You can already create multiple nodepools, with different autoscaling parameters and target a specific one for a given deployment, but yes, autolabelling of nodepools depending on flavors would make it easier, and we plan to do so.

**Comment by mhurtrel** [comment]
(our frontend team are polishing translations and review to have the utoscaling appear in the web control pannel aka manager)

**Comment by tgruenert** [comment]
@mhurtrel thank you  for referencing the other issue. that is exactly what i am looking for. 
But i am interested how you would 
> target a specific [nodepool] for a given deployment

Could you give us a hint for this? 
Thank you in advance!

**Comment by mhurtrel** [comment]
The feature should be relase in the control panel before the end of this week.

@tgruenert as a workaound  before we release https://github.com/ovh/public-cloud-roadmap/issues/87 , my colleague Xavier suggest you hav a look on https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/ , and set up an AdmissionController to mutate news nodes automatically on certain conditions

**Comment by mhurtrel** [comment]
A new bug (limited to the UI) was found and the feature deployment in the control panel is move forward a week, but remains totally stable from the API/CRD.

**Comment by mhurtrel** [comment]
The Node Pools (aka cluster) Autoscaling is now in production in the control panel (aka manager) !
Both offered when creating the first nodepool at cluster creation and from the "Node Pools" view 🙂
The feature is available for all customlers, in all regions, except US (where it is available though API and Kubernetes CRD)
It should be prodded in US soon.

**Comment by mhurtrel** [comment]
![image](https://user-images.githubusercontent.com/24432524/127136789-c99b4432-c272-4caf-a059-2493c9369671.png)

**Comment by tanandy** [comment]
amazing !! now lets have the possibility to spawn node in different region :)

**Comment by mhurtrel** [comment]
The feature has now also been deployed by our OVHcloud US friends
