### ISSUE TITLE
Harbor Major upgrade (2.3+)

### ISSUE THREAD

**Issue by brennerm** [ovh/public-cloud-roadmap#240]
As a Managed Private Registry (2.0+) user
I want to benefit from a more recent Harbor version
To leverage the lastest features 

-----
original story

As a Harbor administrator I'd like to use the proxy cache functionality, e.g. to avoid running into Docker Hub's rate limiting.

As described [here](https://goharbor.io/docs/2.1.0/administration/configure-proxy-cache/) this functionality is supported by Harbor but it seems to be currently disabled in the OVH managed registry offering as seen on the screenshot.
|Expected|Actual|
|-|-|
|![image](https://user-images.githubusercontent.com/5527832/168799063-20111aee-1f27-420b-a939-e305b8883191.png)|![image](https://user-images.githubusercontent.com/5527832/168798954-0478981d-cff0-4fbc-9b06-5ffa5c670143.png)|

**Comment by sergelogvinov** [comment]
I think this is a version issue. Harbor on OVH is too old.

Do you have a plan to upgrade the Harbor?  It is a very useful feature to have docker-proxy near your cluster.

Thank you.

**Comment by mhurtrel** [comment]
Hello everyone !
I confirm this feature will come with us bumping Harbor to a recent version later this year.

**Comment by arcalys** [comment]
Any ETA for this upgrade?

**Comment by mhurtrel** [comment]
Updated story. we currently target very early 2023

**Comment by mhurtrel** [comment]
The team is  glad to announce the release of Harbor 2.4.1 today 🎉.
For now, only new Managed Private Registry services are running on this new Harbor version.

All existing Harbor 2.0.1 services will be upgraded early 2023 (customer will get informed and this issue will be updated).
Current can customer that do not want to wait for this managed upgrade can consider spwaning a new service and using the harbor replication feature to migrate all their data.

Main new features are:
- Proxy-cache (https://goharbor.io/docs/2.4.0/administration/configure-proxy-cache/)
- Garbage-collection improvements (stability / non blocking)
- System Level Robot Account (in addition to project robot accounts)
- Trivy bumped to v0.20
- Huge performance improvements

Full list of features:

- 2.4: https://github.com/goharbor/harbor/releases/tag/v2.4.0
- 2.3: https://github.com/goharbor/harbor/releases/tag/v2.3.0
- 2.2: https://github.com/goharbor/harbor/releases/tag/v2.2.0
- 2.1: https://github.com/goharbor/harbor/releases/tag/v2.1.0

**Comment by brennerm** [comment]
@mhurtrel Awesome, huge thanks to you and the team!

**Comment by Samuel29** [comment]
Hi and Happy New year. 
last release of Harbor is 2.7.x does this impact this task and its delivery date ?
side question: how will the upgrade be deployed on the existing harbor instances ?

**Comment by mhurtrel** [comment]
Hello @Samuel29 2.7 release does not change our plans.
Existing Harbor 2.0 will be upgraded during February and March.

As this upgrade will require a small period of downtime, each customer will receive an email in the following weeks, telling him the planned window for his services(s), and every customer will be given an option to optin for another window.

Please note that we took this opprtunity to bring major performance improvment to the performance of the service, leveraging our recently launched S3 object storage as Backend and other major infrastructure updates. 
This major replatforming also allo us to plan new regions opening in Spring, and more regular upgrades to even more recent versions of Harbor in the future.

**Comment by Samuel29** [comment]
Many thanks for the update @mhurtrel this upcoming upgrade looks way better than I expected.

**Comment by jMonsinjon** [comment]
Hello,
In the 2.2 version, Harbor introduced the "[System Level Robot Account](https://github.com/goharbor/harbor/releases/tag/v2.2.0)" and deprecated other robot-accounts.
In the 2.4 version, legacy robot-accounts have been [removed](https://github.com/goharbor/harbor/releases/tag/v2.4.0).

Migrating from Harbor 2.0 to 2.4 would have resulted in a breaking change.

That's why we decided to migrate all your registries to **Harbor 2.3**, in a first step.
This migration will start mid February until mid March. You will receive an email (tomorrow) with your update window, and the procedure if you want to change it.

We are already ready to migrate your registries from 2.3 to 2.4, so the next version upgrade will be planed very soon (2023 April~May).

**Comment by mhurtrel** [comment]
All customers with a managed private registry running Harbor 2.0 instance should have received an email indicating the date of their planned automatic upgrade to Harbor 2.3 and can force another upgrade windows by completing the following survey : https://survey.ovh.com/index.php/114447?lang=en

**Comment by matmicro** [comment]
Hi,

I was hoping for a migration to 2.4 but it looks it's only 2.3 (which does not includes Proxy Cache).

Do you have any ETA to share for 2.4 upgrade ?

Regards

**Comment by mhurtrel** [comment]
Hi @matmicro 
I confirm Harbor 2.3 suports proxy cache : https://goharbor.io/docs/2.3.0/administration/configure-proxy-cache/ 
Nevertheless, we will communicate during Spring about new dates for upgrading th Harbor 2.4 and next versions (some includes breaking changes that we need to handle.

**Comment by LisaPerrier** [comment]
Closing this issue since there is a new upgrade with less impact coming really soon :  https://github.com/ovh/public-cloud-roadmap/issues/379
