### ISSUE TITLE
Managed databases - configure how long backups are retained for

### ISSUE THREAD

**Issue by dantownsend** [ovh/public-cloud-roadmap#241]
As a user I would like to be able to configure how long backups are retained for in the managed database product.

<img width="1005" alt="Screenshot 2022-05-18 at 20 29 23" src="https://user-images.githubusercontent.com/350976/169141461-19fef985-0a6e-4d73-8d1e-e03ae223d456.png">

For the essential plan, 2 days is too short for many use cases. It would be useful if users could configure this to be 7 days. Or even set it to 0 if being used in a staging environment.

(Apologies if this already exists, or is on a roadmap - if so, please delete).

**Comment by thild42** [comment]
Essential plan is not really suited for a production environment so 2 days seems more than enough for development, testing or any other non-production purpose.
