### ISSUE TITLE
Install the Kubernetes dashboard at cluster setup

### ISSUE THREAD

**Issue by qualitesys** [ovh/public-cloud-roadmap#243]
I am new to OVHCloud, and have tested a K8S Cluster setup.
Would it be possible to install (by default or by option) the standard Kubernetes Dashboard [1] ?
The "how to guide" is available at OVH but from the user point of view, it should be pre installed.

Thanks for your answer

[1] : https://kubernetes.io/fr/docs/tasks/access-application-cluster/web-ui-dashboard/

**Comment by mhurtrel** [comment]
Hello @qualitesys and thanks for your suggestion.
Though this was a regurlar requests during our Beta 3 years ago, we wince see a lot less customers asking for this and have decided to de-priritize this feature for a few reasons : 
- The UI adds some workload to the cluster and elarges the surface of attack (it could contain CVE that would put in danger the cluster if not securirez and updated regurlarly)
- The vast majority of our customer use CLI tools, and there is a clear move toward external multicluster tools such as Lens or Rancher and others that have all the advantage of the dashboard without its disadnatge below
- As you said this is qui straightforward to deploy via official helm charts.

So at the moment, this is not condidred anymore as a dedicated feature in the backlog, but not that we are considering offering a service catalog in the future that would contain a series of apps for 1 click deploy, and dhaboard could be one of them : https://github.com/ovh/public-cloud-roadmap/issues/81

**Comment by miragecentury** [comment]
Hi, you can use a tool like [Lens](https://k8slens.dev/). It keep the workload spread on the "user resource" instead of in the cluster.

**Comment by mhurtrel** [comment]
We decided not to priotize this for reasons mentionnend above. Note that a web user friendly UI is available though our new Managed Rancher Service, usable for any Kubernetes including our Managed Kubernetes Service.
