### ISSUE TITLE
Managed databases

### ISSUE THREAD

**Issue by baaastijn** [ovh/public-cloud-roadmap#25]
As a Public Cloud user
I want to launch quickly and easily managed databases instances.
So that I can focus on my core business and automate my architecture.

Note:
- MongoDB at very first
- Followed by Relational databases (MySQL / PostgreSQL ), then other NoSQL (Redis, ...)
- Can be spawned via UI/API/automation
- managed service (DBMS major updates, ...)
- Public or Private Network (vRack)
- Backuped
- Optional high-availability

**Comment by snow-evy** [comment]
As a Public Cloud user 
I will highly appreciate the following features in the managed databases: 

- Private Endpoint or availability of the managed databases in the vRack

- Elasticity (not only horizontal scaling, but also scale up/down of storage space using block storage, for example)

- Multi-regions HA with low latency (primary node in SBG, secondary node in FRA)

**Comment by baaastijn** [comment]
> As a Public Cloud user
> I will highly appreciate the following features in the managed databases:
> 
>     * Private Endpoint or availability of the managed databases in the vRack
> 
>     * Elasticity (not only horizontal scaling, but also scale up/down of storage space using block storage, for example)
> 
>     * Multi-regions HA with low latency (primary node in SBG, secondary node in FRA)

Hello @snow-evy,

Elasticity should be there from day 0.
For private endpoint we fully agree on the need :) but we have some dependencies with our Network Team
They work on a "Private Network Gateway" to connect any managed service to vRack. it should not be there at launch of DBaaS.

For the last point, multi region, as you said it has to be low latency. usually you have either
- Multi AZ (availability Zones) in same region, allowing you low latency. For example GRA + SBG
- Multi Region, but quite often hard to have really low latency.

We first target mono AZ, then Multi AZ, and multi region is not planned.

**Comment by Zero3** [comment]
@baaastijn I checked out https://www.ovh.co.uk/cloud-databases/, and noticed that the maximum memory size is 4 GB. That seems quite low to me. Are there any plans to support more than 4 GB ram? Is it possible to order more by contacting support, perhaps?

**Comment by baaastijn** [comment]
> @baaastijn I checked out https://www.ovh.ie/cloud-databases/, and noticed that the maximum memory size is 4 GB. That seems quite low to me. Are there any plans to support more than 4 GB ram? Is it possible to order more by contacting support, perhaps?

Hello, the current offers are : 
Maximum 4GB and no HA, an dmulti-tenant : Cloud Databases you've seen. Cannot go more than that, sorry.
Or starting at 16GB, cluster HA, single tenant, PostgreSQL only : Enterprise cloud Databases. for critical needs.

As you can see the gap is too big and that's why we are developping a database service between those 2.
Work in progress !

**Comment by Sungodragon** [comment]
Multi-Region Read Replica.
HA on Main Instance AKA Multi-AZ
HA of Main Database Instance Same AZ
HA on Read Replica Instance.

**Comment by tanandy** [comment]
@mhurtrel @baaastijn could we get ETA for it please ? because its a must have for a cloud provider

**Comment by baaastijn** [comment]
Hello, here are the timeline we want to deliver.

End of May : deliver MongoDB clusters in beta (no contractual SLA. community licence, 1 to 3 nodes, backups, public/private network.

End of June : deliver MySQL/PostgreSQL/Redis in beta. All with clustering, private/public network, autobackup, automation, ...

September/October. shifts the offers in General Availability. i.e. contractual support and SLA

I will also email customer for Alpha test, in April/May for all of them (services up and ready but without control panel, just API).

**Comment by tanandy** [comment]
do we have an idea of Disk space limits you target ?

**Comment by baaastijn** [comment]
> do we have an idea of Disk space limits you target ?

Fore relational DBMS (MySQL / PostgreSQL) we target 1 vCPU x 4GB RAM x 80GB local SSD storage ratios

just need to multiplicate for 4/8/16/32/64/128/256 GB RAM. Don't hesitate to share your feedbacks about these ratios !

For NoSQL, it will depends. Redis, will be around 30-40GB

**Comment by Julienh** [comment]
Hello,
What about MariaDb please ?

**Comment by matmicro** [comment]
In order to get more affordable prices, is it plan to have smaller offers ? like :
- only 1 replica (1 master RW + 1 replica RO)
- 2 vCPU 8GB RAM

**Comment by baaastijn** [comment]
> Hello,
> What about MariaDb please ?

MariaDB is not planned for the moment. We will have MySQL 8.x

**Comment by baaastijn** [comment]
> In order to get more affordable prices, is it plan to have smaller offers ? like :
> 
>     * only 1 replica (1 master RW + 1 replica RO)
> 
>     * 2 vCPU 8GB RAM

Yes, we will have 3 levels of offers

1. Essentials (1 x VM only)n no private network, only public
2. Business (2x VM only), public or private network
3. Premium (2 x VM minimum, max 8), public or private network, better SLA vs Busines

All of them will start with 1 vCPU / 4GB RAM per node

**Comment by matmicro** [comment]
> Yes, we will have 3 levels of offers
> 
> 1. Essentials (1 x VM only)n no private network, only public
> 2. Business (2x VM only), public or private network
> 3. Premium (2 x VM minimum, max 8), public or private network, better SLA vs Busines
> 
> All of them will start with 1 vCPU / 4GB RAM per node

Great ! Any ETA for this ?
Also do you have an estimate of prices for those offers ?
You confirm that this will be available for PostgreSQL ?

**Comment by matmicro** [comment]
> Yes, we will have 3 levels of offers
> 
> 1. Essentials (1 x VM only)n no private network, only public
> 2. Business (2x VM only), public or private network
> 3. Premium (2 x VM minimum, max 8), public or private network, better SLA vs Busines
> 
> All of them will start with 1 vCPU / 4GB RAM per node

Great ! Any ETA for this ?
Also do you have an estimate of prices for those offers ?
You confirm that this will be available for PostgreSQL ?

Is "Managed database" in the scope and "Enterprise Cloud Databases" ?
FYI currently i cannot use Cloud Database offer as i need to access the DB as postgres user.
Is it planned for Enterprise Cloud Database or those Managed Databases to have postres user access ?

**Comment by baaastijn** [comment]
> > Yes, we will have 3 levels of offers
> > 
> > 1. Essentials (1 x VM only)n no private network, only public
> > 2. Business (2x VM only), public or private network
> > 3. Premium (2 x VM minimum, max 8), public or private network, better SLA vs Busines
> > 
> > All of them will start with 1 vCPU / 4GB RAM per node
> 
> Great ! Any ETA for this ?
> Also do you have an estimate of prices for those offers ?
> You confirm that this will be available for PostgreSQL ?
> 
> Is "Managed database" in the scope and "Enterprise Cloud Databases" ?
> FYI currently i cannot use Cloud Database offer as i need to access the DB as postgres user.
> Is it planned for Enterprise Cloud Database or those Managed Databases to have postres user access ?

Once i have better ETA i will split this issue on several issues, per DBMS. so far Beta for MySQL/PostgreSQL/Redis is planned for this summer.

Enterprise cloud Database : it's an existing solution at OVHcloud, but not VM-base din the public cloud. It's minimum 3 physical nodes (dedicated servers) and only PostgreSQL is proposed (with psotgres user). 

We will not provide superuser for PostgreSQL but propose methodes to activate extensions, play with logical_replication or auto_explain.

**Comment by fredhusser-metronome** [comment]
Hi, 
Is there a way to enroll for the alpha phase for Postgres managed database?

**Comment by baaastijn** [comment]
> Hi,
> Is there a way to enroll for the alpha phase for Postgres managed database?

Hello, Posting here is enough :)
For information : MongoDB public beta (free) will start today. feel free to test it
PostgreSQL/MySQL/Kafka planned for September.

**Comment by matmicro** [comment]
Could you please include me as well to be beta tester for PostgeSQL and Redis ?
Hope this could be available soon.
Thanks

**Comment by baaastijn** [comment]
Sure. 
We also launched an Official Discord Server for OVHcloud, feel free to join and discuss about databases :) 
https://discord.gg/KxZd5aSf

**Comment by boagg** [comment]
Hi,
The link is no longer available, normal @baaastijn ?

**Comment by matmicro** [comment]
For Postgresql, do you confirm that, as a user i can have :
- CREATE and DROP DATABASE privileges
- Read queries are dispatched on all readonly nodes
- Write queries are sent to the read-write master node
- vertical expansion (changing flavor) is transparent and can be done like a rollingUpdate strategy
- horizontal expansion (scale up/down) is automated and can be configured from UI (min node, max nodes)

**Comment by baaastijn** [comment]
> Hi,
> The link is no longer available, normal @baaastijn ?

link edited, sorry for that

**Comment by baaastijn** [comment]
> For Postgresql, do you confirm that, as a user i can have :
> 
>     * CREATE and DROP DATABASE privileges
> 
>     * Read queries are dispatched on all readonly nodes
> 
>     * Write queries are sent to the read-write master node
> 
>     * vertical expansion (changing flavor) is transparent and can be done like a rollingUpdate strategy
> 
>     * horizontal expansion (scale up/down) is automated and can be configured from UI (min node, max nodes)

We are teaming up with Aiven.io as a technology partner to provide you these new engines.

Most of the feautres you can fin in their offers, will be available for you at OVHcloud so :
- Create/Drop privilege : yes. more info https://help.aiven.io/en/articles/489557-postgresql-superuser-access
- Read queries dispatched in all the RO-nodes (replicas) : yes. more https://help.aiven.io/en/articles/653410-high-availability-in-aiven-for-postgresql
- Write queries sent to the primay : yes of course :)
- Vertical scaling without downtime : yes. more : https://help.aiven.io/en/articles/2990664-preventing-postgresql-full-disk-issues
- Horizontal expansion (more replicas) : you have to select the amount of nodes via UI/API/Terrafor when you buy the cluster. not defined today about adding more replicas" once the cluster is up. I cannot confirm.

Sorry to point out to the Aiven documentation, ours is on staging so far. but again the managements methodes will be similar.

Hope it's clear enough !

**Comment by erapx** [comment]
Hello,
any ETA for Redis (5?) and MySQL?
Also, is managed Elasticsearch going to be added as well?
Thanks!

**Comment by baaastijn** [comment]
> Hello,
> What about MariaDb please ?

MariaDB is not planned sorry.

**Comment by baaastijn** [comment]
> Hello,
> any ETA for Redis (5?) and MySQL?
> Also, is managed Elasticsearch going to be added as well?
> Thanks!

Hello, we target maximum end of October to add the new DBMS shown below
To simplify the reading of the roadmap, i will close this issue and I created new ones 
- MySQL 8.0 #119 
- PostgreSQL 10 / 11 / 12 / 13 #120 
- Redis 6.2 #121 
- Kafka 2.8 #122 


ElasticSearch, planned but no ETA yet.

**Comment by baaastijn** [comment]
Hello, as said just before, I close this issue and split it into 4 issues :

- MySQL 8.0 #119 
- PostgreSQL 10 / 11 / 12 / 13 #120 
- Redis 6.2 #121 
- Kafka 2.8 #122 

This way I can give your more details about features and planning. Please follow the desired new issues to get the updates. Thanks !
