### ISSUE TITLE
Cloudlinux Images on PCI

### ISSUE THREAD

**Issue by WebDevM4DC** [ovh/public-cloud-roadmap#258]
Hi,

Please consider offering ready to use Cloudlinux images. It would save customers a lot of time from converting servers, and especially now with the Centos "headache" this would be lifesaver.

Over the past 10+ years I installed and converted more than a dozen PCI across several PC Projects, these came with headaches and ups and downs. If I had a ready to use CL image... would have been much better.

I`m very sure many would be happy for this and even more people would use PCI OVH.

https://docs.cloudlinux.com/cloudlinux_installation/#installing-new-servers

Thanks

**Comment by JacquesMrz** [comment]
We are currently validating the image. I hope we'll be able to push it in prod in the coming weeks.

**Comment by JacquesMrz** [comment]
Cloudlinux image is now available (BYOL model)
