### ISSUE TITLE
Upgrade kernel nodes version

### ISSUE THREAD

**Issue by romdum** [ovh/public-cloud-roadmap#259]
As Kubernetes administrator I would like to deploy Gitpod on my managed cluster.

Gitpod require "Either Ubuntu 18.04 with ≥ v5.4 kernel or Ubuntu 20.04 with ≥ v5.4 kernel" like mentionned in this [documentation](https://www.gitpod.io/docs/self-hosted/latest/cluster-set-up#node-and-container-requirements). Nodes deployed on managed kubernetes services are using version 4.15.0 of linux kernel, so we can't deploy Gitpod.

I would be able to upgrade kernel / image on my nodes.

This feature was previously ask on OVH forum [here](https://community.ovh.com/t/mettre-a-jour-version-kernel-de-linux/51461/2) and [here](https://community.ovh.com/t/update-linux-kernel/51431).

**Comment by rverchere** [comment]
+1, it would be great to upgrade to latest LTS Ubuntu version for compute instances.

**Comment by Wats0ns** [comment]
Hello @mhurtrel and happy new year, any ETA on this feature please ?
Thanks a lot !

**Comment by mhurtrel** [comment]
Hello @Wats0ns ! We plan to upgrade the Kernel in February :)

**Comment by frabe1579** [comment]
+1, I'm waiting for kerner upgrade, I want to try [Caretta](https://github.com/groundcover-com/caretta), and it requires nodes with 4.16+ kernel version.
Thank you!

**Comment by mhurtrel** [comment]
Hello ! Any new node created is now deployed with 5.4 linux kernel. Users can also force a patch update to their Kubernetes cluster to totigger a rolling upgrade of all nodes of their existing cluster to benefit from New kernel version.
