### ISSUE TITLE
Ray.io on demand service

### ISSUE THREAD

**Issue by cyrta** [ovh/public-cloud-roadmap#275]
# Ray.io on demand service 

It is possible to use kubernetes + terraform 
https://docs.ray.io/en/latest/cluster/cloud.html#cluster-cloud

However, I believe it would be valueble to make deployment easier, by just one call or button click

Rferences:

See this blog post for a [step by step guide](https://medium.com/distributed-computing-with-ray/a-step-by-step-guide-to-scaling-your-first-python-application-in-the-cloud-8761fe331ef1) to using the Ray Cluster Launcher.

To learn about deploying Ray on an existing Kubernetes cluster, refer to the guide [here](https://docs.ray.io/en/latest/cluster/kubernetes.html#ray-k8s-deploy).

It is very easy to prepare massive, large dataset for AI model training
https://speakerdeck.com/anyscale/ray-datasets-scalable-data-preprocessing-for-distributed-ml

**Comment by mhurtrel** [comment]
Thanks for the input @cyrta

As we have no other demand for this, and multiple solutions for ML at OVHcloud, we do not plan to work on this.
However, you are more than welcome to offer our Kubernetes user a documentation to deploy Ray on our managed services.

We have multiple partners that have done so like [CloudCasa](https://docs.ovh.com/gb/en/kubernetes/backup-and-restore-cluster-using-cloudcasa/) or https://docs.ovh.com/gb/en/kubernetes/backing-up-cluster-with-velero/ .
