### ISSUE TITLE
K8s Loadbalancer flavor

### ISSUE THREAD

**Issue by matmicro** [ovh/public-cloud-roadmap#285]
As a Managed Kubernetes Services user i would like to be able to configure my K8s loadbalancer flavor.

By default it seems that LB are limited to 2000 requests/s
And this seems to be the only one flavor available with no ability to changed it.

From kubectl usage and .yml files, i would like to be able to configure my Loadbalancer flavor (S, M, L, XL).
I would like to be able to change it live without service disruption (no IP change).

Is it something possible/planned ?

**Comment by gchicoye** [comment]
Agree, it's a really clear limitation currently!

**Comment by matmicro** [comment]
Can we have an update on this ?

**Comment by mhurtrel** [comment]
Hello @matmicro @gchicoye I confirm we will support new load balancer (based on Octavia) diffrent plans when we will be able to implement them in Managed Kubernetes CCM. This is definitely in the plans, we currently target Spring but I cannot give a more precise ETA yet, as we are wainting for our LBaaS colleagues to finalize native support for all our usecases (inclusing public to public and public to private LB cases)

**Comment by dm-jnpstr** [comment]
Any updates?Really needed in DE1

**Comment by mhurtrel** [comment]
Hello @dm-jnpstr and other contributors and watchers of this issue.
LBaaS based on Octavia development is still being developped by our colleagues to support all use cases. 
I confirm again that managing the different "flavors" and capacbility to change the flavor of an existing LB is planned.

I edited the octavia integration issue to relfct this a while ago.
I am closing this one for clarity, please now watch this issue : https://github.com/ovh/public-cloud-roadmap/issues/104
