### ISSUE TITLE
Custom disk types at database creation

### ISSUE THREAD

**Issue by thild42** [ovh/public-cloud-roadmap#289]
## User story
As a customer,
I want the best disk type chosen for me during the database instance creation
so that
I benefit from the best performances for my database settings.

## Acceptance criteria
Based on geographical availabilities and the storage capacity:
- The local SSD disk is automatically selected when creating a database (MongoDB only)
- The first generation of remote disk is automatically selected when creating a database (not for MongoDB)
- The second generation of remote disk is automatically selected when creating a database

## Scope
First generation of remote disk is available for all engines on all regions but won't be available for MongoDB instances.
Second generation of remote disk is available for all engines on all European regions by the end of 2022 and everywhere in the course of 2023 (dates are subject to change).
The following countries are out of scope for ordering:  OVH US.

## Follow, vote and give your feedback
You can follow this task with the notification on the right tab.
Ask us anything here in the comments below, and vote with emojis for most requested items !
👍 to vote for this issue

## Discuss on Discord
Feel free to discuss with us on  https://discord.gg/ovhcloud

**Comment by baaastijn** [comment]
hello, for info we prioritized this feature for the next release.

**Comment by thild42** [comment]
Good news ! The feature is being developed but the scope changed a little.
During the refinement of the feature we realised that letting customers select the disk type themselves was unwise as it could lead to situation where another disk type could have been selected to grant better performances.
These troublesome situations could easily be avoided by automatically choosing the most suitable disk type depending on the amount of storage of the database and the geographical availabilities of disk types (first and second generation of remote disks).

**Comment by notz** [comment]
@thild42 In the meantime mongodb databases are also using remote disks, so they should also profit from gen2 disks. Is there any ETA? I expect any database to use gen2 (if available) or are there any configurations where the old generation is faster?

**Comment by thild42** [comment]
@notz Yes, I will update the content of this feature to reflect the situation for MongoDB.

As we speak, MongoDB services are being migrated progressively from SSD Local to gen1 remote disks. Newly ordered services are already on gen1 remote disks.

When all services will have been migrated on remote disks, by the end of next week if all goes well, we will then begin to migrate them on gen2 disks.
