### ISSUE TITLE
Public cloud vps: monitoring cpu/disk/mem/net usage

### ISSUE THREAD

**Issue by biapar** [ovh/public-cloud-roadmap#291]
Public cloud vps: monitoring cpu/disk/mem/net usage with history.

**Comment by JacquesMrz** [comment]
Observability feature is being developped and will be available for VPS and Public Cloud in the future.
Meanwhile, we have no OVHcloud based technical answer to provide.

**Comment by biapar** [comment]
When? It's not possible to use OVH cloud without a monitoring instruments, workflow, instance replica or a restore a backup into another zone for DR.

**Comment by biapar** [comment]
News?
