### ISSUE TITLE
Public Cloud Database: Microsoft SQL Server

### ISSUE THREAD

**Issue by biapar** [ovh/public-cloud-roadmap#294]
Public Cloud Database: Microsoft SQL Server

**Comment by thild42** [comment]
Hello @biapar and thank you for your input.

The support for Microsoft SQL Server is currently not planned, and I can safely say that it won't be anytime soon as OVHcloud efforts are currently focused on supporting open source databases.

If you are committed to move to (OVH)cloud and look to gain a competitive edge, with our managed databases, your best bet would be to migrate to PostgreSQL. Comprehensive guides are available on [OVHcloud Public Cloud website](https://www.ovhcloud.com/it/public-cloud/postgresql/) to help you undertake such a migration.

**Comment by biapar** [comment]
Thanks for your reply. We are trying your cloud services. Why PostgreSQL and not MySQL/MariaDB?

**Comment by thild42** [comment]
Migrating to PostgreSQL or MySQL/MariaDB should be based on how you are currently using MSSQL and on which feature you rely most. Mentioning PostgreSQL is more out of force of habit as the engine has been gaining a lot of traction in the last years and we see a trend in migration to Postgres.

**Comment by baaastijn** [comment]
Also

You Can find wonderful open Source tools to migrate from SQL server to
PostgreSQL, like this one :
https://nuvalence.io/insights/microsoft-sql-server-to-postgresql-migration-using-sqlserver2pgsql/

**Comment by biapar** [comment]
So or I've to use SQL on Azure/AWS or I've to install myself on Linux/Windows Instance.
