### ISSUE TITLE
[OVH API] Trigger manual public-cloud instance backup

### ISSUE THREAD

**Issue by Aiden-RC** [ovh/public-cloud-roadmap#302]
This feature is exposed / available via the manager UI however isn't yet available for the ovh API, 
it would be useful if this could added as the ground work for it has already been completed.

Possible use cases:
  trigger manual backup before auto deployment
  in-house multi server / multi platform backup management software

Thanks :)

**Comment by JacquesMrz** [comment]
If you want to trigger the snapshot of a Public Cloud instance via OVH API:
https://api.ovh.com/console/#/cloud/project/%7BserviceName%7D/instance/%7BinstanceId%7D/snapshot~POST

Hope it answers.
