### ISSUE TITLE
Postgres pool on * databases

### ISSUE THREAD

**Issue by matmicro** [ovh/public-cloud-roadmap#303]
As a pgbouncer user i would like to be able to specify "*" (any) database connection on my pool.

So i need to connect to a pool (on port 20185) without specifying the database name.
this is something possible with pgbouncer with such syntax :

```* = host=postgresql-132456789.database.cloud.ovh.net port=20184```

I would like to be able to do such configuration on my Managed Postgres Database from OVH UI Manager.

**Comment by matmicro** [comment]
@baaastijn , is there a chance to quickly implement this ?
It just needs to allow setting "*" database name (source and dest) for Managed Postgres DB on pgbouncer config for pool management. 
Its currently a big limitation to not having this.

**Comment by baaastijn** [comment]
Hello @matmicro , we priorize our features based on customer request and we are currently working on :
- storage improvements (more flexibility, more performance)
- private netowrk for essentials offers
- better overall experience (troubleshooter helpers and co)

For this specific demand it's an isolated request so far, that we are not considering for now. 
I hope that you understand !
