### ISSUE TITLE
Provide a  better authentication method for Kubernetes clusters with autoscaling

### ISSUE THREAD

**Issue by baaastijn** [ovh/public-cloud-roadmap#305]
**Last update for user story : january 2023**

## Context ##
Many of our customers have K8s clusters. Cluster have nodes who vary over time. Amount and IPs. It’s really boring to add each ip manually for ACL. We Need to find an easier way (long term : having an IAM)

## User story ##

As a customer
I want a smart way to authorize a whole Kubernetes cluster to access one or multiple DB cluster, with autoscaling into account
So that
When I have new nodes, I don’t need to authorize them IP by IP

Scope : All DBMS

## Acceptance criterias ##

- mandatory : adding or removing nodes in a K8S cluster is taken into authorization access
- mandatory : a K8S cluster can be authorized for multiple DbaaS.
- mandatory : a DBaaS can be authorized for multiple K8s
- mandatory : works with any K8s cluster, inside of outside OVHcloud, in public network or private network.
- mandatory : work with cluster and k8s from different goegraphical locations
- accepted limitation  : authorization can be done via "code", not via API/CLI or even UI

## Found solution ##

OVHcloud will develop a Kubernetes operator, allowing any K8s cluster to interact with our databases IP authorization token.
Later (no ETA), once an IAM will be available, we will also provide IAM-based auth, cross service mode.

## Follow, Vote and give your Feedback ##
You can follow this task with the notification on the right tab.
Ask us anything here in the comments below, and vote with emojis for most requested items !
👍 to vote for this issue

## Discuss on Discord ## 
Feel free to discuss with us on  https://discord.gg/ovhcloud

**Comment by annismckenzie** [comment]
Chiming in here because I came across it while evaluating managed DBaaS offerings in Europe, specifically Cassandra and/or ScyllaDB. Wouldn't providing a TLS client certificate already improve security by a lot? At least for me that would be more beneficial than authorizing IPs. Even better would be if I were allowed to provide my own TLS client certificate when provisioning via Terraform.

**Comment by baaastijn** [comment]
> 

hello, sorry for late reply. We enforce TLS by default for all our dbms already.

**Comment by annismckenzie** [comment]
> > 
> 
> hello, sorry for late reply. We enforce TLS by default for all our dbms already.

Did I miss something in the documentation? I specifically asked for client certificates, not server certificates. Can you reread my comment and double-check that you didn't misunderstand? If you already support client certificates then that'd be so awesome!

**Comment by baaastijn** [comment]
Hello ! Issue update, we will develop a K8s operator during this quarter.

**Comment by baaastijn** [comment]
hello, the operator is developed, and documentation is in proofreading.
You can follow the proofread here : https://github.com/ovh/docs/pull/4379
