### ISSUE TITLE
Add Rocky Linux / AlmaLinux 9 images

### ISSUE THREAD

**Issue by karljohns0n** [ovh/public-cloud-roadmap#306]
Please consider adding Rocky Linux / AlmaLinux 9 images. RHEL 9 has been out for a while, see;

https://access.redhat.com/articles/3078

Thanks!

**Comment by JacquesMrz** [comment]
![image](https://user-images.githubusercontent.com/73828583/197176447-a7607bc6-e00a-4e5f-8af8-be0444b57de2.png)
Rocky Linux / Alma Linux are now part of the image catalog.

**Comment by karljohns0n** [comment]
Hello @JacquesMrz,

Any reason why these image have a different partition schema (3 partions, boot, EFI and /), while the other such as Alma/Rocky 8 and Ubuntu have only one partition, everything in / ?

Thanks,
