### ISSUE TITLE
Database MongoDB 6.0

### ISSUE THREAD

**Issue by kmlwlkwk** [ovh/public-cloud-roadmap#309]
As a user I would like to have possibility to create cluster on latest stable version of MongoDB.

AC:
- user can deploy cluster on MongoDB 6.0

More info about releases: https://www.mongodb.com/docs/manual/release-notes/

**Comment by thild42** [comment]
Good news @kmlwlkwk ! We are currently working on the release of MongoDB 6.0.
No strict ETA yet but I could say it should be available fairly soon.

**Comment by thild42** [comment]
Good news, it is done !
MongoDB 6.0 is now available.
