### ISSUE TITLE
Disk usage for databases on the list

### ISSUE THREAD

**Issue by kmlwlkwk** [ovh/public-cloud-roadmap#312]
As an admin who is responsible for managing our infrastructure I would like to have an overview of used resources od database clusters directly on the list. This will improve maintenance by a lot.

AC:
- on the databases list I can see percentage of used disk

NTC:
- nice to have: current IOPS
- nice to have: current RAM usage
- nice to have: current CPU usage

**Comment by thild42** [comment]
Hello @kmlwlkwk and thank you for your feedback. I will try to reformulate, to be sure that I understand what you would like to see.

The idea would be to have either the resources directly displayed on the database list or a dedicated view dedicated to the resources consumed by your clusters. Am I right ?

**Comment by kmlwlkwk** [comment]
Thank you for quick response. My idea is to display resources directly on the database list.

**Comment by F-Legrand** [comment]
Delivered with https://github.com/orgs/ovh/projects/16/views/1?sliceBy%5Bvalue%5D=Managed+Databases&pane=issue&itemId=81318874&issue=ovh%7Cpublic-cloud-roadmap%7C607
