### ISSUE TITLE
Postgres 15

### ISSUE THREAD

**Issue by matmicro** [ovh/public-cloud-roadmap#313]
Can we have an ETA for postgresql 15 available for Managed DB ?

**Comment by baaastijn** [comment]
Hello, good question indeed. =No ETA so far but usually we try to provides them quite quickly after release.
We will move this request to "priorized" when we will be able to provide an ETA.

have a good day !

**Comment by thild42** [comment]
PostgreSQL 15 was made available internally for testing purpose.
If everything goes well the version should be released in production from a few days to a couple of weeks.

**Comment by thild42** [comment]
PostgreSQL is available in production.

**Comment by matmicro** [comment]
Hi @thild42 
I have migrated my DB to v15 and i am facing below issue :
`psycopg2.OperationalError: connection to server at "postgresql-xxxxx.database.cloud.ovh.net" (xx.xx.xx.xx), port 20185 failed: FATAL:  pgbouncer cannot connect to server - - -`

Do you have an idea of the issue ? All was working fine in postgres 14.

**Comment by thild42** [comment]
Hi @matmicro !

The first idea that came out would be to check the IP authorization that you may have on your database client infrastructure (k8s?) as the migration let the cluster to respawn with a new address.
