### ISSUE TITLE
Host a static web site inside a bucket

### ISSUE THREAD

**Issue by lason-ovh** [ovh/public-cloud-roadmap#316]
Static websites can be hosted in OVH object storage in the same manner as in AWS S3.
Typically static websites content (html pages, css, scripts, images, ...etc) can be uploaded in a bucket and served to visitors.

/!\reminder: a static website is a website that does NOT require serverside processing.

What we provide:
- an S3 compatible REST API to upload, download, delete a configuration file (in json or xml format) that tells S3 how to serve your web site

The following configuration elements will be supported:
- homepage definition
- error page definition
- redirection & routing rules inside the website

The following configuration elements will not be supported as it is out of the scope of the object storage offer:
- cname mapping & DNS configuration (for example, if you have a domain name and you want that domain name to point to your static website hosted inside a bucket)

**Comment by biapar** [comment]
News?

**Comment by lason-ovh** [comment]
> News?

Our network and CDN product teams are currently working hard on it as we have the ambition to deliver to our clients a user experience similar to Cloudfront.
We will keep you updated as soon as possible ;)

**Comment by lason-ovh** [comment]
on it, documentation will be released very soon
