### ISSUE TITLE
S3 Server access logging

### ISSUE THREAD

**Issue by lason-ovh** [ovh/public-cloud-roadmap#318]
Server access logging provides detailed records for the requests that are made to a bucket. It helps you to track who accessed what objects in what buckets and when.

In practice, access logs to a bucket will be written in a target bucket of your choice and you will be able to determine permissions to that target bucket: all of that will be defined via a configuration file that you provide.

This feature enables more advanced use cases to visualize and monitor bucket accesses via OVH log data platform.

What will be provided is an S3 compatible REST API that enables our customers to upload, delete the server access logging configuration file.

The following functionalities will be supported:
- define target bucket
- define target permissions

The following configuration elements will not be supported :
- log format: a fixed predefined log format will be used

**Comment by MircoT** [comment]
Hi, there is any ETA on the final release of this API? Is it already available in `v1` or `v2`?
