### ISSUE TITLE
Healthcare HDS 1 conformity

### ISSUE THREAD

**Issue by baaastijn** [ovh/public-cloud-roadmap#33]
As a OVHcloud public cloud user
I want all my services (Compute, Data, Containers, Storage, ...) to be HDS 1 compliant
so that I can host healthcare services on Public cloud with official approval

Note :
We currently target a public-cloud-wide certification

**Comment by mhurtrel** [comment]
The capability to add HDS conformity to a public cloud project should be offered late March.

**Comment by mhurtrel** [comment]
The HDS compliant Public cloud projects should be made available within a week.

**Comment by mhurtrel** [comment]
The teams in charge of the otion management had some delay and now announce a launch next week

**Comment by mhurtrel** [comment]
The feature is now in production. 
You can both activate this as project creation or for existing project, in the "project settings" area.

![image](https://user-images.githubusercontent.com/24432524/114403032-b6dfe380-9ba4-11eb-9a6a-5c9865e4dc9e.png)

More information can be found here : https://www.ovhcloud.com/en-ie/enterprise/certification-conformity/hds/
