### ISSUE TITLE
Access control lists for Cloud Archives

### ISSUE THREAD

**Issue by khaledavarteq** [ovh/public-cloud-roadmap#336]
I'd like to suggest adding ACLs to Cloud Archives similar to the way [Object Storage containers support ACLs](https://docs.openstack.org/swift/latest/overview_acl.html). One should be able to give individual users access to certain Cloud Archives while other users do not get permission to access this particular Cloud Archive.

**Comment by Izaia64** [comment]
We don't plan additional feature for Cloud archive class of storage, deprecated class of storage based on Swift Api. 


For you use cases, i will suggest to go to the new product line that offer larger compatibility with S3 api and more features, included bucket ACL
- back up use case : class of storage Object Storage Standard - S3 api (7Eu/TB-m)
- archive use case : class of storage Cold Archive (1,3Eu/TB-m)

Cold Archive will be in beta test available on the manager next week.
