### ISSUE TITLE
Terraform - Public Gateway for kubernetes cluster

### ISSUE THREAD

**Issue by psalkowski** [ovh/public-cloud-roadmap#337]
I can't find any resource in terraform that will let us order public Gateway for vRack: https://www.ovhcloud.com/pl/public-cloud/gateway/

Currently I think we need to order it manually and assign to newly created kubernetes cluster, but it would be nice if terraform will support it.

**Comment by yomovh** [comment]
hello @psalkowski 

Did you try using the [networking_router_v2](https://registry.terraform.io/providers/terraform-provider-openstack/openstack/latest/docs/resources/networking_router_v2) from the openstack tf provider 
You can find an example of router resource used as gateway in that example : https://github.com/ovh/public-cloud-examples/tree/main/networking/private-network-mono-region

**Comment by psalkowski** [comment]
I tried similar setup, but `openstack_networking_network_v2` throw an exception with Policy error. My user have all rights but still, I wasn't able to go this way.

**Comment by leonidstakhovsky** [comment]
@yomovh hi
do you have a working example for creating a Gateway with terraform?
I can't understand where get `external_network_id`?

**Comment by yomovh** [comment]
Hello,

You can have a look at that [example](https://github.com/yomovh/tf-at-ovhcloud/tree/main/simple_http_lb) that does more than gateway
