### ISSUE TITLE
Grafana engine support in ovh Terraform provider

### ISSUE THREAD

**Issue by yomovh** [ovh/public-cloud-roadmap#338]
## User story
As a customer,
I want to be able to automate the management of a grafana database using terraform tool
so that
I do not have to create all my grafana databases for all my environment manually in the [manager](https://www.ovh.com/manager/) that is error prone and can lead to configuration drift

## Acceptance criteria
All the configuration items that can be done in the [manager](https://www.ovh.com/manager/) can also be done through terraform

## Scope
Public Cloud Databases for Grafana

## Follow, vote and give your feedback
You can follow this task with the notification on the right tab.
Ask us anything here in the comments below, and vote with emojis for most requested items !
👍 to vote for this issue

## Discuss on Discord
Feel free to discuss with us on  https://discord.gg/ovhcloud **

**Comment by thild42** [comment]
To be precise, you could currently create a Grafana service with Terraform.
What is laking is the support for the user credentials reset.
We are working on it and it should be released pretty soon.
