### ISSUE TITLE
Terraform - private network subnet routes

### ISSUE THREAD

**Issue by jon4hz** [ovh/public-cloud-roadmap#339]
It would be nice if you could create routes for private network subnets using the ovh terraform provider.

**Comment by yomovh** [comment]
@jon4hz

Thanks for the issue. 
do you know that you can do it with the openstack provider in OVH ?

The following documentation can help :
- This [guide](https://docs.ovh.com/ie/en/api/terraform-at-ovhcloud/#introduction) explains the different providers you can use. 
- This other [guide](https://docs.ovh.com/ie/en/public-cloud/how-to-use-terraform/)  explains how to create an instance & network with openstack provider.

**Comment by jon4hz** [comment]
Hi, no I wasn't aware that I can do that with the openstack provider. Thanks for the hint!
