### ISSUE TITLE
Open http port on k8s Load balancer - port 9100 - Security issue

### ISSUE THREAD

**Issue by nantoniazzi** [ovh/public-cloud-roadmap#342]
All load balancers in front of the Kubernetes service seem to open port 9100 and the URL /metrics

It's a security issue because some subdomains associated with our company domain are linked to those load balancers.
Example:  http://135.125.85.99:9100/metrics 

There are many security agencies that give a grade to companies/domains and they decrease our notation because of this (open insecure port 9100 with metrics publicly exposed)

Is there a way to disable it? Can you protect it with an auth mechanism or at least expose it on HTTPS? Because it has a bad impact on us and the reputation of our company

**Comment by ToMs77130** [comment]
This is related to prometheus node-exporter which exposes public IP with web.listen-address parameter, it shouldn't be publicly accessible.
You can moderate it with enabling firewall on your nodes, and adding a rule which deny all traffic on port 9100 (it does not seems to block prometheus metrics scrapping)

**Comment by Lucasgranet** [comment]
Hello,

We released in our production environments the patch for all customers.
The port 9100 is now allocatable.

To benefit the fix right now, you have to trigger a new configuration on the LoadBalancer, e.g.:
- add a node in your MKS cluster to trigger the update. (after the node is Ready, you can revert the change if needed)
- remove a node in your MKS cluster to trigger the update.
- expose a new port via the LoadBalancer service. (wait one minute before revert it)

Lucas,
From MKS Team
