### ISSUE TITLE
Define authorised IP at database creation

### ISSUE THREAD

**Issue by thild42** [ovh/public-cloud-roadmap#344]
## User Story ##

As a customer
I want to define a set of authorised IP address or CIDR blocks when ordering a new database
So that
I can manage my authorised IP in a single step and do not have to wait for my service to be up and running to configure these addresses.

## Acceptance criterias ##

- Can be done through UI
- Can be done with API/CLI
- Can be done with Terraform
- Can specify multiple IP addresses or CIDR blocks
- Can still manage authorised IP after database creation

## Vote and Feedback ##
Ask us anything here in the comments below, and  vote with emojis !
👍 to vote for this issue

## Discuss on Discord ## 
Feel free to discuss with us on https://discord.com/invite/PwPqWUpN8G

**Comment by kmlwlkwk** [comment]
Would be super helpful to have a predefined list of IPs (based on current instances) and whitelist them with one click

**Comment by thild42** [comment]
We need to check the feasibility first but that is a good idea.
We are already digging into the way to auto whitelist IP from managed kubernetes clusters, so that also make sense to provide a way to ease integration to VM as well.
Thanks for your feedback.

**Comment by thild42** [comment]
Quick update, that seems to be feasible.
Let's see how to do it properly.

**Comment by thild42** [comment]
A short update to this issue as you could whitelist IP address at service creation through the API or Terraform.
The UI will follow shortly.
