### ISSUE TITLE
Managed Database Fork on smaller flavor

### ISSUE THREAD

**Issue by matmicro** [ovh/public-cloud-roadmap#349]
As a Managed Database (postgres) user
I would like to be able to fork a database and use the appropriate flavor based on the real database size.

Currently we can't fork a database to a smaller flavor than the actual instance.

For example, i am running a  really small database size, but on flavor DB1-120, because of CPU and network bandwith needs.
I would like to be able to fork that DB on a new DB1-4 if space required is enough.

**Comment by thild42** [comment]
Hello @matmicro.

Good news is we want this to be feasible and are working on the first steps of this feature as part of PITR (#334) where we are redesigning the fork process to be more straightforward.

The second step will be to work out how to be implement clever rules to enable the fork downscale. As you mentioned it, the major constraint is to let users downscale only if the targeted flavor have enough storage capacity. The release of Flex Disks (#143) will make fork downscaling even more relevant and natural.

The rule of thumb we currently have is that the targeted instance needs to have enough storage to restore the backup (compressed backup size + 20%). However with PITR, we have an initial backup plus delta files (WAL, binlog, or oplog) that makes it harder to estimate what should be the total capacity required to restore.

As a summary, first we release the Flex Disks (by the end of January 2023), then we release the PITR (by the end of March 2023, hopefully sooner, we'll see), and finally we implement a robust implementation of the downscale fork.
