### ISSUE TITLE
Add support for HTTPS in S3 hosted static websites

### ISSUE THREAD

**Issue by lason-ovh** [ovh/public-cloud-roadmap#351]
Currently, OVH Object Strorage S3 website endpoints do not support HTTPS. However nowadays, HTTPS is a MUST in terms of security on the internet and is considered a basic feature of any website.

The objective is to enable the use of encrypted and secure connections via HTTPS by managing and serving 3rd party certificates.

The scope of this feature will be focused on static web sites hosted in OVH Object Storage S3 buckets.

**Comment by loliee** [comment]
Also waiting for this feature !

**Comment by lason-ovh** [comment]
this feature has been released and is now avaialble. check the documentation [here ](https://help.ovhcloud.com/csm/en-public-cloud-storage-s3-static-website-https?id=kb_article_view&sysparm_article=KB0058074)
