### ISSUE TITLE
Object Storage Standard - S3 API - New DC in LIM

### ISSUE THREAD

**Issue by Izaia64** [ovh/public-cloud-roadmap#355]
We continue to expand our Object Storage Standard class with new endpoint
Follow the geo-availability here : https://docs.ovh.com/ie/en/storage/object-storage/s3/location/
Next DC to be opened is in Germany with LIM

**Comment by frabe1579** [comment]
Is this referred to DE/DE1 or it is a completely new/separate DC?
I ask this because I have a Kubernetes cluster in DE, but i cannot use Standard Object Storage with S3 API.
