### ISSUE TITLE
Notification when a new Kubernetes version is available

### ISSUE THREAD

**Issue by rverchere** [ovh/public-cloud-roadmap#360]
Hello,

Today, I need to check regularly on the manager if a k8 supgrade is available (major or security upgrade).
I can also get some info by pulling the OVH API (with isUpToDate field).
Note that  I do not use the automatic upgrade as I need to plan my upgrades.

It would be nice to have some option on the manager to subscribe on avaliable updates, and receive these informations (push model, maybe by e-mail or other protocols).

**Comment by LisaPerrier** [comment]
Hello @rverchere, 
For major upgrades such as v1.26 coming soon, this will inform you for every release due and available : https://public-cloud.status-ovhcloud.com/
We will also start announcing such events on Discord : https://discord.com/channels/850031577277792286/955385102945370122 
Also, you can subscribe to this issue on the roadmap and receive notifications whenever an update is made: https://github.com/ovh/public-cloud-roadmap/issues/300

**Comment by rverchere** [comment]
Hi @LisaPerrier,

Ok. Note that it would be great to have some estimated EOL dates [here](https://docs.ovh.com/sg/en/kubernetes/kubernetes-plugins-software-versions-reserved-resources/#kubernetes-versions) or [here](https://docs.ovh.com/sg/en/kubernetes/eos-eol-policies/) .

**Comment by LisaPerrier** [comment]
Hi @rverchere, we could add the information [here](https://docs.ovh.com/sg/en/kubernetes/kubernetes-plugins-software-versions-reserved-resources/#kubernetes-versions). The other one will remain general though :)
