### ISSUE TITLE
Kubernetes Cluster - specifying a private subnet

### ISSUE THREAD

**Issue by chris-cynation** [ovh/public-cloud-roadmap#361]
When working with terraform I realised that when deploying a kubernetes cluster on a private network I'm not able to select which subnet  to place it in.

This causes issues out of the box when doing terraform destroy as it is unaware of the private subnet usage (without manually using depends_on).

I think it would be good to be able select the private subnet a kubernetes cluster should use.

**Comment by mhurtrel** [comment]
Hello @chris-cynation . I am not sure to get the issue : choosing a specific private subnet is one of the configuration parameter at kubernets cluster creation.

This documentations shows an example using it : https://registry.terraform.io/providers/ovh/ovh/latest/docs/resources/cloud_project_kube

![image](https://user-images.githubusercontent.com/24432524/223715560-849d5c88-9a43-46b2-98c5-d2923465abf3.png)

**Comment by chris-cynation** [comment]
Oh, I think I see it is 
tolist(ovh_cloud_project_network_private.network.regions_attributes[*].openstackid)[0]
selecting the first subnet on the network?

**Comment by mhurtrel** [comment]
Yes indeed

**Comment by chris-cynation** [comment]
Ah, then the improvement would be a way to get that from the output of creating the subnet so terraform can know there's a dependency.

Another aspect it helps with is when you've declared multiple subnets and want a clear link which one it is.

**Comment by LisaPerrier** [comment]
Hello all, 
this has been prioritized on our end and you will soon be able to select the subnet of a given private network on cluster creation/reset.

**Comment by LisaPerrier** [comment]
Hello all,
this has been prioritized on our end and you will soon be able to select the subnet of a given private network on cluster creation/reset.

**Comment by danvy** [comment]
Hi @LisaPerrier 
Any update ?

**Comment by antonin-a** [comment]
Hello @danvy and @sennerholm, I do confirm that it is now possible to define the subnet you want to use for your MKS clusters. This is currently available through APIs and Terraform with 'nodesSubnetID' parameter (https://eu.api.ovh.com/console/#/cloud/project/%7BserviceName%7D/kube~POST).
_This is the OpenStack subnet ID that the cluster nodes will use. This files is Optional, can only be set on cluster creation or reset, can only be set if privateNetworkId is also set. If unspecified, it will be selected automatically when the first node is created._

Note that it will be available using the OVHcloud Manager (webUI) soon. We will also add another optional parameter 'loadbalancerSubnetID' for users who want to have a dedicated subnet for their Public Cloud Load Balancers used alongside MKS.

**Comment by sennerholm** [comment]
We have had some new releases of the provider, but nothing on this yet, any ETA?

**Comment by danvy** [comment]
We missed this issue anniversary 🎂

**Comment by nicolaslacroux** [comment]
We are pleased to inform you that our Managed Kubernetes Service (MKS) now supports subnet management in the OVHcloud Control Panel and the Terraform provider. 
 
It will now be possible to specify a subnet for an MKS cluster for the nodes and Octavia Public Load Balancer (optional for advanced user).

**Comment by nicolaslacroux** [comment]
We are pleased to inform you that our Managed Kubernetes Service (MKS) now supports subnet management in the OVHcloud Control Panel and the Terraform provider.

It will now be possible to specify a subnet for an MKS cluster for the nodes and Octavia Public Load Balancer (optional for advanced user).
