### ISSUE TITLE
Managed GPU worker nodes

### ISSUE THREAD

**Issue by mhurtrel** [ovh/public-cloud-roadmap#37]
As a Managed Kubernetes user
I want to spawn managed GPU worker nodes (instances) in my cluster
so that I have ready to use GPUs for my containerized AI/data processing workloads

Note :
Those nodes will come with a standard opinioated NVidia drivers and kernel version.
The ability to launch GPU and even other customer worker nodes may be enabled sooner with [Self Managed Worker Nodes](https://github.com/mhurtrel/public-cloud-roadmap/issues/20)

**Comment by mhurtrel** [comment]
To accelerate this feature, we are exploring another approach : we would instal the exact same components as any other public cloud instance and leave the freedom to our user to install the nvidia specific components, with a step-by-step documentation (same approach as other major actors on the market). The new target for this feature in February.

**Comment by mhurtrel** [comment]
We are rechallebging this approach because we see very low demand compared to other features.
Our current plan would be to autorized Managed Kubernetes to launch any instance, including GPU, with no specific  drivers installed, and offer some basic documentation on how to self-deploy a container at launch for these dependancy using a deamonset.

Please comment below if that approach would suit you, and some informations about your use case.

**Comment by flying-kestrel** [comment]
Support for this would be really cool, as currently we're discussing options for how to integrate GPU-based ML inference models into our current setup. Setting up a daemonset for drivers seems like a reasonable compromise solution in the near term that would work perfectly OK for us.

**Comment by mhurtrel** [comment]
@flying-kestrel @manicole @rgr and @pcqnt We will offer GPU support based on NVIDIA GPU operator in the coming month :)

**Comment by mhurtrel** [comment]
@flying-kestrel @manicole @rgr and @pcqnt 
The feature is now available in GRA 5, GRA7 and BH5 and GPUs ill be progressively available in other regions !

You can consult  our documentation here : 
https://docs.ovh.com/gb/en/kubernetes/deploying-gpu-application/

**Comment by mhurtrel** [comment]
Some of you may have seen t2 flavors not showing up in some regions where they should be available. We are aware of the issue and will make them available next week. Sorry for the delay.

**Comment by Yayg** [comment]
Hi,

Any idea if GPU workers will be available in RBX-1?

Thanks,
