### ISSUE TITLE
Object Storage - High Performance

### ISSUE THREAD

**Issue by JacquesMrz** [ovh/public-cloud-roadmap#38]
As a user, I want Object Storage coming through and with a wide coverage of S3 standard APIs, with low lantency/lot of IOps.

API call included
Incoming traffic included
Outgoing traffic toward OVHcloud Services included
Billed per GB per month/per GB of outgoing traffic (going out of OVHcloud)

ETA SBG : 21/02 ETA GRA : April 2022

**Comment by cambierr** [comment]
Hi,

I know it's a difficult question but do you have any approximate ETA regarding this feature ? We use a lot of swift (via S3 API) containers to store our images, leading to a lot of "live" calls and current performances are too unstable for us to keep using OVH's Object Storage services for such a load (and yes, we already discussed this numerous times with the support, without leading to any solution).

Maybe an early access/beta version available soon so that we can validate and do the switch as soon as the product goes GA ?

**Comment by sbarnoud** [comment]
Any news on that topic? It make now a while that we expected a solution, and nothing seems to be announced ...

**Comment by cambierr** [comment]
Any news here ? The current service offer (both via Swift or S3) is more and more becoming unusable for live workload... This is becoming nothing more than a place for backups... 

At this point, without clear vision, we'll have to consider an external service... which is really against what we try to build with OVH.

Ping @JacquesMrz @mhurtrel

**Comment by tanandy** [comment]
Cc @chibenwa

**Comment by chibenwa** [comment]
Yes I noticed some spikes to 20-40 seconds under load for even small objects...

**Comment by cambierr** [comment]
Yes exact same pattern for us (storing media images for tens of thousands of movies) - each of those spikes generates impacts on our QoS / QoEx

**Comment by d19dotca** [comment]
Agreed, Object Storage performance is really poor with OVH in my experience too. As a test (since I hadn't used many Object Storage services prior) I moved to using Vultr's Object Storage and received three to four times the performance that I ever got with OVH Object Storage, but their Object Storage is only in one region which is a huge limitation when it comes to data sovereignty. This leads me to really desire OVH to improve the performance of Object Storage because right now it's too slow and too unreliable - but thankfully it has the advantage of existing in all regions which I really need in my use-case to keep the data in Canada for example. I hope OVH improves the performance of Object Storage significantly soon.

**Comment by JacquesMrz** [comment]
Hi all,
Our High Performance Object Storage service is officially in BETA !
All the information you want to know about this BETA and how to get access to it, available here https://labs.ovh.com/high-perf-object-storage .

**Comment by Izaia64** [comment]
ETA SBG : end of January. ETA GRA : Q1 2022

**Comment by TheBeardedRaspberry** [comment]
Hello, quick question !

In the new price list, it is stated that _Outgoing Internal traffic_ is _Included_. How is something "Internal" or "External" defined ?
Is Internal traffic just data that transits inside OVH Network ? Does traffic from High Perf Object Storage to So You Start servers count as internal or external traffic ? So you start servers are technically internal to OVH Network, but external to OVH right ?

Thanks a lot !

**Comment by cambierr** [comment]
@Izaia64 any news about GA ?

**Comment by Izaia64** [comment]
> Hello, quick question !
> 
> In the new price list, it is stated that _Outgoing Internal traffic_ is _Included_. How is something "Internal" or "External" defined ? Is Internal traffic just data that transits inside OVH Network ? Does traffic from High Perf Object Storage to So You Start servers count as internal or external traffic ? So you start servers are technically internal to OVH Network, but external to OVH right ?
> 
> Thanks a lot !

hello Right. Internal outgoing traffic is from OVHcloud object storage to a OVHcloud servers (VPS, instance, VMS hosted on bare metal, Soyoustarts servers...)

**Comment by Lebvanih** [comment]
Hello,

I did some testing this morning on the SBG region, and I am bit confused regarding the Bucket access policy.

From my understanding from here: https://docs.ovh.com/fr/storage/s3/debuter-avec-s3/
- I can add a bucket via S3 cli (done) or via UI (also tried)
- Then via the UI or via OVH API I need to link a user.

However, I do not see any process to see/alter who has access to the bucket. 
- Via CLI I get this (An error occurred (NotImplemented) when calling the GetBucketPolicy operation: The requested resource is not implemented). 
- The UI don't show up any options
- There is no API Call for it.

I know that for the swift container (or the S3 layer on top of it) this was the same via API and UI. However, the swift cli allowed us to alter the permission with commands similar to this ones:
- See the bucket policies/info `swift stat my-bucket`
- Alter the policies `swift post my-bucket -w read-policy-name -r write-policy-name`

Am I missing something or is this not supported or an oversight for the High perf S3.

**Comment by erkanImperiatec** [comment]
Hello @Lebvanih, have you found a solution for this ? I am currently facing the same problem, personnaly, the error I am facing is 
`botocore.exceptions.ClientError: An error occurred (403) when calling the HeadObject operation: Forbidden`
used with Django-Rest-Framework (Django-> Python) and its remote storage library: django-storages with aws S3 api

**Comment by cambierr** [comment]
@JacquesMrz any plan to make this available in BHS ?

**Comment by Izaia64** [comment]
@cambierr Object Storage S3 High Performance is planned is BHS soon (August 22)

**Comment by cambierr** [comment]
Great! Thanks !

Sent from a typical smartphone. If this is illiterate, it’s the voice recognition’s fault.
________________________________

**Comment by nik736** [comment]
When will this be available in Limburg?

**Comment by Izaia64** [comment]
Object Storage High Performance -S3 API is not planned this year in LIM . It is available in SBG/GRA/BHS
Object Storage Standard - S3 API is available in GRA, soon in RBX, than SBG/BHS, and LIM/ERI/WAW (Jan/ February)

**Comment by lepinsk** [comment]
@Izaia64 I see that there's no "Outgoing Internal traffic" pricing for Object Storage (Swift) in BHS — does that mean I'll be charged for outgoing traffic to a VPS in BHS even though it's internal to the data centre? I was told by a sales contact that that wouldn't be the case.

**Comment by lepinsk** [comment]
# Openstack Swift/S3 API

It seems like new versions of Swift may support *both* the S3 and Swift API? [More in this search](https://www.google.com/search?q=openstack+swift+s3+api&rlz=1C5CHFA_enCA1017CA1017&oq=openstack+swift+s3+api&gs_lcrp=EgZjaHJvbWUyBggAEEUYOdIBCDI5MDlqMGo3qAIAsAIA&sourceid=chrome&ie=UTF-8)

I'm unsure if OVH would allow us to access our existing Swift stuff *through* the S3 API? If so, this would be insanely good (and we could use Super Slurper?!).

**Comment by lepinsk** [comment]
<img width="706" alt="Screenshot 2023-07-05 at 5 05 00 PM" src="https://github.com/ovh/public-cloud-roadmap/assets/154543/6213dcdb-7e6c-4fa5-b9f0-6cd89c538e85">

yeah what does this mean?! [from here](https://help.ovhcloud.com/csm/en-ca-public-cloud-storage-s3-choosing-right-storage-class?id=kb_article_view&sysparm_article=KB0047283)

**Comment by lepinsk** [comment]
<img width="730" alt="Screenshot 2023-07-05 at 5 05 46 PM" src="https://github.com/ovh/public-cloud-roadmap/assets/154543/308ca6c5-98ad-45bc-9987-3e473b929658">

**Comment by lepinsk** [comment]
Okay, so [according to this](https://help.ovhcloud.com/csm/en-gb-public-cloud-storage-pcs-getting-started-swift-s3-api?id=kb_article_view&sysparm_article=KB0047146) to get S3 credentials for a Swift instance (I think?) you need to connect in and generate ec2 credentials, which will be functional for doing S3 auth against our stuff.

I'm still not 100% sure this'll work but we might as well try.

**Comment by lepinsk** [comment]
@cambierr Thanks for the info — I appreciate it. 🙂 

Do you happen to know: OVH claims that "outgoing internal traffic" from object storage is free:

<img width="812" alt="Screenshot 2023-07-12 at 7 18 31 PM" src="https://github.com/ovh/public-cloud-roadmap/assets/154543/96f001df-50fd-4961-826b-d998c5993945">

However my tests show me being billed for traffic from object storage to an OVH VPS. Do you have any experience with this? I can't seem to get any answers from anyone there about this.
