### ISSUE TITLE
Upgrade to Harbor 2.5

### ISSUE THREAD

**Issue by LisaPerrier** [ovh/public-cloud-roadmap#380]
As a user in Harbor version 2.4.3,
I want to upgrade to the 2.5 version
So that I can benefit from latest features

Full list of features here :

2.5: https://github.com/goharbor/harbor/releases/tag/v2.5.0

**Comment by LisaPerrier** [comment]
Harbor version 2.5.6 is now available ! :)

**Comment by LisaPerrier** [comment]
New registries are now delivered in 2.5.6 version, all customers in version 2.x will be migrated if their upgrade policies allow it with an announced ETA.

**Comment by LisaPerrier** [comment]
Hello, all 2.4.3 versions will be migrated to 2.5.6 version on August 21st. You should all have received an email with the informations, if not, please contact me.

**Comment by mhurtrel** [comment]
All customer are now benefiting for Harbor 2.5.6.
