### ISSUE TITLE
Pay OVH with crypto

### ISSUE THREAD

**Issue by Francewhoa** [ovh/public-cloud-roadmap#383]
## User Story

As a OVH client, I need to be able to pay **OVH using a cryptocurrency (crypto)**. So that I benefit from:

* **Decentralized Crypto**
  I could pay OVH using decentralized cryptocurrency. Such as, but not limited to, https://www.getmonero.org et https://bitcoin.org

* **Redundancy**
  Suppliers of credit card, such as VISA, and PayPal, increasingly block the accounts of their clients who have feelings or thoughts they disagree with. Including lawful and peaceful feelings and thoughts. When this challenge happens, I would still be able to pay OVH using a decentralized cryptocurrency. Without any dependencies on a centralized credit card or PayPal supplier.

* **Increase OVH Income**
  An increasingly large number of hosting suppliers offer to their clients to pay in crypto. Such as, but not limited to, Bitcoin Web Hosting, Glowhost, Hawk Host, Heficed, Hosterbox, Hostwinds, Hostinger, JAVAPIPE, Namecheap, NameSilo, Shinjiru. In turn, OVH products would be more attractive. In turn, OVH could potentially increase its sales.

* **Stronger Privacy & Security**
  Crypto as a much stronger privacy and stronger security. In comparison, credit card and PayPal suppliers often sell their clients data for money.

Below is the same suggestion as above. But with Details if you're interested in those. Including suggested resolutions.

## Suggested Resolution

Feel really free to choose any crypto payment processing supplier to your liking. I suggest considering the options below. Including some who are both free and Libre Source (Open Source). Thus, stronger privacy and stronger security.

### Option: Taler

* Cost: Free

* Type: Self-hosting

* Backend software code: Libre (Open Source)

* Website: https://taler.net

* Note: This option is fully free. Except, OVH would have to pay for its hosting. I bet that OVH has plenty of this ;)

### Option: BTCPay Server

* Cost: Free

* Type: Self-hosting

* Backend software code: Libre (Open Source)

* Website: https://btcpayserver.org

* _Note: This option is fully free. Except, OVH would have to pay for its hosting. I bet that OVH has plenty of this ;)_

### Option: Taler Systems

* Cost: Paid

* Type: SaaS

* Backend software code: Proprietary

* Website: https://taler-systems.com/en/electronic-cash.html

* Note: 
  * Taler Systems offers both free and paid commercial services. Their free service is the other option above. Titled Taler.
  * Taler Systems offer either Crypto (Electronic Cash) or CBDC. I do NOT trust the CBDC option. Because it is centralized by a Federal Bank. Which have a long history of blocking transactions of clients who have feelings or thoughts they disagree with. Including lawful and peaceful feelings and thoughts. This challenge can easily be resolved by using any of the other Libre Source and self-hosted options above.

### Option: NowPayments

* Cost: Paid

* Type: SaaS

* Backend software code: Proprietary

* Website: https://nowpayments.io

### Option: CoinGate

* Cost: Paid

* Type: SaaS

* Backend software code: Proprietary

* Website: https://coingate.com

### Option: Paykassa

* Cost: Paid

* Type: SaaS

* Backend software code: Proprietary

* Website: https://paykassa.pro

### Option: BitPay

* Cost: Paid

* Type: SaaS

* Backend software code: Proprietary

* Website: https://bitpay.com/business

## Contribution

If needed, both me and the Ubertus.org team would be happy to contribute testing and documentation for this new feature.

**Comment by yomovh** [comment]
Thank you for taking the time to share your feature request with us. We truly value your input and appreciate your engagement in making our products better.

After careful consideration and analysis of your feature request, I regret to inform you that we will not be able to proceed with its implementation at this time. If our decision changes, we would open another issue. 

Best regards,

**Comment by Francewhoa** [comment]
Thanks for your consideration OVH team :)

**Comment by Francewhoa** [comment]
Hello @Alkorin @yesnault @antleblanc @baaastijn @rbeuque74 @nemobis @elbacilon @VincentCasse @DavidDelebecque @F-Legrand @thild42 @agoude @pdepaepe @fsamin @loopfz @guitdev @mhrng @mhurtrel @JacquesMrz @nicolaslacroux @baaastijn 🙂
  
OVH is presently doing a survey. If you are interested to use crypto to pay OVH services, the survey form is at https://satisfaction.ovhcloud.com/ovh/itw/answer/s/ 
Around 10 questions. The last one allows you to suggest payment with crypto.
