### ISSUE TITLE
XL or XXL Flavors for Public Cloud Gateway

### ISSUE THREAD

**Issue by francoisovh** [ovh/public-cloud-roadmap#385]
As a user, I want to choose flavor with more than 2 Gbs BW (ie : 5, 10)

**Comment by maylukas** [comment]
Same here. For us it's concerning that when creating a cluster, we're limited to 2Gbps of bandwidth

**Comment by yomovh** [comment]
**XL Gateway (4Gbps) are now available on all the public cloud regions.** 
2XL (8Gbps) should follow soon (on SBG5 / SBG7 / GRA11 / DE1)

**Comment by yomovh** [comment]
Hello @matmicro,
* For higher throughput (XL and 2XL), the resource allocation rule on our shared infrastructure involves slightly different consumption model on the undercloud resources, this explains why the price is not linear between S/M/L and XL/2XL.
* With regards to the metrics dashboard for Gateway, no ETA to share, sorry. 
I would advise to contact your OVHcloud sale representative to express your interest in the feature.

**Comment by MircoT** [comment]
There is any possibility to have a 3XL or a 4XL size?
