### ISSUE TITLE
Germany (DE1) region

### ISSUE THREAD

**Issue by mhurtrel** [ovh/public-cloud-roadmap#4]
Making the Managed Kubernetes Service available in our German Datacenter.

Notes/Existing workaround :
The featureset and pricing model will be the same as existing regions.
German customer can already benefit from the service in other regions, including SBG (Strasbourg, France) one.

**Comment by steffenmllr** [comment]
Any timeline here? have managed k8s within Germany would be a real benefit for our customers

**Comment by mhurtrel** [comment]
Hi @steffenmllr  ! We currently target either very late Spring or early Summer for DE and UK regions.

**Comment by maylukas** [comment]
@mhurtrel Is the timeline still up to date?

**Comment by mhurtrel** [comment]
Hello @maylukas no, unfortunately, we are reassessing a new date, probably late 2021. Sorry for the delay.

**Comment by mhurtrel** [comment]
We plan to open this region late october

**Comment by mhurtrel** [comment]
Hi @ZuSe This will unfortunately be delayed a little bit (November) due to a missing dependancy (integrated LBaaS) for Kubernetes.

**Comment by ZuSe** [comment]
Hi @mhurtrel  any update on it?

**Comment by mhurtrel** [comment]
We have cleared a blocker that was explaining the delay. Dur to the holday season, the feature should be prodded in January 2021. Sorry again for the delay.

**Comment by khaledavarteq** [comment]
@mhurtrel is there an update on the ETA of managed k8s in DE1? We need it because our customers insist on data centers in Germany.

**Comment by mhurtrel** [comment]
Hi @khaledavarteq  sorry again for the delay on several features, due to multiple factore, including COVID cases. We plan to open the region next week !

**Comment by khaledavarteq** [comment]
@mhurtrel thanks for the update, we're looking forward to get going with it! 👍

**Comment by mhurtrel** [comment]
@khaledavarteq @ZuSe @steffenmllr and others, the Managed Kubernetes Service is now available in our DE1 region !
