### ISSUE TITLE
Public Gateway (Distributed Virtual Router & Floating IPs)

### ISSUE THREAD

**Issue by JacquesMrz** [ovh/public-cloud-roadmap#40]
As a user, I want to create/configure/delete a virtual router highly available.
As a user, I want to create/release Floating IPs.
As a user, I want to live attach/detach Floating IPs to my compute nodes/virtual routers.

vRouter & Floating IPs to be billed on a pay as you go model.

Will be available in GRA9 at first (Openstack Stein).

**Comment by goldpanic** [comment]
Do this issue concerns OpenStack routers feature ?

**Comment by cambierr** [comment]
Since it was flagged as "coming soon" 2.5 months ago... Am I allowed to ask for news ? :)

**Comment by qualifio-infrastructure** [comment]
Any news ?

**Comment by JacquesMrz** [comment]
The BETA will officially open in the coming days.
Stay tuned.

**Comment by mhurtrel** [comment]
@JacquesMrz backporting here a request that we had multiple time on load balancer and kubernetes gitter channel : please make sure floating IPs are cross region and usable also in front of cloud load balancers (to make sure the traffic can be redirected if a region is down)

**Comment by rafalnn** [comment]
Any news? What is production ETA?

**Comment by DeepBlueMussel** [comment]
> The BETA will officially open in the coming days.
> Stay tuned.

Any news?

**Comment by cambierr** [comment]
@DeepBlueMussel it's open on GRA9

**Comment by DeepBlueMussel** [comment]
@cambierr Great! In the other hand for my use (and I assume for a lot of other users) my ressources are not located in GRA9 so it's kind of difficult to fully use it.
Also I assume that it's not officially released because if it were we should see it available on other AZ?
Thanks for the update

**Comment by JacquesMrz** [comment]
@cambierr , for the time of the BETA we decided to propose the feature only in GRA9.
For the GA, as OpenStack Stein version is mandatory to be able to deliver this feature, the availability of L3 Services (Virtual Router & Floating IPs) will follow the upgrade of our Public Cloud regions from OpenStack Newton to Stein.
GRA7 and GRA9 are for now the only Public Cloud regions running OpenStack Stein.
Nota Bene: same principles apply for LBaaS availability.

**Comment by dave-b-code** [comment]
@JacquesMrz Hi, is there any ETA on when managed kubernetes will be available in GRA9? Thanks.

**Comment by mhurtrel** [comment]
@dave-b-code  Our current estimate is late September or more probably somexhere in October for managed Kubernetes in GRA9

**Comment by wullon** [comment]
@JacquesMrz @mhurtrel could we have an update on this please?

**Comment by tanandy** [comment]
any news ?

**Comment by mscheer93** [comment]
any ETA yet?

**Comment by fraff** [comment]
The ~2 months are over ... any news ?

**Comment by salimidruide** [comment]
Any news on that topic?

**Comment by morphace** [comment]
Any news?

**Comment by Tharegorn** [comment]
Any news ?

**Comment by maxdelorme** [comment]
Any news ?

**Comment by youenchene** [comment]
Any news ?

**Comment by wullon** [comment]
Any news ?

**Comment by rcapraro** [comment]
Any update on this please?

**Comment by jslocinski** [comment]
Hey,
sorry, we've been so busy on the region upgrades and UI mockups that forgot to update here :) 
We plan to release: Gateway (DVR), Floating IPs and LoadBalancer (Octavia) in the comming weeks!
First shot Gateway with Floating IPs will come OpenStack+APIv6+Manager UI and LoadBalancer OpenStack+APIv6.
Second shot (few weeks later): LoadBalancer Manager UI.

Hope this is good, summer info for you.

**Comment by cambierr** [comment]
@jslocinski any plan per region ? thinking about BHS and SYD that are often far "late" compared to other regions

**Comment by jslocinski** [comment]
Hello, yes plan (as region upgrade is progressing) to release the first shot in: GRA9 | SBG7 | UK1 | DE1 | WAW1 | BHS5 | SYD1 and probably in SGP1 as well

**Comment by cambierr** [comment]
Great!

Sent from a typical smartphone. If this is illiterate, it’s the voice recognition’s fault.
________________________________

**Comment by dm-jnpstr** [comment]
Any updates?Really needed at DE1

**Comment by jslocinski** [comment]
Still closing minor tasks. Official comm should be launched soon, and you can expect GA a month later.

**Comment by JustDoItSascha** [comment]
So to get it right: When this Feature is implemented, I will be able to assign a predefined IP to a load Balancer of a Managed kubernetes Cluster? And when I delete the load Balancer and create a New one, I can give it the same IP again?
