### ISSUE TITLE
Upgrade to kernel version >= 5.6

### ISSUE THREAD

**Issue by vixns** [ovh/public-cloud-roadmap#401]
As a kubernetes user, as power consumption tends to become a major concern for our final users, I would like to monitor process consumption using https://github.com/hubblo-org/scaphandre.

Scaphandre use the `intel_rapl_common` kernel module to expose data in `/sys/class/powercap`.

KMS Nodes are using kernel 5.4. when loading the module the required files in `/sys/class/powercap` are not created.

Upgrading to kernels >= 5.6 should fix this issue, as mentioned in https://askubuntu.com/questions/1401888/modprobe-intel-rapl-common-no-such-device-on-intel-core-11th-i7-dual-boot-syste

**Comment by cortexx** [comment]
Hello @vixns 

We are working on a global upgrade of Managed Kubernetes nodes delivered for each MKS cluster. 
These nodes will be upgraded to Ubuntu 22.04 and the Kernel in its 5.15 version.

ETA: between April and May if we don't encounter any particular blocking.

-- Joël from the MKS team
