### ISSUE TITLE
Purge cache DNS

### ISSUE THREAD

**Issue by lenglet-k** [ovh/public-cloud-roadmap#405]
# Context

Google and CloudFlare proposed a system to purge DNS cache for same entry. Like here: https://developers.google.com/speed/public-dns/cache or here https://1.1.1.1/purge-cache/

It's possible to OVH to do the same things ?

Sametime we modify dns entry and the time for clear the is too long

**Comment by guitdev** [comment]
Hi,
It seems not to be in the plan.
Have you try to reduce TTL to 60 sec ?
Could you detail your use case please ?

**Comment by yomovh** [comment]
Closing the issue as this is not planned for now

**Comment by jas8522** [comment]
This would be handy. Too bad it's not planned :(
