### ISSUE TITLE
Kubernetes autoscaler: billing cycle awareness

### ISSUE THREAD

**Issue by cambierr** [ovh/public-cloud-roadmap#406]
One of our current uses of the MKS is auto-scaled CI/CD (based on Gitlab Kubernetes executor).

To achieve this goal, we configured a node pool with min one node and max 10, and gitlab executor is configured maximum 10*2 jobs (our config making max two jobs to fit on a single node at the same time).

When more capacity is needed, the auto-scaler does a decent job at providing more capacity even if the time of reaction between when a cluster is lacking resources and when the nodes actually becomes ready is quite long (too long for our production workloads).

Where this is more a problem is that the auto-scaler sometimes decide to scale down a node 30 minutes after it was started... or 61 minutes after it was started... despite a billing plan based on the amount of at-least-partially consumed windows of 1hour.

This lead to an over-billing of the actual usage of the resources and to avoid this, the only available solution at the time of writing is to build a custom script labelling nodes based on "how close they are from the end of a 60minutes window" to prevent their removal if we are too far from the end of the already-paid window.

This **may** somehow be linked to #67 but I think having a smarter auto-scaler without usage commitment remains something needed to stay competitive with other large providers billing on a per-minute basis.

To illustrate what I mean, here is a screen capture of today's usage:
* At 13h19 we seed a brutal scale-up of the cluster to handle a peak of many jobs
* At 14h42, there is a progressive scale-down because less work is offered to the cluster
* At 15h14 the auto-scaler re-provision a decent amount of resources

![Capture d’écran du 2023-04-19 21-03-26](https://user-images.githubusercontent.com/10885859/233174886-52a644ff-20f4-4a12-b457-a5364c67fa15.png)

Based on this, I would suggest:
* be able to "limit" the scale-up speed of a cluster (ex: no more than +1 node per minute given the time between the scale-up decision and the actual node availability in K8S)
* be able to prevent scale-down before the end of a paid time "window"
* be able to "limit" the scale-down speed of a cluster

**Comment by mhurtrel** [comment]
Hello @cambierr As we are moving towards Saving plans and not anymore attach billing to a specific instance, I am closing/rejecting this issue. I understand it still makes sense for current B2/C2/R2 in monthly, but I hope you understand we prioritize the developement of "cloud native" sustained used disccounts through upcoming (late sprint/early summer) saving plans, and invite you to use the workaround of using multiple nodepools in the meantime.
