### ISSUE TITLE
[MKS] support container optimized Linux distro

### ISSUE THREAD

**Issue by achevillard** [ovh/public-cloud-roadmap#415]
**As a** SRE
**I want to** be able to choose [Talos](https://www.talos.dev) as container optimized Linux distro.
**So that I** can improve security and limit the attack surface.

[Talos](https://www.talos.dev) provides the following features:

- it is immutable
- it is atomic
- it is ephemeral
- it is minimal
- it is secure by default
- it is managed via a single declarative configuration file and gRPC API

**Comment by henyxia** [comment]
That would be really awesome!

**Comment by mhurtrel** [comment]
Hello @achevillard . I officially close this issue and took the initiative to generalize its title.
Some more details :
We have strong expertise internally on securing and maintaining Ubuntu at OVHcloud, and we also see a lot of customers relying on the packages awailable in this widely uses distribution.

Though I totally agree in the interest of offering the alternative of a container-specialised light distribution for efficiency, we see this small advantage (small when considering compute power of an average worker node) not being woth the extra effort needed for our operation, support teams and many customers. 

Of course we may reconsider this at a later (longer term) stage.
