### ISSUE TITLE
UDP support with OVHcloud Managed Kubernetes LoadBalancer

### ISSUE THREAD

**Issue by Sporesirius** [ovh/public-cloud-roadmap#416]
Add UDP support to the OVHcloud Managed Kubernetes LoadBalancer.
https://help.ovhcloud.com/csm/en-public-cloud-kubernetes-known-limits?id=kb_article_view&sysparm_article=KB0049873
"The use of the UDP protocol is not supported."
EDIT: And add UDP Proxy Protocol support for the LB

**Comment by yomovh** [comment]
Hello @Sporesirius @matmicro 
Thanks for your issue. 
This should be supported when we will provide built in integration between MKS and Public Cloud Load Balancer (aka Octavia) see this [issue](https://github.com/ovh/public-cloud-roadmap/issues/104) since UDP is supported by Octavia. 
However, we need to be sure that the integration is OK for UDP.

**Comment by Sporesirius** [comment]
Hi @yomovh ,
Thanks for the response.
Is Octavia also going to support mixed protocols for TCP and UDP? K8s got support for that in 1.26, see https://github.com/kubernetes/enhancements/issues/1435

**Comment by LisaPerrier** [comment]
Hello, we confirm this feature is correctly integrated :)

**Comment by LisaPerrier** [comment]
A private BETA has been planned, if you are interested contact me on Discord.

**Comment by yomovh** [comment]
Since this will be implemented by #104 I propose to close the issue.

**Comment by yomovh** [comment]
Hello,

I confirm what is said by @antonin-a :
UDP is already supported. Source IP propagation with UDP (through Proxy protocol for instance) **is not**. Issue for the feature request is [here](https://github.com/ovh/public-cloud-roadmap/issues/508).  Currently its status is `Acknowledged` which means that "_These issues have been review by OVHcloud staff that confirmed alignment with our strategy._"
However they are not yet `Prioritized` ("_These issues should be addressed within the next 9 to 12 months_") nor `Planned` ("_These features/improvements should be released within the next 2 to 3 months_")

**Comment by rezasmt** [comment]
Any update on this? This limitation is literally the only reason that we cannot migrate to OVH from Azure!

**Comment by antonin-a** [comment]
Hello @rezasmats, is your requirement to use UDP on OVHcloud Load Balancer or UDP + Proxy protocol ?
First option is already supported, that is why this issue is closed.
Second option is tracked here : https://github.com/ovh/public-cloud-roadmap/issues/508

**Comment by rezasmt** [comment]
> Hello [@rezasmats](https://github.com/rezasmats), is your requirement to use UDP on OVHcloud Load Balancer or UDP + Proxy protocol ? First option is already supported, that is why this issue is closed. Second option is tracked here : [#508](https://github.com/ovh/public-cloud-roadmap/issues/508)

I'm not really sure about the underlying system. I tried to create a Service object in Kubernetes with type LoadBalancer and Protocol UDP and it was not working. TCP was fine.
We need that for OpenVPN UDP.

Thanks

**Comment by rezasmt** [comment]
any update on this?
