### ISSUE TITLE
HPA min and maxReplicas update (not mandatory fields)

### ISSUE THREAD

**Issue by matmicro** [ovh/public-cloud-roadmap#419]
As a MKS user i would like to be able to use HPA more easily.

`minReplicas` and `maxReplicas` values are currently mandatory.
Thus if i try to update other settings from my existing HPA, i get the below error :
```
* spec.maxReplicas: Invalid value: 0: must be greater than 0
* spec.maxReplicas: Invalid value: 0: must be greater than or equal to `minReplicas
```

I would like to be able to upgrade a current HPA without specifying those fields, thus in that case it should keep the current value.
In case those values are missing on creation by default, it should be 0 in order to avoid issues.

Thus i could be able to update an HPA y using kube apply -f values.xml  with contextual values without resetting all values already set.
Is it possible to change the behavior in that way ?

**Comment by LisaPerrier** [comment]
Closing this issue as problem seems to be Kubernetes's and not OVH's
