### ISSUE TITLE
MySQL Public Cloud: How to download a backup file and restore it with another database name?

### ISSUE THREAD

**Issue by biapar** [ovh/public-cloud-roadmap#421]
MySQL Public Cloud: How to download a backup file and restore it with another database name?

**Comment by thild42** [comment]
Closing as duplicate of #390

**Comment by thild42** [comment]
@biapar Hi.

If the goal is to restore a backup with another database name, you could do it through the Control Panel or the API.
Here is a guide helping you through this procedure: https://help.ovhcloud.com/csm/en-gb-public-cloud-databases-restore-backup?id=kb_article_view&sysparm_article=KB0048968

However if the goal is to download a backup, you currently won't be able to do it.

**Comment by biapar** [comment]
Will be this feature?
