### ISSUE TITLE
Object storage bucket name

### ISSUE THREAD

**Issue by pierreedbrg** [ovh/public-cloud-roadmap#425]
After contacting the support, it is said that It is not possible to create 2 buckets with the same name in the same region as there is a limitation in the infrastructure.
As an example, trying to create a bucket with the name "test" is not possible in a public cloud project as it is already used by another customer.

would it be possible to allow the bucket names to be set to whatever even though a bucket with the same name exists in the datacenter ?

**Comment by lason-ovh** [comment]
OVHcloud Object storage has a global namespace. (i.e. No two S3 buckets can have the same name.) It's similar to how DNS works where each domain name must be unique. Therefore, you need to use a unique bucket name when creating S3 buckets.
