### ISSUE TITLE
Kafka schema registry ACL automation

### ISSUE THREAD

**Issue by Jibux** [ovh/public-cloud-roadmap#428]
## Context
Today, it is not possible to use API/Terraform to grant a Kafka user access to the schema registry (only avnadmin user can). This prevent us to fully automate our Kafka databases creation.

## What should be done
Be able to modify Kafka schema registry ACL via API/Terraform.

**Comment by thild42** [comment]
We will be working on this on the next weeks.

**Comment by thild42** [comment]
Closing as duplicate of #433.
