### ISSUE TITLE
Kafka Schema Registry ACL support from API

### ISSUE THREAD

**Issue by thild42** [ovh/public-cloud-roadmap#433]
## User story ##

As a customer I want access control lists to be supported for Schema Registry so that I could manage Kafka user access rights to control access to individual Karapace schema registry REST API endpoints and to filter the content the endpoints return.

## Acceptance criteria

- I can create, retrieve and delete ACL
- I can configure following rights: schema_registry_read, schema_registry_write
- I can configure rights for per resource per user
- Available through the API

## Follow, vote and give your feedback

You can follow this task with the notification on the right tab.
Ask us anything here in the comments below, and vote with emojis for most requested items !
👍 to vote for this issue

## Discuss on Discord

Feel free to discuss with us on  https://discord.gg/ovhcloud

**Comment by thild42** [comment]
To be more specific, what we are working on is the ACL support for Kafka Schema Registry.

**Comment by thild42** [comment]
I have updated the issue so that it reflects what we are working on.
Sorry for the confusion my initial description was not good enough.

**Comment by thild42** [comment]
@FritschAuctores for regular ACLs on topics you can check the following guide: https://help.ovhcloud.com/csm/en-ie-public-cloud-databases-kafka-getting-started?id=kb_article_view&sysparm_article=KB0048944

**Comment by FritschAuctores** [comment]
@thild42 Thanks for the information, we have forwarded our request to support
