### ISSUE TITLE
Object Storage - Standard performance (new class of storage)

### ISSUE THREAD

**Issue by JacquesMrz** [ovh/public-cloud-roadmap#44]
As a user, I want Object Storage coming through and with a wide coverage of S3 standard APIs, with standard level of performance.

Beta test will open soon (25 April 22)

- API call included
- Incoming traffic included
- Outgoing traffic toward OVHcloud Services included
- Billed per GB per month/per GB of outgoing traffic (going out of OVHcloud)

**Comment by PhilippeVienne** [comment]
Is it a different service from Swift ? 

For us the "Outgoing traffic toward OVHcloud Services included" is a real game changer to use a such service with our services. We are hosting a GitLab instance and we currently run Minio for S3 API, if we can have a S3 service within OVH Network free of outgoing traffic (between S3 and our GitLab instance) this will be great.

**Comment by JacquesMrz** [comment]
Hi @PhilippeVienne,
The coming Object Storage offer (Standard & High Perf as well) will rely on S3 API standard.
Glad to hear from you the move we're about to make regarding the outgoing traffic will better answer your needs (likely done on purpose).

**Comment by Izaia64** [comment]
Beta test of Object Storage Standard Performances will be opened in GRA the 25th of April 2022

**Comment by VeridisQ** [comment]
> Beta test of Object Storage Standard Performance will be opened in GRA the 16th of May 2022

Hi. I know it is early for this kind of question but is there any documentation or guide on how to use the new Standard Object with the S3 API ? Will it be possible to just specify the endpoint in the aws sdk for example for it to work?
Will it appear as a new option when creating a bucket or will it replace the older swift version?
![image](https://user-images.githubusercontent.com/54961609/169294012-041b09d6-70e8-43a9-b825-6a4a598bc502.png)
Thanks.

**Comment by Izaia64** [comment]
In GA (general availability) in Gravelines 
Next to come, scope 1:  Canada, Strasbourg & US (Q4 2022)
Next to come, scope 2:  Roubaix, UK, Varsovie, Limbourg (Nov-Q1 2023)

**Comment by Izaia64** [comment]
GRA, SBG and BHS are now opened : https://docs.ovh.com/fr/storage/object-storage/s3/location/

**Comment by frabe1579** [comment]
How about DE-DE1 region?

**Comment by Izaia64** [comment]
LIM (Limbourg) is planned in March

**Comment by JacquesMrz** [comment]
If it can help: DE1 (OpenStack Region) is located in Limburg Germany (LIM).

**Comment by frabe1579** [comment]
I'm trying to create a bucket via OVH API, but I can't find the correct endpoint of the API.
There is `/cloud/project/{serviceName}/region/{region}/storage`, but it only create high performance storage.
Where can I find information about it? No success with guides or via community.

**Comment by Izaia64** [comment]
Here is the doc on geolocation : https://docs.ovh.com/gb/en/storage/object-storage/s3/location/
All documentation on object storage is here : https://docs.ovh.com/gb/en/storage/object-storage/
