### ISSUE TITLE
Cloud Database: backup node backup with a different interval time ( not one day only ). How to?

### ISSUE THREAD

**Issue by biapar** [ovh/public-cloud-roadmap#445]
It's possible to plan the node backup with a different interval time ( not one day only )?

**Comment by thild42** [comment]
You can change the backup window but not the interval between backups.
You could check our guide on automated backups for more information: https://help.ovhcloud.com/csm/en-gb-public-cloud-databases-backups?id=kb_article_view&sysparm_article=KB0048699

**Comment by biapar** [comment]
Ok, but 24h it's a bit long interval for important db.

**Comment by thild42** [comment]
Indeed 24h would be a bit long for backup intervals. That is why you have access to Point In Time Recovery. As you could see in the documentation page I mentionned earlier, the backup frequency is "continuous", technically and for MySQL example, that means that on top of regular backup we use the binary log.

The result is that you could restore your database at any point you wish to between now and now + backup retention. For more information on backup retention that depend on the plan you subscribed to, see https://help.ovhcloud.com/csm/en-gb-public-cloud-databases-mysql-capabilities?id=kb_article_view&sysparm_article=KB0049173#backups
