### ISSUE TITLE
s3 bucket website hosting set up according to the tutorial does not work [reproducibly]

### ISSUE THREAD

**Issue by christophehrke** [ovh/public-cloud-roadmap#451]
The s3 bucket website hosting, which was set up following the tutorial https://help.ovhcloud.com/csm/en-public-cloud-storage-s3-static-website?id=kb_article_view&sysparm_article=KB0058067, does not work. 

We followed all steps of the tutorial:

created s3 bucket (tried performance vs non performance, tried other regions)
=>
![image](https://github.com/ovh/public-cloud-roadmap/assets/42517949/affafdab-a2d1-4428-8709-ea95d0d3bc2b)

uploading website ressource index.html as content/html:
![image](https://github.com/ovh/public-cloud-roadmap/assets/42517949/e45b50a0-945f-42e1-a365-30481dc79e41)

retrieving ressource to ensure content type is correct:
![image](https://github.com/ovh/public-cloud-roadmap/assets/42517949/e53bd25e-2fc6-4b36-badd-ef339ff8ec52)

set acl public-read to ressource and retrieve to verify
![image](https://github.com/ovh/public-cloud-roadmap/assets/42517949/9e9fc51e-c2b4-4aa3-8d7c-27bd7be651ee)

set acl public-read to bucket and retrieve to verify:
![image](https://github.com/ovh/public-cloud-roadmap/assets/42517949/bbf0b64e-8802-4bc5-8199-cca74ff8df07)

created website configuration with command:
![image](https://github.com/ovh/public-cloud-roadmap/assets/42517949/1e701314-95da-4cb4-b5c7-b86d4afa0815)

retrieving website configuration with command in order to validate configuration:
![image](https://github.com/ovh/public-cloud-roadmap/assets/42517949/b3ce8027-0948-45c2-bd45-57230301c77e)

According to tutorial we are done here:
https://performance.s3.sbg.perf.cloud.ovh.net/index.html
=>this works!

**What i expected from website hosting is, that https://performance.s3.sbg.perf.cloud.ovh.net works as well and shows index.html. This is not working.**

PS: i won't open a support ticket again on this because my technical details got completly ignored although i explained it more than once. therefor i tried this way.
PPS: https is working (tutorial says it won't work) but http is not working. We are evaluating s3 website hosting for an internal project; we are currently not sure if this is a productive-ready feature.

**Comment by lason-ovh** [comment]
> 

Hi we are sorry that you couldn't get the help you needed from support. By any chances, do you have a Discord account? I'd suggest to take it to Discord for better communication

**Comment by christophehrke** [comment]
Hey lason. Thanks for reaching out. Appreciated. I did not have discord acc until now but i created one as we are still consider to use ovh static website hosting with object storage. Please contact me via: christoph_omx in discord

**Comment by lason-ovh** [comment]
> 

you can use this invite link to join our discord: https://discord.gg/ovhcloud

**Comment by lason-ovh** [comment]
I suggest we close this issue as Github is mainly used for feature requests. We can continue on Discord

**Comment by alexandervlpl** [comment]
@christophehrke Same exact problem, did you ever find a solution? Is something missing in the tutorial?
