### ISSUE TITLE
Instances: Not possible to deleta a backup used for a restore

### ISSUE THREAD

**Issue by biapar** [ovh/public-cloud-roadmap#459]
Hi, if I try to delete an old instance backup used for a restore, the system give this error:

Italian
**Al momento non è possibile eliminare questo backup in quanto risulta installato su queste istanze: .....**

Eng
**At the moment it is not possible to delete this backup as it is installed on these instances: .....**

Thanks.

**Comment by yomovh** [comment]
Pull request to state this limitation in the doc => https://github.com/ovh/docs/pull/5220
