### ISSUE TITLE
Add LB size support

### ISSUE THREAD

**Issue by LisaPerrier** [ovh/public-cloud-roadmap#464]
As a Managed Kubernetes User 
I want to specify a LoadBalancer size when ordering an external load balancer in Managed Kubernetes service
So that I can allocate the appropriate resources for my application's traffic handling needs

**Comment by LisaPerrier** [comment]
Private beta users can access this feature at creation with a given annotation on the dedicated Discord Channel

**Comment by antonin-a** [comment]
This feature is already supported on our Public Cloud Load Balancer (currently in alpha)
