### ISSUE TITLE
Multicloud and Multicluster Kubernetes Management (including self-managed clusters)

### ISSUE THREAD

**Issue by mhurtrel** [ovh/public-cloud-roadmap#467]
A future OVHcloud managed service will cover those 3 use cases : 

1. Self-managed clusters with Bring Your Own infrastructure (Hybrid or Multicloud)
As a Platform team
I want to self-managed Kubernetes clusters based on existing infrastructure (VMs or Baremetal), wherever it is
So that i can leverage and modernise onprem or multicloud infrastructure, and build cross-regions clusters, using a supported opensource Kubernetes distribution

2. Multicluster management
As a Platform team
I want to manage multiple Kubernetes clusters in the same tool 
SO that I can benefit from a single UI. CLI and observability across multiple cluster to apply common policies and increase my productivity.

3. Service catalog
As a Plaform Team
I want to leverage an application service catalog
so that I can deploy and upgrade tools on multiple clusters and/or extend it with my own application packages to build a self-service IT catalog

Note : We plan to release an private beta in Autumn 2023 and GA in Spring 2024.
The service will require internet connectivity at first and will support vRack / OVHcloud connect at a later stage.

**Comment by mhurtrel** [comment]
This new product is called "Managed Rancher Services" and we just moved it in alpha (aka private beta) phase on https://labs.ovhcloud.com/en/managed-rancher-service/ !
Please fill the short form on the labs page to ask for private access under beta terms and conditions now. We will progressively cover more use cases and target a GA of this product in Spring.

**Comment by antonin-a** [comment]
We are pleased to announce that Managed Rancher Service is now available on OVHcloud Public Cloud !
