### ISSUE TITLE
MKS in GRA11 to Use GPU flavor (a100) as worker node

### ISSUE THREAD

**Issue by antonin-a** [ovh/public-cloud-roadmap#470]
As a OVHcloud Managed Kubernetes Service (MKS) user
I want to be able to use the new GPU flavor A100 available on the public catalog (https://www.ovhcloud.com/fr/public-cloud/gpu/) as a worker node for my k8s clusters. 

NB: it seems that those flavors are only available on GRA11 region ATM.

**Comment by mhurtrel** [comment]
Hi @antonin-a . I Confirm gra11 is on its waybfor the new few months and will also expose a100 flavors. My colleague @LisaPerrier will share a more precise ETA soon
