### ISSUE TITLE
Managed DB plan downgrade

### ISSUE THREAD

**Issue by matmicro** [ovh/public-cloud-roadmap#494]
As a Managed DB user i would like to downgrade plan (from API and UI).
Eg: Going from Enterprise to Business, or from Business to Essential plan.

Could you provide ETA for this feature ?

**Comment by thild42** [comment]
We will probably make a first step by providing support of this feature by API and only for Aiven engines.

**Comment by thild42** [comment]
The feature is available through the API.
The UI will follow.
