### ISSUE TITLE
United Kingdom (UK1) region

### ISSUE THREAD

**Issue by mhurtrel** [ovh/public-cloud-roadmap#5]
Making the Managed Kubernetes Service available in our Bristish Datacenter.

Notes/Existing workaround :
The featureset and pricing model will be the same as existing regions.
Bristish customer can already benefit from the service in other regions, including GRA (Gravelines, France) one.

**Comment by mikeee** [comment]
@mhurtrel From the DE1 region notes it seems that the UK public cloud was coming to the MKS soon, is there an update by any chance?

**Comment by mhurtrel** [comment]
Hi @mikeee i don5 have yet an eta to share on UK launch sorry. Note that the service os available from GRA region, wirh very low latency from uk

**Comment by mhurtrel** [comment]
We are currently targeting a May release for this last missing region :)

**Comment by mhurtrel** [comment]
Hello to everyone following this issue ! The opening of Managed Kubernet in UK is planned within the next 10 days.

**Comment by mhurtrel** [comment]
The service is now open in UK1.
This also means our service is now available in all OVHcloud public cloud cities !
