### ISSUE TITLE
Managed Rancher Service (MRS) to provide Managed Kubernetes Service (MKS) cluster driver

### ISSUE THREAD

**Issue by antonin-a** [ovh/public-cloud-roadmap#510]
As a Managed Rancher Service user I would like to use a [cluster driver](https://ranchermanager.docs.rancher.com/how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/about-provisioning-drivers/manage-cluster-drivers)  so that I can easily deploy and manage OVHcloud Managed Kubernetes Service clusters.

Please react to this Feature Request by adding a thumb up and do not hesitate to comment to show your interest and/or share your use cases !

**Comment by antonin-a** [comment]
It is now possible to use our Managed Kubernetes driver for OVHcloud Manager Rancher under Beta phase, please refer to our online doc:  https://help.ovhcloud.com/csm/en-gb-public-cloud-managed-rancher-service-getting-started?id=kb_article_view&sysparm_article=KB0061909

**Comment by matmitch** [comment]
Hi, is the cluster driver available for import ? I have a mix of OVH managed k8s and self-hosted baremetal, i would like to be able to manage my ovh k8s cluster from my internal rancher master instance.

**Comment by antonin-a** [comment]
Hello @matmitch not yet but we plan to release it publicly. Probably this summer at the same time as we release our Managed Rancher in GA.

**Comment by matmitch** [comment]
Hello @antonin-a, thank you for your answer, can't wait for it to be available.

**Comment by matmitch** [comment]
Hi @antonin-a any news on the public availability of the rancher driver ?

**Comment by antonin-a** [comment]
Hello @matmitch, Managed Rancher Service general availability is planed for this September and we will publish the driver in the following months. We just want to have a clean first version of the driver as it is currently changing a lot.

**Comment by antonin-a** [comment]
We are happy to announce that Managed Rancher Service is now in General Availabiliy alongside our Managed Kubernetes Service (MKS) cluster driver. Those driver will be published on our public Github soon.

**Comment by antonin-a** [comment]
@matmitch we close this issue related to MKS driver inside Managed Rancher, for driver publication you can refer to #639
