### ISSUE TITLE
PaaS: When Will you update the services?

### ISSUE THREAD

**Issue by biapar** [ovh/public-cloud-roadmap#528]
I tried your PaaS service by Platform.sh and it's good and simple, but I had to pass direct to Platform.sh because their control panel and the services are updated and they have more functions like monitoring, choose a Region, etc...
When you put in the monitoring and the possibility to choose a different your datacenter?
Thanks.

**Comment by yomovh** [comment]
Hello & thanks for your issue.

The platform.sh upgrade is currently not in our roadmap so I will close the issue as `not planned`

**Comment by biapar** [comment]
Will you give some services like platform.sh?
