### ISSUE TITLE
[MKS] Support gen3 flavors (b3,c3,r3) for worker nodes

### ISSUE THREAD

**Issue by antonin-a** [ovh/public-cloud-roadmap#529]
As a customer I would like Managed Kubernetes Service (MKS) to support new [gen3 flavors](https://github.com/ovh/public-cloud-roadmap/issues/352) so that I would be able to deploy MKS worker nodes based on those new  flavors (b3, c3, r3).

**Comment by antonin-a** [comment]
Hello here, many of you seem to be waiting for gen3 on MKS, and we thank you for that. If all goes well, we should be able to offer them before the end of this month (jan 2024), the only constraint being to properly manage the fact that monthly billing doesn't exist on these flavors. 
Stay tuned !

**Comment by antonin-a** [comment]
Good news, gen3 flavors b3,c3,r3 are now supported as worker node flavor for MKS on GRA11, DE1 and UK1 regions. New regions will be added as these flavours become available on Compute side.

**Comment by antonin-a** [comment]
Hello @matmicro, from what I know it is not planed but you can raise a new requirement on Compute side (https://github.com/ovh/public-cloud-roadmap/issues/352).

**Comment by jonathon2nd** [comment]
I was wondering when they will be available for bhs3. I can deploy VM, but not k8s nodepool.

![image](https://github.com/ovh/public-cloud-roadmap/assets/52681917/ba833383-f667-4e93-8ce9-8699a8b4ed2a)
![image](https://github.com/ovh/public-cloud-roadmap/assets/52681917/2841bbc1-4725-43e4-93c8-8467b11a8465)

**Comment by clement-igonet** [comment]
> Good news, gen3 flavors b3,c3,r3 are now supported as worker node flavor for MKS on GRA11, DE1 and UK1 regions. New regions will be added as these flavours become available on Compute side.

I don't see gen3 instance in GRA11 selection:

<img width="520" alt="image" src="https://github.com/ovh/public-cloud-roadmap/assets/7684243/b02279b7-61fe-4b21-93c2-9b6e64459ca9">

<img width="1184" alt="image" src="https://github.com/ovh/public-cloud-roadmap/assets/7684243/e1c06c9b-f9b1-40ce-8bde-655a9539a592">

What could have missed ?

**Comment by yomovh** [comment]
@clement-igonet  I am not able to reproduce your issue. I am able to choose B3-XX flavors for a MKS cluster in GRA11. 
Can you please open a ticket ?

**Comment by antonin-a** [comment]
@clement-igonet can you try to clear your cache and/or test with another web browser ?

**Comment by clement-igonet** [comment]
I confirm it was a matter of cache.
It has finally worked well, after emptying the cache and using an "incognito" mode.

**Comment by SLoeuillet** [comment]
I saw yesterday Gen3 available in managed K8S interface on BHS5 but when I tried, it complained on OpenStack side that "r3-64" flavor did not exist. Then today, Gen3 are gone from OVH Console (on managed K8S, those are still present on compute side)

We'll wait a bit more

**Comment by jonathon2nd** [comment]
I am still not able to use gen3 for k8s, even though it has been available on compute side.

![image](https://github.com/ovh/public-cloud-roadmap/assets/52681917/3b4f7226-0447-4670-81c6-19d3e4d8999a)
![image](https://github.com/ovh/public-cloud-roadmap/assets/52681917/53345849-53bc-4934-8334-172b12dad908)

**Comment by jonathon2nd** [comment]
Working now, thanks!

**Comment by SevenGroupParis** [comment]
Any chance to have B3 instances on MKS GRA5 ?

**Comment by clement-igonet** [comment]
As SBG5 is forgotten, we'll switch to GRA11.

Do we have some improvements about MKS node **autoscaling** (far more than 5 minutes) ?

**Comment by tominou** [comment]
Any plans to provide B3s on MKS GRA5 ?

**Comment by tominou** [comment]
Any update when other regions will get b3s ? Or should we just all move to gra11 ?
