### ISSUE TITLE
Ability to change network configuration of existing managed kubernetes cluster

### ISSUE THREAD

**Issue by maylukas** [ovh/public-cloud-roadmap#543]
As an OVHcloud customer using the Managed Kubernetes Service
I want to be able to change the network configuration of existing kubernetes clusters
so that the cluster does not have to be re-created in order to move it to a different private network or from a public to a private network.

**Comment by mhurtrel** [comment]
Hi @maylukas this is doable through a cluser reset operation (keeping your nodes for example if you have monthly nodes enables), and we do not plan to enable "on the fly" changes has this would break in many cases.
