### ISSUE TITLE
Providing SUPERUSER access to the PostgreSQL databases.

### ISSUE THREAD

**Issue by sachinnnaik** [ovh/public-cloud-roadmap#551]
The user is requesting superuser access to the PostgreSQL database to perform activities such as terminating PIDs, changing custom passwords for users, and initiating a database VACUUM process.

Current status:
As our Public Cloud Databases products are managed services, we do not provide superuser or root access for these types of products.

Future request:
Can we implement SUPERUSER access for PostgreSQL databases created under the OVH Public Cloud Project in the future?

**Comment by sachinnnaik** [comment]
Hello @thild42,

Thank you so much for the provided information. Is that possible to restart the DB for the customer through OVH platform?

**Comment by thild42** [comment]
Hello @sachinnnaik.

It is not possible to restart a service. This is a feature that is often request but usually for bad reasons.

What is it you want to achieve through a service restart ?

**Comment by sachinnnaik** [comment]
Hello @thild42 

The restart task was a request from one of our customers. I am working with the customer and trying to get more details about it.

Thank you for your timely response.
