### ISSUE TITLE
Serverless functions like AWS Lambda on OVHcloud

### ISSUE THREAD

**Issue by MUsman1992** [ovh/public-cloud-roadmap#553]
Is it possible to create serverless functions like AWS Lambda on OVHcloud? I have tried to find online how we can create serverless functions on OVHcloud but i think, it's not as much simple as AWS Lambda. Can anyone guide me in this regard? Thanks

**Comment by antonin-a** [comment]
Hello @MUsman1992 it will depend of your use case, is the idea is to easily deploy function or batch computing in a serverless way, an identified option is the deploy [Knative](https://knative.dev/docs/) on top of our Managed Kubernetes Service. We have a detailed guide available here: https://help.ovhcloud.com/csm/fr-public-cloud-kubernetes-install-knative?id=kb_article_view&sysparm_article=KB0055148
At the moment you can't find 'as a Service' solution that is providing cloud services event driven functions on OVHcloud, but it is on our mid/long term roadmap.

**Comment by MUsman1992** [comment]
@antonin-a thanks for your reply. yes, I have also seen that technologies like Knative, OpenFaaS can be used to write serverless functions in the Kubernetes cluster but in my case, I want to trigger serverless function when a file is uploaded in Object storage but my understanding is that in OVHcloud, we can not register such events to execute some kind of serverless function if some file is added or deleted from Object Storage,

**Comment by mhurtrel** [comment]
Hi @MUsman1992 just confirming this is aknowledge and will be developped but is not prioritized in the short term.

**Comment by mhurtrel** [comment]
merged with https://github.com/ovh/public-cloud-roadmap/issues/205
