### ISSUE TITLE
MKS High Speed Gen2 Blockstorage

### ISSUE THREAD

**Issue by MrOffline77** [ovh/public-cloud-roadmap#565]
As an OVHcloud customer with MKS 
I would like High Speed Gen 2 Block Storage to be available in all K8S clusters that live in a supported region for storage
so that we can use block storage with higher IOPS throughput for data processing e.g. databases / data analytics. I expect OVH to roll out a storage class to all those in a supported region.

**Comment by MrOffline77** [comment]
Hi, thanks for the feedback. 
I understand the approach of waiting for #476. However, the issue becomes relative from 100GB volume size. HighSpeedG2 supports up-to 20K IOPS which is more than described in the linked beta page for #476. In my Universe 100G for a Database is almost the bare minimum I would deploy :D. Anyway, I have already tested and manually rolled out the HighSpeedG2 storage classes without any problems. However, we do not use them, as I assume that there may be reasons why OVH has not yet rolled them out for MKS.
Until #476 is ready, the provision of HighSpeedG2 for existing clusters would be perfectly fine for me. The question is which workload needs 10GB storage but generates 15K IOPS ? I can only think of super edgy cases off the top of my head. 
In our case, we use the RAW disk devices and create our own Ceph cluster, which generates Encryption at Rest. In doing so, we lose about 50% of the performance of the HighSpeedG1 storage. The G2 storage would help us massively to increase the IOPS here. Our Databases and Services then consume the Encrypted Storage.

**Comment by antonin-a** [comment]
Hello @MrOffline77, thanks a lot for you feedback.
A short update to let you know that capability to support highspeed-gen2 as storage class for MKS clusters has been prioritized and will be available by this summer. 
We will keep you updated.

**Comment by AntoineMicheaOpencell** [comment]
hello @antonin-a, can you please provider delivry date ?

**Comment by antonin-a** [comment]
Hello @AntoineMicheaOpencell we are currently working on it and it should be available by beginning of August, I will update here when ready !

**Comment by AntoineMicheaOpencell** [comment]
Hi again @antonin-a, any chance to be released before 15th ? I've planned maintenance for customers and i really need this new storage class

**Comment by nicolaslacroux** [comment]
Hello everyone, 

 
We are pleased to inform you that our Managed Kubernetes Service (MKS) now supports [High Speed Gen2 Blockstorage](https://www.ovhcloud.com/en/public-cloud/block-storage/?_gl=1*en4irh*_gcl_aw*R0NMLjE3MjA2MjY0MTUuRUFJYUlRb2JDaE1Jajd6azdlaWNod01WSkUxQkFoMUw3Z00wRUFBWUFTQUFFZ0p0Y1BEX0J3RQ..*_gcl_au*MTU2MDUzMTY4OS4xNzE3NDE0ODk5LjExNDA0NTk4MDAuMTcyMDcwNTk0My4xNzIwNzA1OTQz) as a Storage class for your Kubernetes volumes . This new feature will significantly improve the performance of your applications deployed on MKS. 

**What is High Speed Gen2 Blockstorage ?** 
High Speed Gen2 Blockstorage is a high-performance storage solution designed to deliver higher IOPS (Input/Output Operations Per Second) and throughput speeds, while ensuring low latency. It is ideal for mission-critical applications that require fast access to data, such as transactional databases, analytics applications, and more. 

 
**How do I activate it ?** 
Enabling High Speed Gen2 Blockstorage on your MKS clusters is simple. 
Simply update your MKS cluster with the new patch version offered. 

 
**How do I use it ?** 
To use High Speed Gen2 Blockstorage on your MKS clusters, simply select csi-cinder-high-speed-gen2 as the Storage class for your Kubernetes volumes . 

 
To learn more about this feature and how to use it, please refer to our [technical documentation](https://help.ovhcloud.com/csm/en-public-cloud-kubernetes-set-up-persistent-volume?id=kb_article_view&sysparm_article=KB0049955#storage-classes) or contact our support team, who will be more than happy to assist you. 

We are convinced that this new feature will bring added value to your operations and allow you to get the most out of your Kubernetes environments. 

Please feel free to contact us if you have any questions or would like to discuss this new feature in more detail.
