### ISSUE TITLE
[MKS] Kubernetes 1.29

### ISSUE THREAD

**Issue by kikefdezl** [ovh/public-cloud-roadmap#566]
As an OVHcloud customer using Managed Kubernetes, I want the k8s version in MKS version to be upgraded from 1.28 -> 1.29, so that I can use the new `SidecarContainer` feature which is enabled by default in version 1.29.

https://kubernetes.io/blog/2023/12/13/kubernetes-v1-29-release/

**Comment by antonin-a** [comment]
Hello @kikefdezl  please note that k8s 1.29 is now available.
![image](https://github.com/ovh/public-cloud-roadmap/assets/17782936/c19b3e7a-8c55-4a1c-9661-12c9bfb08fe1)
(if you do not see it on the OVHcloud Control Panel try to refresh your cache)

Note :
This new version is available in all regions where MKS is available
It is available both for new cluster creation and for existing clusters using N-1 (1.28) minor version using Upgrade feature.
We will force upgrade n-5 minor version cluster shortly after this released (concerned customers will be contacted by email).

More info on the new version are available on Kubernetes official repo: https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.29.md

**Comment by kikefdezl** [comment]
Thank you! I was mislead by this page here:

https://help.ovhcloud.com/csm/en-ie-public-cloud-kubernetes-plugins-software-versions-reserved-resources?id=kb_article_view&sysparm_article=KB0049970

**Comment by antonin-a** [comment]
@kikefdezl oh yes good point, we are currently updating the doc. Thank you for raising this point !
