### ISSUE TITLE
[MRS] Update to Rancher 2.8.7

### ISSUE THREAD

**Issue by nicolaslacroux** [ovh/public-cloud-roadmap#572]
As an OVHcloud customer using Managed Rancher Service, I want upgrade my current Rancher version(2.8.2) to 2.8.7 .

So as to benefit new features and enhancements provided by this release, like the support of Kubernetes 1.28 for your downstream clusters as indicated on the official support matrix (https://www.suse.com/suse-rancher/support-matrix/all-supported-versions/rancher-v2-8-7/)

https://github.com/rancher/rancher/releases/tag/v2.8.7

**Comment by rverchere** [comment]
Be careful, v2.8.6 is a Prime version, not community.

**Comment by nicolaslacroux** [comment]
Hello @rverchere, 

The Managed Rancher Service product benefits from extended support for patch versions provided by SUSE.

We plan to work on the release of the patch version and the upgrade in the next few days
