### ISSUE TITLE
Unused MKS automatically deleted

### ISSUE THREAD

**Issue by matmicro** [ovh/public-cloud-roadmap#586]
As a MKS user, i do not want an empty cluster to be deleted automatically.

I received an email informing that "Managed Kubernetes Service : Votre cluster xxxx issue du Public Cloud xxxx sera automatiquement supprimé".

As a PRA, we are using empty clusters that we do not want to get deleted automatically because they are not used.
Indeed we are using it as a backup MKS in case of severe incident that will need to perform a switchover.

Is there a way to avoid this ?

**Comment by antonin-a** [comment]
Hello @matmicro, the current MKS offer is free of charge and that leads to a huge number of created clusters that tends to inactive for years. 
We are keen to limit the number of unused resources on our platforms, not only to limit the management workload but also to minimize our ecological footprint. 
Despite this, I fully understand your use case. We are planning to launch a premium MKS offer (including SLAs) for which we will not auto-delete clusters.

In the meantime, as stated in our terms and conditions: "A cluster is considered active when it orchestrates at least one active worker node and/or is configured with a persistent volume" so an easy and cost-effective solution is therefore to create a 1 GB Persistent Volume in your cluster so it won't be inactive.
