### ISSUE TITLE
Upgrade of pgvector Postgres extension to 0.7.x

### ISSUE THREAD

**Issue by hmans** [ovh/public-cloud-roadmap#587]
As an OVHcloud customer using **Public Cloud Managed PostgreSQL**
I want **the [pgvector extension](https://github.com/pgvector/pgvector)** to **be upgraded to the 0.7.x branch**
so that **I can use its new features, starting with Index Subvectors and Binary Quantization**.

I appreciate that [pgvector](https://github.com/pgvector/pgvector) is available on your managed Postgres instances, currently in version 0.6.2. pgvector 0.7.0 (released in April '24) introduced some big new changes that would help us optimize our vector indexes both in terms of performance but also size. The latest version available is 0.7.4.

An upgrade to a more recent version would be highly appreciated.

**Comment by hmans** [comment]
Thanks for your feedback, we'll give this a try.

**Comment by thild42** [comment]
Cool, keep me posted.
