### ISSUE TITLE
Object Storage - Standard performance multi AZ

### ISSUE THREAD

**Issue by Mickael-Roger** [ovh/public-cloud-roadmap#59]
A class of storage (S3 endpoint) geo-replicated

**Comment by cambierr** [comment]
Fyi, you can use `X-Container-Sync-*` features to do this: that's what we use to replicate our docker registry across most of our OVH POPs

**Comment by darthShadow** [comment]
+1 to this idea.

---

@cambierr Thanks for the idea. Do you have any docs or articles for reference on how to accomplish the same?

**Comment by cambierr** [comment]
sure, here it is: https://docs.ovh.com/gb/en/public-cloud/sync-object-containers/

**Comment by agoude** [comment]
Closing this issue as it is related to two different topics:
1) Geo-replication, issue already released (#179)
2) Multi-AZ (3-AZ region) Object Storage service, issue available here (#623)

Thank you!

**Comment by agoude** [comment]
hi! just closing this issue as we have created two ones related to the statement here:
1) Geo-replication, issue already released (#179)
2) Multi-AZ (3-AZ region) Object Storage service, issue available here (#623)

Thank you!
