### ISSUE TITLE
pgvecto.rs PostgreSQL extension

### ISSUE THREAD

**Issue by olivierlemoal** [ovh/public-cloud-roadmap#598]
It would be advantageous to include the [pgvecto.rs](https://github.com/tensorchord/pgvecto.rs?tab=readme-ov-file) extension for managed PostgreSQL (it is Apache licensed).
While we currently utilize pgvector, we are restricted to vectors with a maximum size of 2000 dimensions.

**Comment by thild42** [comment]
Are you currently limited by the max size of 2000 offered by PGVector? If so I am interested to know what is the model embedding you are using.

Most of the open-source and popular text embedding models produce vectors with less than 2000 dimensions.

**Comment by olivierlemoal** [comment]
We are using the `text-embedding-3-large model` from OpenAI, which creates embeddings with up to 3072 dimensions. However, it seems pgvector accepts them anyway; though we are not sure if they are truncated in some way.

**Comment by thild42** [comment]
Thanks for the pointer. That is an interesting thread.

From my end, I have checked the roadmap and we have no plan to support `pgvecto.rs`.

I think the only workaround you have is to test the solution described in the `pgvector` thread, namely Scalar quantization with 2-byte (fp16) floats (halfvec). Maybe you already have ?

**Comment by olivierlemoal** [comment]
We misconfigured Langchain, resulting in no index being created. As a result, we were able to insert embeddings of any size. 
I will take a look at `halfvec`; however, the underlying library `pgvector-python` does not allow for much customization.

**Comment by thild42** [comment]
I will close this issue, thanks for submitting it and for the detailed use case.

Do not hesitate to update me if you were to test/found a workaround the limitation of 2000 dimensions.

**Comment by SebG-js** [comment]
Is it difficult to support pgvector-rs ? 
It is very fast, very scalable.
Simple pgvector extension is very limited to manage large embedding model.

**Comment by thild42** [comment]
How difficult would it be, I can't tell.
For our Database service we have partnered with Aiven and are subject to their roadmap.

Recently `pgvectorscale` was added so maybe there is hope for `pgvector.rs`.

I'll ask again to Aiven if there is any plan for this extension.
