### ISSUE TITLE
Public Cloud Instances - Shelve / Unshelve

### ISSUE THREAD

**Issue by JacquesMrz** [ovh/public-cloud-roadmap#69]
As a user I want to be able to shelve my Public Cloud Instance through the customer control panel.
As a user I want to be able to unshelve my Public Cloud Instance which has been previously shelved through the customer control panel.

Shelving a Public Cloud INstance will suspend the billing of the instance for Hourly billed instances.
The storage needed to store the data of the instance will be billed during the time the instance is shelved.

The user can unshelve the instance at any time, he will get back his resources (IP address included), and his data.

Feature available as well through OpenStack API.

**Comment by telenieko** [comment]
> Shelving a Public Cloud INstance will suspend the billing of the instance for Hourly billed instances.

On Monthly billed instances this should work too, maybe:

  1. There is not billing effect until the end of the month (this is already billed)
  2. Instance *won't* be billed at start of month as long as it is SHELVED
  3. When unshelved, if still on Monthly, the prorata will be applied (just the same as when creating monthly instances mid-month)

Unshelving an instance on the same month as it was shelved should have no billing impact at all.

**Comment by JacquesMrz** [comment]
@telenieko , Shelving an monthly instance has currently no interesting effect on the billing.
We will change/solve this with what is coming with https://github.com/ovh/public-cloud-roadmap/issues/67
We basically need to manage/monitor the consumption regardless of Instance IDs.

**Comment by telenieko** [comment]
> @telenieko , Shelving an monthly instance has currently no interesting effect on the billing.
> We will change/solve this with what is coming with #67
> We basically need to manage/monitor the consumption regardless of Instance IDs.

I understand that a shelved instance, regardless of wether it was pay-as-you-go or monthly, simply won't be billed at all (except storage costs) mostly because the concept of "monthly instance" changes when #67 is in. ou might simply be paying unused commitment, etc.

thanks

**Comment by telenieko** [comment]
Just noticed this has been moved to Coming Soon (apparently github does not send emails on those changes or I missed it). ¿Do you have an ETA?

**Comment by JacquesMrz** [comment]
> > @telenieko , Shelving an monthly instance has currently no interesting effect on the billing.
> > We will change/solve this with what is coming with #67
> > We basically need to manage/monitor the consumption regardless of Instance IDs.
> 
> I understand that a shelved instance, regardless of wether it was pay-as-you-go or monthly, simply won't be billed at all (except storage costs) mostly because the concept of "monthly instance" changes when #67 is in. ou might simply be paying unused commitment, etc.
> 
> thanks

I do agree with your understanding, I confirm this is the target we have with #67 . Meanwhile, monthly instances will be charged even if they're shelved.

BTW: the feature has been released. Available through API (OVHcloud API & Openstack API) as well as in the OVHcloud customer control panel.

**Comment by matmicro** [comment]
Do you mean that currently, a shelved instance pay-as-you-go   will not be billed ?

**Comment by JacquesMrz** [comment]
> Do you mean that currently, a shelved instance pay-as-you-go will not be billed ?

As soon as a pay-as-you-go instance is shelved, you are only billed for the storage needed to store the data of the instance.

**Comment by telenieko** [comment]
> > Do you mean that currently, a shelved instance pay-as-you-go will not be billed ?
> As soon as a pay-as-you-go instance is shelved, you are only billed for the storage needed to store the data of the instance.

I am at a loss now. This issue is marked as coming soon, but per this comment it is already implemented ?

Anyway, it is awesome news, I was just about to delete some old instances that I can just switch to pay-as-you-go and shelve !! 
Amazing news!

`openstack server shelve` is my new best friend for the week.

**Comment by matmicro** [comment]
> I am at a loss now. This issue is marked as coming soon, but per this comment it is already implemented ?

I was also confused with this.
For my old knowledge i was assuming this was not the case. I don't know for how long this is available...
 
> Anyway, it is awesome news, I was just about to delete some old instances that I can just switch to pay-as-you-go and shelve !!

Are you sure ? I think we cannot change a monthly billed instance to pay-as-you-go, right ?
It's not possible from Manager. Is it from API ?

**Comment by telenieko** [comment]
> > I am at a loss now. This issue is marked as coming soon, but per this comment it is already implemented ?
> I was also confused with this.
> For my old knowledge i was assuming this was not the case. I don't know for how long this is available...

Maybe @JacquesMrz can confirm, and clarify then what is "coming soon"

> > Anyway, it is awesome news, I was just about to delete some old instances that I can just switch to pay-as-you-go and shelve 
> Are you sure ? I think we cannot change a monthly billed instance to pay-as-you-go, right ?
> It's not possible from Manager. Is it from API ?

[You are right](https://docs.ovh.com/us/en/public-cloud/change-public-cloud-billing-rate/), we will have to wait for #67 which will be sometime between fall 2021 and early 2022 apparently.

**Comment by telenieko** [comment]
This issue is `Open` though it is marked as released.
Though the missing piece is shelving of monthly billed instances.
Maybe close this issue and open a separate one for the missing piece? (Or just track the missing piece in #67)

**Comment by JacquesMrz** [comment]
@telenieko  you are right. As of today shelving monthly instances has no impact.
I will open a new issue to address that.
