### ISSUE TITLE
Managed Kubernetes - Allow activation/deactivation of Admission Plugins

### ISSUE THREAD

**Issue by abstract-entity** [ovh/public-cloud-roadmap#70]
Currently API server is configured with following parameter:
--enable-admission-plugins=AlwaysPullImages

Allow us to remove this parameters to make 'ImagePullPolicy' work. For 2 mains reason:
- Docker hub introduce a download quota since december for free account, people don't want to download every newest image. (save the forest !)
- If Docker hub is unavailable we still want our pod (iImagePullPolicy: IfnotPresent + Tag != latest) to startup if node got image in cache.

Thanks,

**Comment by cemonneau** [comment]
Hi, we would gladly like that feature too !
We use gitlab internally with their registry, and it happens that their API is not responsive (like every service), combine with some node/deployment restart and you can't start your pod. 
Thanks

**Comment by mhurtrel** [comment]
Hi @Chaya56  and @cemonneau  I confirm that we heard you and we will make this change? I dont have yet an ETA to share but will had this officially to the changelog and update here as soon as I have this information

**Comment by tsn77130** [comment]
Hi, I confirm this possibility is important for many cases, especially when registry is down like today, and node restart appears in the same time...

**Comment by hshimizu** [comment]
I'm voting for this feature. The container image pull time on the "AlwaysPullImages" is significantly longer.

**Comment by digiserg** [comment]
Adding to this, docker hub has a quota limit:

https://docs.docker.com/docker-hub/download-rate-limit/

**Comment by cemonneau** [comment]
Hi guys, I know you don't have ETAs, but was there some changes or discussions on your end ? 
Gitlab had an outage yesterday, right when we made some changes and it impacted us. 
Thanks

**Comment by bcouetil** [comment]
Hello 😊

First time for me on an OVH Kubernetes cluster, and shocked that this option is turned on by default, with no way to changed that, in an era of DockerHub quotas :cry: 

More than 2 months later, could we have an ETA ? 🙏

**Comment by mhurtrel** [comment]
hello @bcouetil I confirl this feature is currently under developpment. I cannot yet share an ETA for production, but this is now a matter of weeks.

**Comment by mhurtrel** [comment]
@bcouetil @cemonneau @digiserg @tsn77130 @hshimizu @abstract-entity 

The feature is now available API only. This API will be documented (including default values) and the Terraform provider will be updated in the next 2 l weeks to reflex this facultative additionnal parameters.

You can alreadu use it though these API routes :
https://api.ovh.com/console/#/cloud/project/%7BserviceName%7D/kube~POST for a new cluster
https://api.ovh.com/console/#/cloud/project/%7BserviceName%7D/kube/%7BkubeId%7D/customization~PUT to force a new customization on an existing cluster

![image](https://user-images.githubusercontent.com/24432524/188125941-0ec27b7b-8140-454f-93de-d2fc61ffd8c9.png)

Thanks for your patience !

**Comment by bcouetil** [comment]
Thank you 🙏

Can someone share a working curl command for existing cluster ? Thanks !

**Comment by cemonneau** [comment]
Hi, 
Great news ! we got caught up with gitlab maintenance today and pod restart, so we will look at changing the options next week.
What's the impact on a running k8s cluster : master node restart, nodes restart ? just to be sure of the impact on production cluster.

Thanks !

**Comment by matprig** [comment]
Hello,

Components API server/kubescheduler/controller manager are redeployed

best,

**Comment by mhurtrel** [comment]
@cemonneau and all , the featire is now documented : https://docs.ovh.com/gb/en/kubernetes/apiserver-flags-configuration/

**Comment by abstract-entity** [comment]
@mhurtrel Big thx

**Comment by mhurtrel** [comment]
The fetaure is deployed and documented but I reopen because we are waiting for UI integration

**Comment by scraly** [comment]
The feature is also available through the Terraform provider:
https://docs.ovh.com/gb/en/kubernetes/apiserver-flags-configuration/#configure-the-api-server-admission-plugins-through-terraform_1
:-)

**Comment by nicolaslacroux** [comment]
Hello everyone, 

The feature that manage activation/deactivation of Admission Plugins is now available in OVH console. 

![image](https://github.com/user-attachments/assets/7ffdebdb-6466-40cc-839e-3059ce9707e2)
