### ISSUE TITLE
Object Storage "static hosting" with SSL

### ISSUE THREAD

**Issue by dantart** [ovh/public-cloud-roadmap#72]
My request is to be able to use SSL when defining static hosting in object storage.

**Comment by lason-ovh** [comment]
Hi, does this new feature answers your need? https://github.com/ovh/public-cloud-roadmap/issues/351

**Comment by lason-ovh** [comment]
This feature has been released under https://github.com/ovh/public-cloud-roadmap/issues/351.
You can find the documentation [here](https://help.ovhcloud.com/csm/en-public-cloud-storage-s3-static-website-https?id=kb_article_view&sysparm_article=KB0058074)
