### ISSUE TITLE
Recoverable prorratas // Reserved Instances

### ISSUE THREAD

**Issue by telenieko** [ovh/public-cloud-roadmap#76]
Hi,

Currently OVH Public Cloud has two billing options on compute:

- Hourly, pay per hour the instance exists. Billed at end of period
- Monthly, pay up front for the whole month at about 50% discount.

This gives amazing pricing for consitent workloads but at the expense of flexibility. Any changes you plan you have to do them at the end of the month to make the most out of the up front payments.

I can think of two main scenarios:

1. Moving from flavor to another, like now that #46 is almost closed you have a bunch of `shared resources` instances on monthly payment and you want to move to the new instances.
2. Facing the need to recreate instances for some reason: you have to destroy a bunch of `b2-7` and create new ones in their place (ie: backup recovery, or adding and removing nodes to a k8s cluster).

Case 1. is not discussed here. If the user changes flavors they forego the remaining credit of the month. Plan ahead.

Case 2 is what this is about. Depending on when on the month you start destroying and recreating instances you either have to be careful and stick to the higher hourly pricing or risk paying lots of prorratas. Even though **your resource consumption is the same**.

Every cloud provider has something on this area: Reserved instances (AWS) or  Sustained Usage discount (GCP). Note than on both of those Case 2 doesn't pose any problem.

An idea that would work similar to current OVH pricing would be that of Reserved Instances: Instead of creating monthly instances I `pay upfront for 4 concurrent b2-7 and 2 c2-15`, then I create hourly instances and OVH discounts me at the end of the month for those covered by the upfront resource reservation.

**Comment by mhurtrel** [comment]
Hi @telenieko 
We tottaly agree we have improvment to do to allow commitment and discount while still offering the capability to dynamically recreate ibstances in a cattle approach. 

Actually we have another existing issue that covers it (with no eta yet) https://github.com/ovh/public-cloud-roadmap/issues/67 do you mind having a look at it and commenting if this totally corresponds to what you have in mind and vote for it, else comment below for adjustments?

**Comment by telenieko** [comment]
My bad for not seeing #67 earlier.
It is exactly what I meant here. Thanks.
