### ISSUE TITLE
Windows Server node pools

### ISSUE THREAD

**Issue by lluismontero** [ovh/public-cloud-roadmap#78]
Hi,

I would like to know if you have any plan to support windows server node pools to your kubernetes service.

**Comment by mhurtrel** [comment]
Hi @lluismontero 

We don't have plans to support managed Windows worker in Managed Kubernetes Services in the short/mid term future.

As you can see, we have high impact features in the hort term pipe that would address a significantly wider range of use cases. Additionally, the team in charge of the product has senior production experience with Unix based system and offering the same level of support for windows would be challenging.

At a more global level, I see very limited adoption and not huge perspective for this segment of the market at mid/long term (though of course this may change, and we could reverse this decision the long run).

However note that
- We plan, late this year, to allow unmanaged worker nodes to be registered to a managed Kubernetes cluster : https://github.com/ovh/public-cloud-roadmap/issues/20 this would I think allow you to add windows worker nodes that you would manage yourself.
-
- You can of course use OVHcloud public cloud Windows instances to host windows workloads outside of your cluster but within the same private network if needed and/or build your own self-managed Kubernetes cluster on our Public Cloud Windows instances.
