### ISSUE TITLE
Managed Registry in Canada (BHS)

### ISSUE THREAD

**Issue by mhurtrel** [ovh/public-cloud-roadmap#79]
Making the Managed Private Registry Service available in our Canadian Datacenter.

Notes/Existing workaround :
The featureset and pricing model will be the same as existing regions.
Canadian customer can already benefit from the service in other regions, including GRA (Gravelines, France) one.

**Comment by LisaPerrier** [comment]
Hello all, 
Managed Private Registry in Canada will be available in May :)

**Comment by LisaPerrier** [comment]
Hello all, this feature is now available, sooner than expected ! Thank you for your feedback, enjoy ! :)
