### ISSUE TITLE
No Swift endpoint in service catalog

### ISSUE THREAD

**Issue by SkypLabs** [ovh/public-cloud-roadmap#86]
Hi,

I am not sure if it is the best place to ask for help but your support was not able to solve my problem.

I tried to create an object storage container with the OpenStack CLI tool and Terraform, but in both cases I get an error saying that the Swift endpoint is not in the catalogue.

From Terraform:

```raw
Error: error creating OpenStack object storage client: No suitable endpoint could be found in the service catalog.
```

From the OpenStack CLI tool:

```raw
❯ openstack container list
public endpoint for object-store service in GRA7 region not found
```

I used the OpenStack API v3 and `GRA7` as region.

Is the object storage service only restricted to some specific regions? I cannot find this information in your documentation.

Thanks.

**Comment by XciD** [comment]
Hello, Swift region are not sufixed by numbers. You need to use `GRA` not `GRA7`

**Comment by SkypLabs** [comment]
Indeed, it works now!

Many thanks for your help.
