### ISSUE TITLE
K8 cluster in vRack

### ISSUE THREAD

**Issue by rafalnn** [ovh/public-cloud-roadmap#89]
As a customer, I want to be able to add a K8 cluster to vRack. Same as bare metal or cloud servers.

We use vRacks and vlans to improve the security of enterprise grade solution.
Having K8 cluster outside of a the vrack negatively affects our infrastrucure: security, complexity, maintanance, automations, deployment, audits.

**Comment by tanandy** [comment]
is not the same as https://github.com/ovh/public-cloud-roadmap/issues/15 ?

**Comment by mhurtrel** [comment]
yes indeed that is a duplicate of https://github.com/ovh/public-cloud-roadmap/issues/15 that in already alvailable in beta and will shoudl come with LB compatibilty in less that 2 weeks.
