### ISSUE TITLE
CORS access on private object storage

### ISSUE THREAD

**Issue by drzraf** [ovh/public-cloud-roadmap#95]
_Note: The feature proposal has been proposed via OVH support... and closed. It apparently led to my account at community.ovh.com being held and posts being flagged/hidden. I'm sorry I can't reference here the original topic where   the rationales and issues at pace were thoughtfully explained._

- As a **user of a private object storage**
- I want to make **use of it browse/download/upload from a browser / browser-based file-explorer**
- In order to avoid its use from a particular software, and provide my users with **particular file-viewing features (visualization, decryption, signature, ...)**

**Problem**: When the object storage is used from a browser, **CORS restrictions apply**... during the **authentication** (token gathering) phase : We **can't fetch `X-Subject-Token`** when calling `/auth/tokens`.

The reason this header is not available is that following header must be exposed:
> `Access-Control-Expose-Headers: X-Subject-Token`

But the preflight does not return some `Access-Control-Allow-Headers` that would allow the browser to fetch this header's value and continue.

The good thing is that this is **plainly configurable by OVH administrators in the OpenStack configuration**:
https://docs.openstack.org/keystone/pike/configuration/samples/keystone-conf.html
The value of "expose_headers" in the [cors] section is here for this.

In case of Ansible deployment  (https://docs.openstack.org/openstack-ansible-os_keystone/queens/), it's possible to use `keystone_extra_headers`.

Workarounds explored:
- We tried by using the S3 wrapper for a similar usage of our container and could get through the autentification. But could not got further because custom CORS/meta needed, while we configured them on the Swift object storage are not passed on by the s3 middleware.
- This is a limitation we reported (https://bugs.launchpad.net/swift/+bug/1905104)

I hope this **great feature** (private use of containers from the browser) **could be unlocked**, the stack of the problem analyzed (and the fact that I [got locked](https://community.ovh.com/en/u/RaphaelD) from community.ovh.com for suggesting it... be reconsidered [moderators can't be contacted]).

Thank you

**Comment by SDAChess** [comment]
I'm having the exact same issue with this. Hoping for a fix to work in the browser...

**Comment by tex0l** [comment]
I'm having this issue as well

**Comment by GTorreil** [comment]
We are having the same issue. Hoping for a fix to work in the browser as well.. This is a real deal breaker :(

**Comment by Guillaume-Fernandez** [comment]
I am having the same issue on Standard object storage - S3 API. Is it supposed to be released ?

**Comment by rverchere** [comment]
Hi,

I see this issue moved to "Released (Changelog). So is it implemented?

Does it also work on your "Standard Object Storage – S3 API" ?

**Comment by Izaia64** [comment]
It is working. We are working in a documentation to help users, it will be published soon.

**Comment by acouette** [comment]
hello @Izaia64 ,

Any update ?

Do you mean it is working for "S3 API" as well or only the "S3 object storage" ?

**Comment by acouette** [comment]
Thank you @CorentinStauder, indeed it works smoothly with the s3 client for the s3 object storage.

**Comment by lason-ovh** [comment]
Hi, you can find the documentation [here](https://help.ovhcloud.com/csm/en-gb-public-cloud-storage-s3-cors?id=kb_article_view&sysparm_article=KB0058275)
