### ISSUE TITLE
Managed MongoDB instances - Beta

### ISSUE THREAD

**Issue by baaastijn** [ovh/public-cloud-roadmap#97]
**THIS ISSUE IS FOR THE BETA PHASE ONLY**
For General Availability, please refer to : https://github.com/ovh/public-cloud-roadmap/issues/98

**User story**

As a customer,

I want to test and deploy managed MongoDB instances in OVH Public Cloud easily
So that I'm sure this service will fit my needs, I will gain time, and focus on my own job.

**Acceptance criterias :**

- I can launch new MongoDB instances via control panel / API
- Basic management via control panel / API (manage users, manage databases, manage ACL)
- Daily backups made by OVHcloud
- Community of Enterprise licence
- Pay as you go
- Private or Public network
- High-Availability (replica set)

**BETA phase limitations**
- Free during the whole beta phase
- Not ready for production.
- No SLA will be provided
-No official support from OVHcloud. Best effort
- We will do our best, but you may not be able to keep the services up when the product is generally available. 
- Only in European datacenter

**Comment by baaastijn** [comment]
Hello, since yesterday Public Cloud Databases for MongoDB is live ! 

More informations and offers
FR : https://www.ovhcloud.com/fr/public-cloud/mongodb/
EN : https://www.ovhcloud.com/en/public-cloud/mongodb/

Official Documentation in progress : https://docs.ovh.com/gb/en/publiccloud/databases

**Comment by matmicro** [comment]
As a user, from UI i can add easily a node.
But currently i cannot remove a node (scale down).

Could you plan to add this (at last for GA) ?
Thanks
