### ISSUE TITLE
Managed MongoDB instances - General Availability (prices added!)

### ISSUE THREAD

**Issue by baaastijn** [ovh/public-cloud-roadmap#98]
THIS ISSUE IS FOR THE GENERAL AVAILABILITY PHASE ONLY
For Beta please refer to : https://github.com/ovh/public-cloud-roadmap/issues/97

**User story**

As a customer,
I want to deploy managed MongoDB instances in OVH Public Cloud easily
So that I will gain time, and focus on my own job.

**Acceptance criterias :**

- I can launch new MongoDB instances via control panel / API
- Full management via control panel / API (manage users, manage databases, manage ACL)
- Daily backups made by OVHcloud
- Community Licence
- Pay as you go
- Private or Public network
- High-Availability (replica set)
- Official support and sustainable service (ready for production)

**Improvement compared to beta**

- More documentation/tutorials
- Ready for production.
- SLA will be provided
- Official support from OVHcloud.

**GA phase limitations**

- Some existing OVHcloud datacenters may not be available.
- Not read for MongoDB Enterprise licences yet.

**GA prices available**

![MongoDB GA Prices for Github](https://user-images.githubusercontent.com/83347449/128685204-36273652-a789-4687-9ec6-428e594a1224.png)

**Comment by sg-dsti** [comment]
Awesome! Looking forward to this game changer guys!!!

**Comment by baaastijn** [comment]
> Awesome! Looking forward to this game changer guys!!!

You can try the early access version for free today on our Public Cloud control panel ! free all summer (june/july/august)

**Comment by baaastijn** [comment]
Hello, MongoDB offers are now in general availability !
FR : https://www.ovhcloud.com/fr/public-cloud/mongodb/
EN : https://www.ovhcloud.com/en/public-cloud/mongodb/
